* 知识管理的定义
所谓知识管理，就是通过对存在于组织内、外部的个人、群体或团队中有价值的
知识进行系统地定义、获取、存储、分享、转移和利用等一系列活动，以达到其帮助
人们进行知识交流、提高组织生存能力及竞争优势的目的。知识管理帮助人们对拥有
的知识进行反思，帮助和发展支持人们进行知识交流的技术和企业内部结构，并帮助
人们获得知识来源，促进他们之间进行知识的交流。

知识管理主要依靠知识库中的知识被员工使用来发挥作用。员工首先要学习知识
库的知识，才能增长他们的才干，并在工作中做出正确的决策或提高工作的效率。根
据学习知识的不同，主要分为以下两个方面： 
1、  显性知识的学习 
显性知识是指，能用文字和数字表达出来的，容易以硬数据的形式交流和共享，
并且经编辑整理的程序或者普遍原则。企业只有通过学习显性知识，才能避免在激烈
的市场竞争中掉队，并在将它应用到生产实践活动中去的过程中，产生企业的部分核
心能力。 
2、  隐性知识的学习 
隐性知识是高度个性而且难于格式化的知识，包括主观的理解、直觉和预感。主
要表现为员工之间的相互学习，可以采取相互交流、隐性知识显性化等形式。 
总而言之，知识管理就是把对企业发展有用的各种知识收集存储于知识库中，供
员工进行各种类型的学习，提高他们的学习效率。知识管理只有通过组织学习，这些
知识才能化为员工工作的力量，让知识真正成为企业最重要的资源并发挥作用。知识
管理和组织学习是相辅相成，相互促进的，它们都将是在不远的将来企业致胜的法宝
* 知识管理的意义
知识管理（KM, Knowledge Management）是网络新经济时代的新兴管理思潮与方
法，管理学者彼得·杜拉克早在 1965 年即预言：“知识将取代土地、劳动、资本与机
器设备，成为最重要的生产因素。”受到二十世纪九十年代的信息化技术蓬勃发展，知
识管理的观念结合网际网络建构入口网站、数据库以及应用电脑软件系统等工具，成
为组织累积知识财富，创造更多竞争力的新世纪利器。 

随着知识经济的到来，知识对推动社会的发展起到了越来越重要的作用。尤其是
在 A 银行软件开发中心这样的知识密集型企业中，不仅需要输入大量的计算机专业知
识，而且在开发过程中也会产出大量的知识。如果能将知识管理策略与企业发展目标、
软件开发流程相结合，对相关知识进行沉淀、共享、应用学习和创新，就必然会提升
中心的整体软件开发及创新水平，从而提升核心竞争力。所以，实施知识管理对于提
高项目管理水平、提升人员整体素质、提升 IT 支持服务能力具有十分重要的作用。 



对于 A 银行软件开发中心来说，能够开发出符合监管部门要求，并且满足 A 银行
业务快速发展需求的系统是其首要任务。而无论是提高系统的开发效率和用户体验，
还是降低开发成本，都需要中心具备科学完善的知识体系结构。而中心内部完善的知
识体系结构，主要取决于中心所采取的知识管理策略。所以，为了提升其核心竞争力，
需要进一步提升知识管理策略。只有这样，才能不断提高中心整体的研发和创新能力，
才能不断提高开发系统的技术含量，满足 A 银行日益发展的业务需求。  
实施知识管理，可以使软件开发过程中的显性知识及隐性知识都能得到很好的记
录、分享，让知识发挥出它应有的价值。其意义有： 
（1）实现知识的有效积累及研发人员的不断成长 
通过将隐性知识显性化，并将所有的项目文档进行资源整合，使知识沉淀下来，
让研发人员在需要的时候，随时都能方便快速的查找到所需要的知识，从而提高所有
人的知识的利用效率，也使新入行的员工在较短的时间内迅速的成长起来。 
作为专业开发软件的银行部门，研发人员是所有知识创造的中心，是软件开发过
程中最重要的资源。知识管理通过帮助研发人员主动学习，让一个人的专长全部发挥
出来，更好的为中心服务。这其中也是一个相互的过程：研发人员头脑中的隐性知识，
通过深入挖掘，转变为了组织智慧；而组织智慧的日益丰富又会成为所有研发人员知
识创新的基础和保证。 
（2）让知识发挥应有的价值，促进知识的创新发展 
通过对经验教训的不断总结，避免同一错误的重复发生；通过对已有知识的挖掘
和掌握，加强了知识间的关联，提高项目的开发进度及效率，降低了成本；通过对新
技术及先进经验的主动引进，提升了新系统的用户体验及用户满意度，促进了技术知
识的创新。 
（3）避免重复劳动，提高分析及预测的能力 
在需求分析阶段，通过对过往知识进行筛选和分析，能够快速的把握业务部门的
需求，节省双方的沟通成本及时间，加快对业务部门提出需求的反应速度。 
在立项工作量的评估阶段，通过对过往项目相关知识的统计，可以对未来项目的
工期及工作量做出较准确的分析和预测。 
在开发阶段，如目标模块已有人在之前研究并实现过，就无需再花时间和精力去
进行重复的研究，直接“拿来主义”即可。 
在系统维护阶段，如遇到的问题刚好有人之前给出过完美的解决方案，就不用再
费心费力的做各种尝试，节省了解决问题的时间



1.1.3    创新压力 
习近平总书记在中国科学院第十七次院士大会、中国工程院第十二次院士大会上
说：“科技是国家强盛之基，创新是民族进步之魂”。这一提法，看出了国家在科技创
新方面的重视程度。 
近几年，由于互联网金融的猛烈攻势，给本就竞争激烈的银行业更增添了一把火。
互联网金融以更低的服务门槛，更方便的操作方式，更多样化的产品结构，对传统银
行业造成了不小的冲击。传统银行业只有转变观念，优化流程，提高服务质量和服务
效率，才能在激烈的市场竞争中立于不败之地。 
A 银行软件开发中心作为 A 银行所使用系统软件的开发部门，承载着 A 银行全面
信息化建设的艰巨任务。众所周知，在当今日益激烈的银行间竞争中，谁能更快速的
响应并满足客户的金融需求，谁能更好的把控银行风险水平，谁就更有竞争力。银行
间的竞争说到底是金融产品和服务的竞争。金融产品的创新和服务离不开银行信息系
统的支持和保障。可以说，A 银行软件开发中心的软件开发水平、开发效率、创新能
力对于整个 A 银行的经营业绩有着举足轻重的影响。而软件产品技术复杂，涉及的环
节众多，稍有不慎或缺陷，就可能导致严重的后果。这就要求 A 银行软件开发中心既
要打牢知识基础，又要了解并跟踪时下流行的新技术新成果，与时俱进，从而形成 A
银行软件开发中心区别于其他 IT 公司的核心竞争力，才能高水平的支撑起 A 银行业务
的快速发展。 

知识管理的目的，就是为了保证人们能在需要知
识时，第一时间将其找到。它是一门运用到管理学、信息技术、心理学等知识的综合
性学科。

** 具体到银行科技部的知识管理作用
（2）根据对 A 银行的总体战略及业务 IT 战略的分析，得出知识管理的三个长期
目标：提高项目管理水平、提升人员整体素质和提升 IT 支持服务水平。 
（3）根据知识运转模型和马斯洛需求层次理论，结合中心的实际情况，推导出知
识管理的四个短期目标：知识沉淀规范化、知识共享习惯化、知识应用和学习有系统、
知识创新有激励。 
（4）针对问卷调查所反映出来的问题，制定了知识管理应该遵循的原则：全员参
与原则、与软件开发流程相结合原则与员工绩效相关联原则。 

** 科技部知识的特点
A 银行软件开发中心属于信息系统软件的研发部门，在系统开发过程中涉及到软件
工程相关知识及其经验技巧的运用。 
瀑布模型是对于软件开发阶段流程进行划分的一个过程，可以分为需求分析、软
件设计、代码编写、软件测试、上线维护五个阶段。它通过将以上阶段顺序展开，并
为项目提供了按阶段划分的检查点。A 银行软件开发中心的绝大多数项目都是按照瀑
布模型的方法开展的，每个阶段的显性知识和隐性知识如表 2-3 所示。 
 
表 2- 3 软件开发各阶段知识内容 
开发阶段  显性知识  隐性知识 
需求分析阶段 
业务需求书，需求分析完善建议，
需求规格说明书，评审记录，专业
业务知识文档，需求分析规范文档 
需求获取途径，与业务部门的交流
过程与沟通技巧，监管部门政策规
定及业务经验等 
软件设计阶段 
概要设计文档，详细设计文档，评
审记录 
设计功能与性能间的依赖关系，设
计模块间的耦合度，评审的原则 
代码编写阶段  代码，代码走查检查表  代码的实现方法及编码技巧 
软件测试阶段  业务测试用例，测试问题记录  测试的技巧方法，解决问题的思路 
上线维护阶段 
上线手册，用户手册，项目总结报
告 
系统配置管理技巧，问题解决方法 
 
通过上面的描述，可以看出软件研发过程中的的知识，主要有知识需求量大，知
识产出量大，隐性知识挖掘难度大，知识更新速度快四个方面的特点： 

*** 知识需求量大 
软件产品不同于大多数工业产品，他的开发过程主要依赖于开发人员高度智力投
入。开发软件本身就是一个需要依靠大量知识支持，而又会通过软件开发过程产生大
量知识的活动。 
软件在整个软件研发的过程中，涉及到软件需求分析、软件设计、代码编写、软
件测试、上线维护等多个方面的知识。只有将开发不同阶段产生的知识结合起来使用，
才能提高所开发软件产品的质量，降低开发成本。 
*** 知识产出量大 
A 银行软件开发中心主要负责 A 银行信息及业务系统的设计开发工作。由于开发环
节较多，所以在此过程中会产生大量的显性知识和隐性知识，如需求规格说明书、详
细设计文档、各类评审报告、发现的问题及解决方法等。而且随着各系统间的关联交
互及系统规模的不断扩大，其开发过程中产出的知识量也会有大规模的增加。 
*** 隐性知识挖掘难度大 
软件研发过程中，除了必须落实到纸面上的各类文档之外，还包括大量存储于研
发人员大脑中的经验教训及开发技巧。这些知识由于不易于分享，且会因为研发人员
的离职而使这部分宝贵的经验教训丢失，所以只有依靠形成知识分享的企业文化及一
定的刺激措施，才能将隐性知识显性化并进行储存和分享。 
*** 知识更新速度快 
在信息技术发展日新月异的今天，新产品和旧产品的更替速度在不断加快。这就
要求我们在软件开发过程中不断地积累和创新。只有这样，才能更好的服务于 A 银行
信息化建设，以支持 A 银行战略目标的早日实现。
* 知识管理的现状
近些年，国内外已经有很多公司开始将知识管理的理论知识应用在实践活动中，
其中包括西门子公司、惠普公司，国内包括华为公司、金蝶公司等。知识管理已经越
来越多的向企业管理中渗透，国内外众多企业已经意识到了可持续发展的核心其实是
维护知识资本，保持知识资本不断增值的过程，开始积极策划或开展知识管理工作。

王润良（2001）认为，知识创造的源泉是显性及隐形知识之间的相互转化，并据此提出了实施的三种策略[43]；
王江（2003）对隐性知识进行了分类，并提出利用隐性知识的四个策略[40]；
马宏建（2007）分析了知识创新与知识管理策略的关系，并提出了在不同知识创新阶段所采取的不同的知识管理策略[41]；
沈丽宁（2007）介绍了企业协同知识管理的战略、构成要素、实施策略及保障机制[42]；
唐绍东（2012）在对知识管理与企业核心竞争力进行分析的基础上，就如何通过实施知识管理，以达到提高企业核心竞争力的目的进行探讨[44]；
詹国梁（2012） 先构造了基于生命周期策略的知识管理模型，再介绍了基于此实施知识管理的策略和 步骤[2]。 

徐冬（2006）将软件开发过程和知识管理过程进行融合，发现软件开发过程实际是一个知识转化整合创造的过程，并对此进行了系统的分析和研究[14]；
冉升（2007） 介绍了维普公司实施知识管理活动的具体做法[6]；
杨钊（2008）针对软件开发过程中，团队成员间的信任机制及对知识管理的影响进行了研究[3]；
李春源（2009）通过分析软件开发组织对于知识管理作用、需求、分类及其之间的关系，提出了知识管理系统的功能设计方案[45]

Bierly Paul E(2009) 指出获取和利用知识是一个企业保持竞争优势的根本,尤其是对植根于员工的高度个人化的隐性知识的应,将成为影响企业竞争能力的关键因素

** 部门知识管理现状
A 银行软件开发中心自成立以来，非常重视软件开发过程中知识文档的管理工作。
但随着需要开发的系统越来越多，以及与同业软件开发中心的交流日益频繁，怎样将
这些积累和交流的知识成果有效的利用起来，同时加强知识保护制度，避免知识资产
的流失，这需要软件开发中心及时改进知识管理过程中暴露出来的问题。 
  此外，由于中心自开始进行知识管理以来，都是以各项目组质量管理人员兼职的
方式进行知识管理，而没有专门设立知识管理的部门。所以尽管各项目都有进行知识
管理工作，但从整个中心来说，知识管理工作还基本处于各自为政的状态，各项目组
之间很少在知识共享方面进行互联互通

A 银行软件开发中心目前在知识管理工作中遇到的问
题有： 
（1）知识维度 
虽然 A 银行软件开发中心在每天的软件项目开发过程中，会产生大量的知识，但
由于所有知识并未经过梳理，仅仅是在数据库中按照目录简单的做了存储，所以并没
有形成一个完整的知识体系，每个知识都是孤立存在的，他们之间的联系尚没有建立。 
另外，在隐性知识显性化方面，缺少适当的方式或模式对存在员工头脑中的隐性
知识进行挖掘，造成了宝贵的隐性知识流失。如果骨干员工离职，存在他头脑中的经
验技巧方法等隐性知识也随之带走，会给组织造成非常大的影响

（2）人员维度 
由于缺乏必要的激励机制，所以一些员工会对知识分享缺乏热情。 
因为未将知识管理与软件开发流程有机结合起来，知识管理成为了工作之外的额
外任务，增加了工作量，造成一些人对知识管理的抵触心理。有一些员工怕自己积累
了很久的经验教训技能贡献出去后，自身就失去了核心竞争力，从而被别人超越，所
以拒绝分享自己独有的知识。 
以上这些都导致了之前中心在项目开发过程中，虽然积累了不少文档，却始终没
有很好的将相关知识进行复用，造成了效率的低下及重复投资的现象发生。 

（3）管理维度 
虽然有中心领导对于知识管理的高度重视，但具体落实起来却存在行动力不足的
问题。尤其是没有设置一个专门的知识管理部门，来对知识管理工作进行落实和推进。 
在流程设置方面，未能将知识管理的过程与日常软件开发流程紧密结合起来，造
成了软件开发人员不得不花费额外的工作量去做知识管理，久而久之很难坚持下去。

（4）系统维度 
整个软件开发中心层面缺少一个专业化的知识管理系统，难以将所存储的知识进
行灵活的利用和分享。开发人员在需要知识时，却不知道该从哪里找、该咨询谁。 

基于 ITIL 的建设银行 IT 运维知识管理系统构件 P10
+ WIKI, SVN 文档仓库， ITIL 知识库，ITSM 知识库
+ 知识库的内容以单个系统和案例为主，主要是为项目级小范围的知识管理负责

* 知识管理运转的四个阶段
根据国内著名知识管理解决方案提供商——蓝凌公司的最佳实践目录，将知识运
转的环节分为了知识的沉淀、共享、应用和学习及创新四个环节。这四个环节形成了
一个不断螺旋上升的闭环。

（1）知识沉淀规范化 
软件开发中心各项目的文档是显性知识的主要载体，一般存储在数据库中。在文
档管理上，重视对软件开发过程文档的标准化和规范化管理。为此，中心在 2016 年组
织并通过了软件能力成熟度开发模型 CMMI-DEV 认证，这为文档的统一管理和流程
标准化提供了很好的条件。 
对于新入行的开发人员来说，通过规范化的培训及标准化的文档，可以对项目快
速的熟悉起来；而对于具有丰富开发经验的员工来说，规范化的文档不仅可以在需要
的时候，迅速定位所需知识的具体位置，提高开发效率；而且对隐性知识来说，可以
以规范化的方式进行显性化储存，以利于分享和传播。 
在项目管理方面，根据 CMMI 要求，项目的流程和文档规范是受控的，项目文档
在评审后要形成基线，这样可以保证文档在权威性的条件下，确保文档的时效性。 
A 银行软件开发中心需要管理的文档，涵盖了软件开发的各个方面，包括软件开
发流程、开发规范、纳入基线的项目文档、人员清单、周报日报、会议记录等等，这
些文档都是经过标准化的显性知识

（2）知识共享习惯化 
培养员工在日常软件开发过程中随时进行知识共享的习惯。这不仅需要将知识共享
活动与项目管理结合起来，在不增加研发人员工作量的情况下完成知识的分享工作，
还要对研发人员进行知识共享的教育。 
在软件开发中心内部，由于大部分的知识都是隐性知识，从人的本性来看，人是
不愿意主动将自己辛辛苦苦总结出的知识无偿提供给其他开发人员的。所以，需要对
其进行知识共享的教育，让他们认识到，在如今这个信息爆炸的年代，知识的更新日
益加快，再也不能像从前那样，靠掌握某一关键知识就可以一辈子不愁吃喝了。重要
的不是你的某个独特的隐性知识，而是你掌握知识的能力，这个是最为关键的。知识
给其他人共享了，只要有掌握知识的能力和经验，还会获得更多的知识。而通过别人
共享出的知识，自身也能得到提高。 
我们从小懂得一个道理：温故而知新。只有从过去的项目中总结经验教训，才能
使未来的项目开发过程更加顺利。对于每一个完结的软件开发项目，对其在设计、开
发、测试、上线等环节进行客观的评价，成功的地方需要总结，失败的地方吸取教训，
并由项目经理经组内讨论汇总后形成《事后分析报告》
对于总结过往系统而形成的《事后分析报告》，在知识管理团队的组织下，还需要
对其进行评审，评审后将其纳入知识库，以便其他开发人员调阅。

（3）知识应用和学习有系统 
知识管理的最终目的是让员工在需要某类知识时能马上找到。它是将企业的显性
知识及已显性化的隐性知识，在工作中充分的利用起来，从而为企业创造价值。 
在信息时代，将 IT 技术与日常软件开发流程、知识管理有机结合起来，对知识文
档进行分类存储，以形成完整的知识体系，方便员工随时取用。在隐性知识管理方面，
通过企业内部的专家人才库将擅长各个领域的专家进行汇集，以强化隐性知识的分享
及利用。

（4）知识创新有激励 
对于知识创新来说，要形成激励机制。
在物质激励方面，将知识积累、分享、创新与绩效考核体系相关联。将知识分享
的参与程度直接与每个人的薪酬福利相关联。 
由马斯洛需求层次理论可知，对在知识创新方面有所贡献的员工，不能仅仅局限
于物质奖励，有时候精神方面的奖励更为重要。精神方面的激励可以使员工在被尊重
和自我实现方面获得极大的满足感。精神激励方面采取的主要办法有： 
a）职业发展激励：对于知识分享和创新有突出贡献的员工，要考虑薪酬福利与职
位晋升方面的提升，并在外出培训等机会方面优先考虑。
b）荣誉激励：定期开展评比，设立创新先进个人、最佳贡献奖等，对知识创新方
面贡献突出者给予相应奖励。 
c）专家激励：对于知识贡献度大的员工，中心可以提名作为知识专家候选人，今
后的相关方面评审和咨询，及外出培训调研的机会，可以优先考虑该方面的专家。 


* 知识管理中存在的问题
基于ITIL的建设银行IT运维知识管理系统P10

+ 知识管理不易保存与积累
+ 信息共享程度偏低
+ 工作人员职位变动引起知识的流失
+ 学习培训渠道有限

建设银行在运维管理的过程中，也曾建立过一些运维文档的知识库，然
而，随着环境的日趋复杂，知识的膨胀，知识管理要求的提高，使得这种
简单的知识库无法满足知识生产、知识沉淀、知识分享和知识激励等一系列需求。



* 影响知识管理的因素 



** 人
人是知识管理中的关键影响因素，没有人参与的管理活动一切等于零。在知识管
理中，参与者的主动分享及相互合作的意识，都是应当重点关注的问题。 

通过建立专家人才库，使中心的各领域专家们可以在将他们各自宝贵
的经验教训显性化的同时，让每个遇到问题的人能及时准确的找到可以提问的人，促
进了沟通交流和中心隐性知识管理水平的提升。

知识浏览者、知识创建者、知识专家、知识管理员、知识管理流程经理，

** 机
知识管理技术是指能够协助人们生产、分享、应用以及创新知识的基于计算机的
现代信息技术。它不仅覆盖了知识生产、分享、应用以及创新的各个环节，同时又是
多种信息技术的集成，这些技术结合起来形成了整体的知识管理系统，为企业提供知
识管理服务

（6）A 银行软件开发中心知识管理系统权限控制 
在知识安全方面，我们对于知识管理系统制定了严格的权限管理功能。通过定义
不同的角色来设置不同的权限，来达到信息安全的目的。 
定义的角色主要有系统管理员、知识管理员、审批者、作者、阅读者、只读者，
他们的具体权限如表 4-3 所示。 
 
表 4- 3 系统用户角色权限控制 
用户角色  权限 
系统管理员  拥有所有的权限 
知识管理员  具有对知识库进行增删改及审批操作的权限 
审批者  具有对知识库文档进行审批操作的权限 
作  者  具有对知识库进行增删改操作的权限 
阅读者  具有对知识查看及下载的权限 
只读者  具有对知识查看的权限 

中心专家人才库的建立 

IT服务管理是IT管理中重要的一环，随着IT服务管理的日益深化，运营管理过程中累积了大量的服务信息资源，无论对于客户还是服务管理的内外部提供者来说，都是一笔丰富的知识财富，因此，服务台应该逐步演化成基于服务知识库的、向客户提供增值服务的信息和服务中心，并且通过知识挖掘和知识整合，不断完善服务过程，提高服务的效率和质量，提升客户的服务满意度。
除了通过服务台使用知识库满足服务的需求以外，还可以通过个性化的推送服务、论坛等手段获取丰富的服务知识。


*** 系统需要做到：
+ 有效整合企业IT运维的知识

  通过集中建设知识共享平台，有效地将过去分散在各个部分的运维知识整合起来，同时，针对运维工作特点，将知识库和设备资产、设备维护历史记录等关联，并通过提供知识地图等形式有效地对企业运维知识进行组织和管理。

+ 方便的知识检索功能

  系统不仅能够方便地进行全文检索，而且可以对word、excel等office档以及格式文档进行全文检索。
  
  具备中英文全文搜索，模糊搜索、按关键字搜索、，同义词搜索，按类型搜索等搜索方式。搜索结果中可展现搜索关键字的上下文。


+ 知识管理与日常运维工作流程有机结合

  将典型事件、问题解决方案、运维经验积累到知识库中。技术支持人员利用知识库中的知识，缩短故障解决时间，提高故障解决质量。

+ 能够给出知识质量评估的数据，发布知识评论

+ 访问排行榜

+ 知识订阅RSS

+ 知识收藏，点赞

+ 与运维操作联动起来

+ 故障案例库

+ 同义词匹配，NLP

+ 轻量级的流程设置

+ 提供知识入库接口，方便各渠道分享知识

+ 支持富文本，图片，视频，音频，链接

+ Markdown

+ 知识地图：知识地图可以显示知识点之间的相互关系，方便用户按相邻知识点查找知识。

+ 系统涵盖知识地图、内容管理、培训考试、知识社区、常用工具、系统管理等几个模块，完整的覆盖了知识探索、知识釆集、知识编辑、知识搜索、培训考试、知识展示、知识评价等知识应用模块



** 料
通过该平台，部门员工可创建和查询专业技术知识，业务人员可查询技术支持和服务咨询类相关知识。本期知识管理平台的用户主要为该银行总、分行部门人员，其中会涉及部分业务部门人员（这部分用户主要查询和浏览部门对业务部门支持的相关知识。知识内容主要为部门内部的技术知识和面向业务部门的支持知识，不包含业务部门的业务知识。


知识分类：IT 技术文档，管理制度，运维经验，常见问题，经典案例
** 法
一个企业要想实现知识共享，必须建立一种激励机制。这种激励机制可以是以积
分或者礼品的形式进行发放，可以是评奖以满足精神上的满足，也可以把知识管理成
果与 KPI 考核进行挂钩。总之，让愿意分享知识给他人的员工，获得一定的回报。只
有这样，知识管理活动才可以持续的开展下去。 

A 银行软件开发中心作为专业从事软件开发的组织，只有将知识管理与日常的软件
开发工作相结合，才能产生最大的效益。在实际软件开发过程中，A 银行是按照瀑布
开发模型的方法进行开发管理（如图 3-6 所示）。知识管理对瀑布开发模型之中每个阶
段有价值的信息进行定义、梳理、运用，以避免开发过程中重复或无用的知识的积累。 

*** 知识的评价标准

分享的知识数量，点击率，点赞数，引用数,点击率

** 环
企业文化从结构上看，分为精神层、制度层和物质层。精神层是企业领导和员工
共同遵守的企业基本信念、价值标准、职业道德等。它是企业文化的核心和灵魂，是
形成企业文化制度层和物质层的基础和原因。制度层规定了企业成员在共同的生产经
营活动中应该遵守的行为准则和风俗习惯。物质层是企业的表层部分，包括企业标志、
产品形象等，他们折射了企业的经营思想、经营管理哲学、工作作风和审美意识等。
而良好的组织文化可以使信息和知识的交流更开放、更畅通。 


* 结构
** 学习型组织与知识管理
学习型组织（Learning Organization），美国学者彼得·圣吉（Peter M. Senge）在《第五项修炼》（The Fifth Discipline）一书中提出此管理观念，即指在面临变动剧烈的外在环境的情况下，组织需要通过培养弥漫于整个组织的学习气氛、充分发挥员工的创造性思维能力而建立起来的一种有机的、高度柔性的、扁平的、符合人性的、能持续发展的组织形态，以维持竞争力。
无独有偶，著名管理学者彼得·杜拉克早在 1965 年也曾预言：“知识将取代土地、劳动、资本与机器设备，成为最重要的生产因素。”

而知识管理（KM, Knowledge Management）是网络新经济时代的新兴管理思潮与方法，它通过对存在于组织内、外部的个人、群体或团队中有价值的知识进行系统地定义、获取、存储、分享、转移和利用等一系列活动，以达到其帮助人们进行知识交流、提高组织生存能力及竞争优势的目的。
知识管理帮助人们对拥有的知识进行反思，帮助和发展支持人们进行知识交流的技术和企业内部结构，并帮助人们获得知识来源，促进他们之间进行知识的交流。

由此可以看出，知识管理本身不是目的，它其实是建设学习型组织的手段而已。
** 实施知识管理的意义

随着知识经济的到来，知识对推动社会的发展起到了越来越重要的作用。尤其是在信息科技部这样一个知识密集型组织中，不仅需要输入大量的计算机专业知识，而且在开发，测试和运维过程中也会产出大量的知识。
实施知识管理，可以使软件开发过程中的显性知识及隐性知识都能得到很好的记录、分享，让知识发挥出它应有的价值。其意义至少包括： 
（1）实现知识的有效积累及研发人员的不断成长
通过将隐性知识显性化，使知识沉淀下来，让科技人员在需要的时候，随时都能方便快速的查找到所需要的知识，从而提高所有人的知识的利用效率，也使新入行的员工在较短的时间内迅速的成长起来。 
（2）让知识发挥应有的价值，促进创新 
通过对经验教训的不断总结，避免同一错误的重复发生；通过对已有知识的挖掘和掌握，加强了知识间的关联，提高科技人员知识理解程度；通过对新技术及先进经验的主动引进，提升了系统的开发效率和运维稳健度，促进技术知识的创新。 
（3）避免重复劳动，提高分析及预测的能力
比如在软件的需求分析阶段，通过对过往知识进行筛选和分析，能够快速的把握业务部门的需求，节省双方的沟通成本及时间，加快对业务部门提出需求的反应速度。 
在立项工作量的评估阶段，通过对过往项目相关知识的统计，可以对未来项目的工期及工作量做出较准确的分析和预测。 
在开发阶段，如目标模块已有人在之前研究并实现过，就无需再花时间和精力去进行重复的研究，直接“拿来主义”即可。 
在系统维护阶段，如遇到的问题刚好有人之前给出过完美的解决方案，就不用再费心费力的做各种尝试，节省了解决问题的时间
** 我部知识管理的现状与不足
目前我们部门的知识管理主要体现在开发，运维过程中形成的文档管理上，运维中心的ITIL与ITSM系统带有知识库的功能，但功能较弱，应用程度不高。此外实施知识管理基本是由各系统项目组质量管理人员/运维负责人以兼职的方式进行，而没有专门设立知识管理专员。所以尽管各系统都有进行知识管理工作，但从整个部门来说，知识管理工作还基本处于各自为政的状态，各项目组之间很少在知识共享方面进行互联互通。

具体来说，个人认为我们部门的知识管理存在以下问题：

（1）知识共享程度低 
虽然在每天的开发测试，运维过程中，会产生大量的知识，但绝大多数知识并未经过梳理，仅仅是在版本库中按照文档类型简单的做了存储，所以并没有形成一个完整的知识体系，每个知识都是孤立存在的，他们之间的联系尚没有建立。

甚至于，即使是对统一套系统来说，研发中心，运维中心，管理中心三个中心之间累积的知识也是相对隔离的。

（2）隐型知识易流失 
另外，在隐性知识显性化方面，缺少适当的方式或模式对存在员工头脑中的隐性知识进行挖掘，造成了宝贵的隐性知识流失。如果骨干员工离职，存在他头脑中的经技巧方法等隐性知识也随之带走，会给组织造成非常大的影响

（3）缺乏知识分享热情 
知识管理在客观上会为本职工作之外增加额外的工作量，而且由于缺乏必要的激励机制，所以一些员工会对知识分享缺乏热情。 

（4）知识管理系统不专业
事实上我们部门一直都有尝试使用一些系统进行知识管理，比如研发中心的 Wiki, 运维中心的ITIL知识库。但在这些系统的功能普遍单一，开发人员和运维人员分享和查找知识的体验较差。
而且在整个部门层面缺少一个专业化的知识管理系统，难以将知识进行整合，开发人员，运维人员之间累积的知识无法共享。 

** 提出的建议
构建学习型组织是一个系统型的工程，决不仅仅是上线一套知识管理软件就足够的。我这里尝试从人，机，料，法，环这五个层面出发，提出一些建议。

*** 人：人员
人员知识管理过程中有两个作用，他即使知识管理的实施者，也是隐型知识载体本身。

针对人员方面我的建议是：
1. 建立专家人才库，调查各个员工自己擅长的以及自己感兴趣的知识领域，这样有相同兴趣的人可以结成兴趣小组，遇到问题的人也能方便准确的找到可以提问的人。
2. 向员工普及个人知识管理的理念，这方面有很多不错的书籍可以看，比如《好好学习：个人知识管理精进指南》，《你的知识需要管理》。可以考虑由部门购买借给大家阅读。

*** 机：知识管理系统
知识管理系统是存储，分享知识的载体。它覆盖了知识生产、分享、以及应用的各个环节。 在我看来，一个好的知识管理系统应该能够做到以下几点：

+ 强大的知识录入和抓取功能

  首先，知识的表现形式可以是多样的，比如文本描述，图片，视频和音频等等，因此一个好的知识管理系统也需要能支持录入和存储这些富文本元素，像我们现在ITIL知识库只能录入文本信息，它的知识表现能力就很弱了。

  其次，考虑到信息科技部的知识特点，知识中必然会带有大量的代码片段，因此我们的知识管理系统也需要能够支持多语言的代码高亮功能，这样有助于科技人员理解代码内容。这一点研发中心的Wiki 和运维中心的ITIL知识库目前都不支持。

  再次，为了方便知识录入，知识管理系统需要支持 Markdown 标记语言。Markdown 语言是目前互联网上使用最为广泛的文档发布标记语言，它通过简单的标记语法，可以使普通文本内容具有一定的格式。而对于知识来说，知识的层次结构和内容才是重点，具体的表现格式并不是那么的重要，使用 Markdown 可以让人们在录入知识时将重点放在知识的层次和内容上，而不用怎么关注具体的格式。

  然后，知识管理系统中的知识最好能通过链接关系形成知识地图,知识地图可以显示知识点之间的相互关系，方便用户按相邻知识点查找知识。

  最后，知识管理系统需要提供知识入库接口API，以方便各渠道分享知识。回顾我们的日常工作会发现知识其实无处不在，在聊天工具的沟通记录中，在OA的邮件中，在各类的文档中，在知识入库接口API的情况下，理论上我们可以将这些系统（软件）与知识管理系统进行对接，实现知识的快速导入。另一方面，通过知识入库接口API,我们可以使用爬虫技术从外部著名的问答平台（比如zhihu），博客（比如CSDN,51CTO,OSTechNix,opensource.com等）以及文档中心（比如IBM 文档中心，Redhat 文档中心）抓取知识，完成初步的知识积累。

+ 方便的知识检索功能

  知识的检索能力直接决定了知识管理系统的使用效果，只有足够方便才能吸引员工的使用。

  首先，我们目前大多数的知识其实是以word,excel,pdf 这类文档的形式存在的，因此知识管理系统不仅需要能够对文本进行直接的全文检索，还需要支持word、excel、pdf等格式文档进行全文检索。
  
  其次，光根据关键字进行匹配搜索还不够，因为表达同一种意思有多种方式，因此知识管理系统还需具备正则模糊搜索和同义词搜索功能。这一点Elasticsearch 已经有了现成的插件，实现上不存在特别的难度。

  再次，为了方便使用者对知识进行筛选，搜索结果中需要展现搜索关键字的上下文。

  最后，提供知识订阅RSS功能，方便使用者被动收到感兴趣主题的知识推送。

+ 引入社交化，游戏化，增加知识管理系统的使用黏性
  
  为了增加员工的使用黏性，可以考虑引入社交化和游戏化的理念。比如允许员工对知识进行评分，收藏，点赞，评论；对于知识提供者提供积分奖励，允许通过积分悬赏机制吸引其他员工提供知识，对积分高的员工提供荣誉称号等。
  

+ 能够给出知识质量评估的数据，发布知识评论

  知识的质量有好有差，好的知识需要表扬，差的知识需要淘汰。而判断知识的好坏不能仅通过感觉来进行，而需要有一些关键性的数据指标来表示，比如：

  + 访问量

  + 知识收藏数

  + 点赞数

  + 评分数

  + 引用数

+ 能够与自动运维平台进行联动

  俗话说，光说不练假把式，知识最终还是要落到应用上。通过与自动运维平台联动，可以极大地提高员工的工作效率。

*** 料：知识
我这里尝试从知识的分享途径，知识来源和知识的范围，三个方面提出自己的意见：

**** 知识分享途径多元化
目前我们部门的知识分享途径主要通过文档交接和组织内外部教师培训的方式进行的。
我觉得除此之外还可以通过搭建部门内部的博客，问答平台，维基百科的方式为员工提供更多的知识输出途径，同时通过爬虫技术将这些知识抓取到知识管理平台进行统一存储。
另外，部门内部也可以通过定期印发知识期刊（可以是电子版）的方式进行部门部门知识分享。
**** 知识来源多样化
预期知识的来源前期可能主要来自于外部分享，然后随着知识管理的深入应用，知识来源慢慢偏向于内部分享
+ 内部分享可以包括中间件的文档手册，部门内部的故障回顾报告，员工参加会议交流的学习体会，读书笔记，大家自己发现的一些小工具和小技巧，员工好文推荐也可以通过爬虫技术抓取到知识库。
+ 外部分享可以包括购买一些技术视频，邀请离职人员回来进行知识交流，在互联网上订阅主题周刊通过爬虫技术存入知识库中以及电子书等。
**** 知识范围多种多样
不仅可以包含工作相关的知识，也可以包含生活，个人兴趣方面的知识。其目的就是尽可能多地鼓励大家利用起知识管理平台来。

*** 法：规章制度
建立一种激励机制，这种激励机制可以是物质层面的也可以是精神层面的。比如模仿内部培训机制也对季度知识贡献突出者提供一些奖励或者荣誉称号。

*** 环：文化氛围
企业文化从结构上看，分为精神层、制度层和物质层。精神层是企业领导和员工
共同遵守的企业基本信念、价值标准、职业道德等。它是企业文化的核心和灵魂，是
形成企业文化制度层和物质层的基础和原因。制度层规定了企业成员在共同的生产经
营活动中应该遵守的行为准则和风俗习惯。物质层是企业的表层部分，包括企业标志、
产品形象等，他们折射了企业的经营思想、经营管理哲学、工作作风和审美意识等。
而良好的组织文化可以使信息和知识的交流更开放、更畅通。 
