** 学习型组织与知识管理
学习型组织（Learning Organization），美国学者彼得·圣吉（Peter M. Senge）在《第五项修炼》（The Fifth Discipline）一书中提出此管理观念，即指在面临变动剧烈的外在环境的情况下，组织需要通过培养弥漫于整个组织的学习气氛、充分发挥员工的创造性思维能力而建立起来的一种有机的、高度柔性的、扁平的、符合人性的、能持续发展的组织形态，以维持竞争力。
无独有偶，著名管理学者彼得·杜拉克早在 1965 年也曾预言：“知识将取代土地、劳动、资本与机器设备，成为最重要的生产因素。”

而知识管理（KM, Knowledge Management）是网络新经济时代的新兴管理思潮与方法，它通过对存在于组织内、外部的个人、群体或团队中有价值的知识进行系统地定义、获取、存储、分享、转移和利用等一系列活动，以达到其帮助人们进行知识交流、提高组织生存能力及竞争优势的目的。
知识管理帮助人们对拥有的知识进行反思，帮助和发展支持人们进行知识交流的技术和企业内部结构，并帮助人们获得知识来源，促进他们之间进行知识的交流。

由此可以看出，知识管理本身不是目的，它其实是建设学习型组织的手段而已。
** 实施知识管理的意义

随着知识经济的到来，知识对推动社会的发展起到了越来越重要的作用。尤其是在信息科技部这样一个知识密集型组织中，不仅需要输入大量的计算机专业知识，而且在开发，测试和运维过程中也会产出大量的知识。
实施知识管理，可以使软件开发过程中的显性知识及隐性知识都能得到很好的记录、分享，让知识发挥出它应有的价值。其意义至少包括： 
（1）实现知识的有效积累及研发人员的不断成长
通过将隐性知识显性化，使知识沉淀下来，让科技人员在需要的时候，随时都能方便快速的查找到所需要的知识，从而提高所有人的知识的利用效率，也使新入行的员工在较短的时间内迅速的成长起来。 
（2）让知识发挥应有的价值，促进创新 
通过对经验教训的不断总结，避免同一错误的重复发生；通过对已有知识的挖掘和掌握，加强了知识间的关联，提高科技人员知识理解程度；通过对新技术及先进经验的主动引进，提升了系统的开发效率和运维稳健度，促进技术知识的创新。 
（3）避免重复劳动，提高分析及预测的能力
比如在软件的需求分析阶段，通过对过往知识进行筛选和分析，能够快速的把握业务部门的需求，节省双方的沟通成本及时间，加快对业务部门提出需求的反应速度。 
在立项工作量的评估阶段，通过对过往项目相关知识的统计，可以对未来项目的工期及工作量做出较准确的分析和预测。 
在开发阶段，如目标模块已有人在之前研究并实现过，就无需再花时间和精力去进行重复的研究，直接“拿来主义”即可。 
在系统维护阶段，如遇到的问题刚好有人之前给出过完美的解决方案，就不用再费心费力的做各种尝试，节省了解决问题的时间
** 我部知识管理的现状与不足
目前我们部门的知识管理主要体现在开发，运维过程中形成的文档管理上，运维中心的ITIL系统自带的知识库功能，但功能较弱，应用程度不高。此外实施知识管理基本是由各系统项目组质量管理人员/运维负责人以兼职的方式进行，而没有专门设立知识管理专员。所以尽管各系统都有进行知识管理工作，但从整个部门来说，知识管理工作还基本处于各自为政的状态，各项目组之间很少在知识共享方面进行互联互通。

具体来说，个人认为我们部门的知识管理存在以下问题：

（1）知识共享程度低 
虽然在每天的开发测试，运维过程中，会产生大量的知识，但绝大多数知识并未经过梳理，仅仅是在版本库中按照文档类型简单的做了存储，所以并没有形成一个完整的知识体系，每个知识都是孤立存在的，他们之间的联系尚没有建立。

甚至于，即使是对统一套系统来说，研发中心，运维中心，管理中心三个中心之间累积的知识也是相对隔离的。

（2）隐型知识易流失 
另外，在隐性知识显性化方面，缺少适当的方式或模式对存在员工头脑中的隐性知识进行挖掘，造成了宝贵的隐性知识流失。如果骨干员工离职，存在他头脑中的经技巧方法等隐性知识也随之带走，会给组织造成非常大的影响

（3）缺乏知识分享热情 
知识管理在客观上会为本职工作之外增加额外的工作量，而且由于缺乏必要的激励机制，所以一些员工会对知识分享缺乏热情。 

（4）知识管理系统不专业
事实上我们部门一直都有尝试使用一些系统进行知识管理，比如研发中心的 Wiki, 运维中心的ITIL知识库。但在这些系统的功能普遍单一，开发人员和运维人员分享和查找知识的体验较差。
而且在整个部门层面缺少一个专业化的知识管理系统，难以将知识进行整合，开发人员，运维人员之间累积的知识无法共享。 

** 提出的建议
构建学习型组织是一个系统型的工程，决不仅仅是上线一套知识管理软件就足够的。我这里尝试从人，机，料，法这四个层面出发，提出一些建议。

*** 人：人员
人员知识管理过程中有两个作用，他即使知识管理的实施者，也是隐型知识载体本身。

针对人员方面我的建议是：
1. 建立专家人才库，调查各个员工自己擅长的以及自己感兴趣的知识领域，这样有相同兴趣的人可以结成兴趣小组，遇到问题的人也能方便准确的找到可以提问的人。
2. 向员工普及个人知识管理的理念，这方面有很多不错的书籍可以看，比如《好好学习：个人知识管理精进指南》，《你的知识需要管理》。可以考虑由部门购买借给大家阅读。

*** 机：知识管理系统
知识管理系统是存储，分享知识的载体。它覆盖了知识生产、分享、以及应用的各个环节。 在我看来，一个好的知识管理系统应该能够做到以下几点：

+ 强大的知识录入和抓取功能

  首先，知识的表现形式可以是多样的，比如文本描述，图片，视频和音频等等，因此一个好的知识管理系统也需要能支持录入和存储这些富文本元素，像我们现在ITIL知识库只能录入文本信息，它的知识表现能力就很弱了。

  其次，考虑到信息科技部的知识特点，知识中必然会带有大量的代码片段，因此我们的知识管理系统也需要能够支持多语言的代码高亮功能，这样有助于科技人员理解代码内容。这一点研发中心的Wiki 和运维中心的ITIL知识库目前都不支持。

  再次，为了方便知识录入，知识管理系统需要支持 Markdown 标记语言。Markdown 语言是目前互联网上使用最为广泛的文档发布标记语言，它通过简单的标记语法，可以使普通文本内容具有一定的格式。而对于知识来说，知识的层次结构和内容才是重点，具体的表现格式并不是那么的重要，使用 Markdown 可以让人们在录入知识时将重点放在知识的层次和内容上，而不用怎么关注具体的格式。

  然后，知识管理系统中的知识最好能通过链接关系形成知识地图,知识地图可以显示知识点之间的相互关系，方便用户按相邻知识点查找知识。

  最后，知识管理系统需要提供知识入库接口API，以方便各渠道分享知识。回顾我们的日常工作会发现知识其实无处不在，在聊天工具的沟通记录中，在OA的邮件中，在各类的文档中，在知识入库接口API的情况下，理论上我们可以将这些系统（软件）与知识管理系统进行对接，实现知识的快速导入。另一方面，通过知识入库接口API,我们可以使用爬虫技术从外部著名的问答平台（比如zhihu），博客（比如CSDN,51CTO,OSTechNix,opensource.com等）以及文档中心（比如IBM 文档中心，Redhat 文档中心）抓取知识，完成初步的知识积累。

+ 方便的知识检索功能

  知识的检索能力直接决定了知识管理系统的使用效果，只有足够方便才能吸引员工的使用。

  首先，我们目前大多数的知识其实是以word,excel,pdf 这类文档的形式存在的，因此知识管理系统不仅需要能够对文本进行直接的全文检索，还需要支持word、excel、pdf等格式文档进行全文检索。
  
  其次，光根据关键字进行匹配搜索还不够，因为表达同一种意思有多种方式，因此知识管理系统还需具备正则模糊搜索和同义词搜索功能。这一点Elasticsearch 已经有了现成的插件，实现上不存在特别的难度。

  再次，为了方便使用者对知识进行筛选，搜索结果中需要展现搜索关键字的上下文。

  最后，提供知识订阅RSS功能，方便使用者被动收到感兴趣主题的知识推送。

+ 引入社交化，游戏化，增加知识管理系统的使用黏性
  
  为了增加员工的使用黏性，可以考虑引入社交化和游戏化的理念。比如允许员工对知识进行评分，收藏，点赞，评论；对于知识提供者提供积分奖励，允许通过积分悬赏机制吸引其他员工提供知识，对积分高的员工提供荣誉称号等。
  

+ 能够给出知识质量评估的数据，发布知识评论

  知识的质量有好有差，好的知识需要表扬，差的知识需要淘汰。而判断知识的好坏不能仅通过感觉来进行，而需要有一些关键性的数据指标来表示，比如：

  + 访问量

  + 知识收藏数

  + 点赞数

  + 评分数

  + 引用数

+ 能够与自动运维平台进行联动

  俗话说，光说不练假把式，知识最终还是要落到应用上。通过与自动运维平台联动，可以极大地提高员工的工作效率。

*** 料：知识
我这里尝试从知识的分享途径，知识来源和知识的范围，三个方面提出自己的意见：

**** 知识分享途径多元化
目前我们部门的知识分享途径主要通过文档交接和组织内外部教师培训的方式进行的。
我觉得除此之外还可以通过搭建部门内部的博客，问答平台，维基百科的方式为员工提供更多的知识输出途径，同时通过爬虫技术将这些知识抓取到知识管理平台进行统一存储。
另外，部门内部也可以通过定期印发知识期刊（可以是电子版）的方式进行部门部门知识分享。
**** 知识来源多样化
预期知识的来源前期可能主要来自于外部分享，然后随着知识管理的深入应用，知识来源慢慢偏向于内部分享
+ 内部分享可以包括中间件的文档手册，部门内部的故障回顾报告，员工参加会议交流的学习体会，读书笔记，大家自己发现的一些小工具和小技巧，员工好文推荐也可以通过爬虫技术抓取到知识库。
+ 外部分享可以包括购买一些技术视频，邀请离职人员回来进行知识交流，在互联网上订阅主题周刊通过爬虫技术存入知识库中以及电子书等。
**** 知识范围多种多样
不仅可以包含工作相关的知识，也可以包含生活，个人兴趣方面的知识。其目的就是尽可能多地鼓励大家利用起知识管理平台来。

*** 法：规章制度
比如模仿内部培训机制也对季度知识贡献突出者提供一些奖励或者荣誉称号。
