* 任务一：再见吧！羔羊！
** 你们公司提供什么产品/服务？
   * 提供资金中介服务，包括各种信贷业务
   * 提供资金转移服务，包括各种汇钱途径，各种代收付业务，各种代缴费业务。
   * 保险柜业务，提供对贵重物品的保管服务。
   * 投资咨询，私人银行
** 什么样的客户群会购买你们的产品/服务？
   * 资金中介服务

     面向的客户群，主要是企业。 当然也包括一些需要买房买车的中层阶级，但不是主要的利润来源。

   * 资金转移服务

     面向的客户群包括需要转钱到外地的人群（汇钱），或各种时间紧张，怕麻烦的人群（各种代收代付业务，代缴费业务）

   * 保险柜业务

     主要面向家中有一些及其贵重物品的人群。根据网上搜到的消息：
     #+BEGIN_QUOTE
     保管箱的租户大致有以下几大类：
     一是拆迁户。由于近年房地产的迅猛发展，拆迁户大增，家里的金银首饰、合同、地契没个安全的地方可不行，于是银行保管箱就成了最理想的地方。
     二是股民，据了解，每到周一股市开盘的时候，都有上百人蜂拥而至办理手续，存取一些有价证券、交易账单、重要证件等。
     三是一些上了年纪的老人。为了防止子孙不孝或盗贼，便将养老的贵重物品悄悄藏进了银行。
     还有一些生意人，租用的都是大型号的保管箱，存放一些重要合同、契约、古玩字画等贵重物品。
     #+END_QUOTE
     但不能确定正确性。 我们银行该业务业务量不大。

   * 投资咨询，私人银行

     主要面向富裕/高收入，但没有合适的投资渠道的人群。
** 为什么你们能卖的出去？
   * 资金中介服务
     
     这个问题要分两部分来说，第一部分，为什么选择从银行贷款而不找个人信贷？ 第二个问题，为什么找我们行贷款？
     * 为什么从银行贷款

       第一、 银行作为中介，降低了借贷双方信息获取的成本。
       
       第二、 银行对借贷过程中的风险进行集中控制，降低了风险发生概率和风险控制成本。

       第三、 将大家的资金集合起来，可以增强风险承受能力。

     * 为什么选择我们行进行借贷。

       目前信贷市场还是处于供给小于需求的阶段，也就是卖方市场。 基本上只要你能提供贷款就有人要。

       至于为什么信贷市场处于供过于秋的阶段，分析可能是因为中国现在还处于经济上升期，且中国目前的GDP主要靠投资来驱动，资金需求真的不是一般的大。

   * 资金转移服务

     这方面我们银行的主要优势在于：
     * 网点极多

       这一点对于那些教育程度不高和中老年人群来说具有相当的吸引力。因为他们不会/不相信/没条件使用网上银行。

       值得一提的是，手机和手机银行的普及会大大降低了使用网上银行的壁垒，但目前的影响还不够明显。

       另外，网点多无形中也起到了广而告知的作用。

     * 服务相对周到（相对四大行来说的）

       不周到不行啊，地方小银行，不这样怎么跟四大行拼啊。

     * 立足本市，政府支持

       我们行是本土两大银行之一，政府为了扶持本土产业会有一些支持，但不多。

   * 保险柜业务

	 可能是因为价格够便宜吧...

   * 投资咨询,个人银行

	 感觉忽悠的成分比较多...
