#+TITLE: 贪婪的陷阱
#+AUTHOR: DarkSun
#+OPTIONS: ^{}

* 保险的诡计

** 理解保障型保险产品是如何运作的
   * 什么叫保障型保险?
     网上对保障型保险的定义说法不一,综合来看我理解的保障型保险是以转嫁的是被保险人的生存或者死亡的风险的保险,它具有以下几个特点:
	 1. 被保险人收到了伤害或者死亡
	 2. 固定的保单利率,不会随市场利率的上升而提高,也不会随市场利率的下降而降低,投保人获得的保险保障是一个确定不变的给付金额
	 3. 功能单一,相对来说保障高，费用低.
   * 保障型保险产品是如何运作的?
	 首选,选取一部分人群作为产品的目标客户.
	 然后,由精算师算出保费,保额之间的关系
	 通过计算最低盈利客户数,在确定有利可图之后,就开始推销自己的产品.
	 收到的保费部分留存用于支付保费,部分需要用来支付企业经营成本,剩下的可以用于投资资本市场.
	 但由于保险的特殊性,投资需要优先保障安全性和流动性,其次才能考虑收益性. 因此我国法律规定保险资金运用限于(1)银行存储(2)买卖债券、股票、证券投资基金份额等有价证券(3)投资不动产(4)国务院规定的其他资金运用形式. 向期货期权这种极高风险的产品那是不能涉入的.
** 理财保险为什么是垃圾,给出你的理由
   保险决定了它的投资渠道需要保障资金够安全且流动性够强. 而理财的特点又要求它具有较高的收益率. 试问又要求风险低,又要求流动性强还要求高收益率,这种好的投资渠道哪找呢?
** 股票,基金,投资连结保险,它们三者有什么关联吗?
   1. 都需要投资资本市场
   2. 由客户自负盈亏
   3. 都是舶来品,并且在中国这片土地上开始变异.
* 破解贪婪的陷阱
  1. 为什么散户不退出?
	 人心普遍存在过度自信和盲目乐观的心理. 散户们知道大多数人会亏钱,但对自己的操作充满自信,认为自己能够躲过,因此没有退出.
  2. 为什么很少人止损?
	 因为人们普遍损失厌恶. 所谓损失厌恶是指人们面对同样数量的收益和损失时,认为损失更加令他们难以忍受. 同量的损失带来的负效用为同量收益的正效用的2.5倍. 

	 由于损失是极度痛苦的,因此人们普遍守者渺茫的希望而不愿割肉
  3. 为什么喜欢理财型保险?
	 就我自己来说没有这个感觉,推测也是跟盲目乐观的心理有关. 因此高估了没事时带来的收益,而低估了有事时带来的损失
  4. 为什么信赖银行
	 因为光晕效应. 人们对他人(事物)的认知判断首先根据整体印象,然后再从这个判断推断出认知对象的其他品种的现象. 由于与银行普遍接触的业务为存取款,汇钱这类风险极低的业务,再加上普遍的宣传o人们一种银行是稳健的总体印象. 由这种印象推而广之会认为银行提供的其他服务也是几乎不存在风险的.
