#+TITLE: lua
#+AUTHOR: DarkSun
#+EMAIL: lujun9972@gmail.com
#+OPTIONS: H3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* NOTE
  1. ..为字符串连接运算符（可用于字符串与数字之间的连接）
  2. ~=为不等号
  3. *默认数组下标从1开始，不推荐数组下标从0开始，否则很多标准库无法使用* ，这点很不一样
  4. io.write()不输出换行，而print自动输出换行，print（）输出一个换行符
  5. lua中的table，类似于javascript中的Array(数组，同时也是Object，可以当Map用)
     #+BEGIN_SRC lua
     address={1,2,3}
     address.Street="Wyman Street"
     address.Contry="USA"
     print(address.Street,address["Contry"]
     #+END_SRC
  6. if语句
     * if 条件 then 语句 end
     * if 条件 then 语句 else 语句 end
     * if 条件 then 语句 elseif 条件 then 语句 else 语句 end
  7. util语句
     * repeat 语句 until 条件
  8. while语句
     * while 条件 do 语句 end
  9. for语句
     * for from语句,to值,by值
       #+BEGIN_SRC lua
-- Count from 1 to 4 by 1.
for a=1,4 do io.write(a) end

print()

-- Count from 1 to 6 by 3.
for a=1,6,3 do io.write(a) end
       #+END_SRC
     * for 变量 in 列表
       #+BEGIN_SRC lua
       for key,value in pairs({1,2,3,4}) do print(key, value) end
       -------- Output ------
  
       1       1
       2       2
       3       3
       4       4
       #+END_SRC
  10. 定义函数
      * 可以返回多个返回值
      function 函数名(parm1,parm2,parm3...)
      语句
      return value1,value2,value3...
      end
      #+BEGIN_SRC lua
 function myFirstLuaFunctionWithMultipleReturnValues(a,b,c)
     return a,b,c,"My first lua function with multiple return values", 1, true
 end

 a,b,c,d,e,f = myFirstLuaFunctionWithMultipleReturnValues(1,2,"three")
 print(a,b,c,d,e,f)


 -------- Output ------

 1       2       three   My first lua function with multiple return values
 1       true
      #+END_SRC
  11. 与javascript类似，所有的变量默认为全局变量.
      lua中的local与javascript中的var作用一样，使得变量成为局部变量
      #+BEGIN_SRC lua
-- All variables are global in scope by default.

b="global"

-- To make local variables you must put the keyword 'local' in front.
function myfunc()
    local b=" local variable"
    a="global variable"
    print(a,b)
end

myfunc()
print(a,b)


-------- Output ------

global variable  local variable
global variable global

      #+END_SRC
  12. 使用requre语句导入库
      #+BEGIN_SRC lua
      require("iuplua")
      #+END_SRC
* 术语
  1. Chunk:
     Chunk 是一系列语句，Lua 执行的每一块语句，比如一个文件或者交互模式下的每一行都是一个 Chunk。
  2. Upvalue:
     一个函数所使用的定义在它的函数体之外的局部变量（external local variable）称为这个函数的upvalue。
* 编译器lua
  1. 键入文件结束符可以退出交互模式，活着调用os.exit()函数也可以退出
  2. Lua 通常把每一个行当作一个 Chunk，但如果 Lua 一行不是一个完整的 Chunk时，他会等待继续输入直到得到一个完整的 Chunk.在 Lua 等待续行时，显示不同的提示符（一般是>>）.
** 参数说明
   * -l       让lua执行一系列文件
   * -i       要求 Lua 运行指定Chunk 后进入交互模式.
   * -e       直接将命令传入Lua
   * 
* 运算符
  1. 关系运算符:< > <= >= == ~=
     * lua中不等号用~=表示
     * 如果两个值类型不同，Lua认为两者不同；nil只跟自己相等
     * lua通过引用比较tables、userdata、functions
     * 为了避免不一致的结果，混合比较数字和字符串，lua会报错，例如2<'15'
  2. 逻辑运算符:and or not
     * 逻辑运算符认为false和nil是假，其他为真，0和""也为真
     * and 和 or的运算结果不是true和false，而是操作数的结果，这一点跟javascript类似
     * and的优先级比or高
     * C语言的a?b:c在lua中可以用(a and b) or c代替
  3. 连接运算符: ..
     * 如果操作数为数字，则自动转换成字符串
  4. 表构造符:{}
     * 初始化表a={v1,v2...}
     * 初始化表a={k1=v1,k2=v2...}
     * 通过a.x=nil来删除表中的项目
     * 每次调用{}，Lua都会创建一个新的table
       #+BEGIN_SRC Lua
-- 可以使用table构造一个list
list=nil
for line in io.lines() do
    list={next=list,value=line}
end
       #+END_SRC
     * 在同一个构造中，可以混用列表和record风格进行初始化
       #+BEGIN_SRC lua
polyline={k=v,k1,{a=b,c}}
       #+END_SRC
     * 上面的初始化方式有几个限制，你不能使用负索引，也不能使用类似+=*/这样的索引。
       更一般的初始化方式是tb={["+"]="add",["-"="SUB",[ 1 ]="one",[ 2 ]="two"]}
     * 构造函数中域分隔符都好(,)可以用分号(;)代替，通常我们使用分号来分割不同类型的表元素
       #+BEGIN_SRC lua
{x=10,y=45;"one","two"}
       #+END_SRC
* 变量
  lua中的变量如果没有特殊说明，全是全局变量，那怕是语句块或是函数里。变量前加local关键字的是局部变量。这一点跟javascript类似
** 变量类型
   * number
	 Lua的数字只有double型，64bit
   * string
     总是以\0结尾，但可以包含任意字符，包括\0
   * boolean
	 只有nil和false为假，其他都为真
   * function
     对lua来说，函数是一种基本数据类型――代表一种可执行对象，可以有自己的状态。
     可以用setfenv()来对函数设置函数环境
   * table
     任何类型的变量，除了nil，都可以做为表项的键。从简单的数值、字符串到复杂的函数、表等等都可以；同样，任何类型的变量，除了nil，都可以作为表项的值。给一个表项的值赋nil意味着从表中删除这一项.
	 #+begin_quote
: 所谓Table其实就是一个Key Value的数据结构，它很像Javascript中的Object，或
: 是PHP中的数组，在别的语言里叫Dict或Map，Table长成这个样子：
: 
: haoel = {name="ChenHao", age=37, handsome=True}
: 
: 下面是table的CRUD操作：
: 
: haoel.website="http://coolshell.cn/"
: local age = haoel.age
: haoel.handsome = false
: haoel.name=nil
: 
: 上面看上去像C/C++中的结构体，但是name,age, handsome, website都是key。你还
: 可以像下面这样写义Table：
: 
: t = {[20]=100, ['name']="ChenHao", [3.14]="PI"} 
: 
: 这样就更像Key Value了。于是你可以这样访问：t[20]，t["name"], t[3.14]。
: 
	 #+end_quote
	 
	 在lua中，数字其实也是一种特殊table。
	 #+begin_quote
: arr = {10,20,30,40,50}
: 
: 这样看上去就像数组了。但其实其等价于：
: 
: arr = {[1]=10, [2]=20, [3]=30, [4]=40, [5]=50}
: 
: 所以，你也可以定义成不同的类型的数组，比如：
: 
: arr = {"string", 100, "haoel", function() print("coolshell.cn") end}
: 
: 注：其中的函数可以这样调用：arr[4]()。
: 我们可以看到Lua的下标不是从0开始的，是从1开始的。
: 
: for i=1, #arr do
: print(arr[i])
: end
: 
: 注：上面的程序中：#arr的意思就是arr的长度。
:                              	 
	 #+end_quote
   * userdata
     用户（非脚本用户）定义的C数据结构。脚本用户只能使用它，不能定义。
   * thread
     Lua协作线程，与一般操作系统的抢占式线程不一样。
     yield的传入参数是另一个进程resume的返回值
     resume的传入参数是另一个进程yield的返回值
   * nil
** 特殊变量
   * 全局变量arg存放Lua的命令行参数:
     脚本名索引为0，脚本参数从1开始增加，脚本前面的参数从-1开始减少
     #+BEGIN_SRC lua
       prompt> lua -e "sin=math.sin" script a b 
       arg 表如下： 
       arg[-3] = "lua" 
       arg[-2] = "-e" 
       arg[-1] = "sin=math.sin" 
       arg[0] = "script" 
       arg[1] = "a" 
       arg[2] = "b" 
     #+END_SRC
   * LUA_INIT:
     Lua 会查找环境变量 LUA_INIT 的值，如果变量存在并且值为@filename，Lua 将加载指定文件。如果变量存在但不是以@开头，Lua假定 filename 为 Lua 代码文件并且运行他。
   * _G
	 lua使用一个名为_G的Table来保存全局变量。
* 语法
** 注释
   * 单行注释
     #+begin_src lua
       -- 单行注释
     #+end_src
   * 多行注释
	 #+begin_src lua
             --[[
                line1
                line2
                多行注释
             --']]
	 #+end_src
** 赋值
   1. Lua可以对多个变量同时赋值，这点类似Python
   2. 若变量个数与值个数不同则
      * 变量个数>值得个数,变量个数补足nil
      * 变量个数<值得个数,多余的值会被忽略
   3. 局部变量与代码块
      * 与javascript类似，所有的变量默认为全局变量.
      * lua中的local与javascript中的var作用一样，使得变量成为局部变量
        #+BEGIN_SRC lua
-- All variables are global in scope by default.

b="global"

-- To make local variables you must put the keyword 'local' in front.
function myfunc()
    local b=" local variable"
    a="global variable"
    print(a,b)
end

myfunc()
print(a,b)


-------- Output ------

global variable  local variable
global variable global

       #+END_SRC
      * 使用do...end定义一个block
** 控制结构语句
   1. if语句
      * if 条件 then 语句 end
      * if 条件 then 语句 else 语句 end
      * if 条件 then 语句 elseif 条件 then 语句 else 语句 end
		#+begin_src lua
          if age == 40 and sex =="Male" then
             print("男人四十一枝花")
          elseif age > 60 and sex ~="Female" then
             print("old man without country!")
          elseif age < 20 then
             io.write("too young, too naive!\n")
          else
             local age = io.read()
             print("Your age is "..age)
          end
          
          -- 上面的语句不但展示了if-else语句，也展示了
          -- 1）“～=”是不等于，而不是!=
          -- 2）io库的分别从stdin和stdout读写的read和write函数
          -- 3）字符串的拼接操作符“..”
          
          -- 另外，条件表达式中的与或非为分是：and, or, not关键字。
		#+end_src
   2. until语句
      * repeat 语句 until 条件
		#+begin_src lua
          sum = 2
          repeat
             sum = sum ^ 2 --幂操作
             print(sum)
          until sum >1000
		#+end_src
   3. while语句
      * while 条件 do 语句 end
		#+begin_src lua
          sum = 0
          num = 1
          while num <= 100 do
             sum = sum + num
             num = num + 1
          end
          print("sum =",sum)
          
		#+end_src
   4. for语句
      * for var=from值,to值,by值
        #+BEGIN_SRC lua
        -- Count from 1 to 4 by 1.
        for a=1,4 do io.write(a) end

        print()

        -- Count from 1 to 6 by 3.
        for a=1,6,3 do io.write(a) end
        #+END_SRC
	需要注意的是:from、to、by值仅会在循环开始前执行一次；控制变量var是局部变量自动被声明,并且只在循环内有效. 因此如果需要保留控制变量的值，需要在循环中将其保存。
      * for 变量 in 列表
        #+BEGIN_SRC lua
        for key,value in pairs({1,2,3,4}) do print(key, value) end
        -------- Output ------
       
        1       1
        2       2
        3       3
        4       4
        #+END_SRC
	需要注意的是:控制变量var是局部变量自动被声明,并且只在循环内有效. 因此如果需要保留控制变量的值，需要在循环中将其保存。
   5. Lua语法要求break和return职能出现在block的结尾一句，所以若是为了调试或其他需要在block中间使用return或break，需要显式使用do...end来实现
** 函数    
   Lua的函数的语法与Javascript的很像，特性与lisp很像。
*** 定义函数
	* 函数可以返回多个返回值
	  function 函数名(parm1,parm2,parm3...)
	  语句
	  return value1,value2,value3...
	  end
	  #+BEGIN_SRC lua
	   	function myFirstLuaFunctionWithMultipleReturnValues(a,b,c)
		   	return a,b,c,"My first lua function with multiple return values", 1, true
	   	end

	   	a,b,c,d,e,f = myFirstLuaFunctionWithMultipleReturnValues(1,2,"three")
	   	print(a,b,c,d,e,f)


	   	-------- Output ------

	   	1       2       three   My first lua function with multiple return values
	   	1       true
	  #+END_SRC
	* Lua的函数可以接受可变数据的参数，类似C语言在函数参数列表中使用三点...表示函数有可变的参数。Lua将函数放在一个叫arg特殊变量内，这个变量是一个表表。除了参数以外，arg表还有一个域n表示参数的个数。
   	  #+BEGIN_SRC lua
        printResult=""
        function print(...)
            for i,v in ipairs(arg) do
                printResult=printResult..tostring(v).."\t"
            end
            printResult=printResult.."\n"
        end
   	  #+END_SRC
	* 命名参数：Lua可以通过将所有的参数放在一个表内，把表作为函数的唯一参数来实现类似命名参数的功能。
   	  #+BEGIN_SRC lua
        function rename(args)
            return os.rename(args.old,args.new)
        end
        rename{old="old.lua",new="new.lua"}     --当函数参数仅一个，且为表或字符串时，可以省略()
   	  #+END_SRC
	* 定义匿名函数
   	  function (x)
   	  语句
   	  end
	  #+begin_src lua
        function foo(x) return x^2 end
        -- 等价于
        foo = function(x) return x^2 end
	  #+end_src
	* Lua将函数看成一个普通那个变量，也支持闭包
   	  #+BEGIN_SRC lua
        function newCounter() 
           local i = 0 
           return function()     -- anonymous function 
              i = i + 1 
              return i 
           end 
        end 
        c1 = newCounter() 
        print(c1())  --> 1  
        print(c1())  --> 2
   	  #+END_SRC
*** 调用函数
      * 当函数只有一个参数并且这个参数是字符串或者表构造时，()是可选的:
	#+BEGIN_SRC lua
	print "abc"       -- print("abc")
	#+END_SRC
      * Lua也提供面向对象方式调用函数的语法： obj:function().
	*这里object与function之间用:分隔开，而模块与方法之间用.分隔开！！*
	#+BEGIN_SRC lua
	o:foo(x)         --> o.foo(o,x)
	#+END_SRC
      * Lua函数的参数与javascript类似，，多余的部分被省略，缺少部分用nil补足
      * 如果没有返回，则值为nil
      * 函数调用作为函数参数或是表的构造函数中,或是在return语句之后时，与多值赋值时相同
	#+BEGIN_SRC lua
	print(f())          -->print(a,b,c)
	a={f()}             -->a={a,b,c}
	return f()          -->return a,b,c
	#+END_SRC
      * 可以使用圆括号强制使调用返回一个值
	print((f()))       -->print(a)
      * 可以用unpack函数来讲一个数组转换成多个元素
 
* 高级主题
** 面向对象编程
   与javascript类似，lua是基于对象的，其可以用setmetatable()设置一个元表（metatable）,这个元表类似于javascript的prototype
*** 简单的对象实现方式
    * 对象工厂模式
      如前面代码的create函数用表来表示对象,把对象的数据和方法都放在一张表内，虽然没有隐藏私有成员，但对于简单脚本来说完全可以接受。
    * 成员方法的定义
      function obj:method(a1, a2, ...) … end 等价于
      function obj.method(self, a1, a2, ...) … end 等价于
      obj.method = function (self, a1, a2, ...) … end
    * 成员方法的调用
      obj:method(a1, a2, …) 等价于
      obj.method(obj, a1, a2, ...)
    #+BEGIN_SRC lua
    function create(name, id)
       local obj = { name = name, id = id }
       function obj:SetName(name)
           self.name = name
       end
       function obj:GetName()
           return self.name
       end
       function obj:SetId(id)
           self.id = id
       end
       function obj:GetId()
           return self.id
       end
       return obj
    end
    #+END_SRC
*** 简单继承
    1. 先调用基类的工厂函数产生一个基类的对象
    2. 在这个基类的对象的基础上增加子类的属性和方法
    3. 返回这个对象
    #+BEGIN_SRC lua
    function createBase()
        local obj={attr="base"}
	function obj:setName(name)
	    self.name=name
	end
    end
    
    function createSub()
        local obj=createBase()
	obj.attr="Sub"
	function obj:setId(id)
	    self.id=id
	end
    end
    #+END_SRC
*** 实现对外隐藏属性
    *　实现方式 
    　 把需要隐藏的成员放在一张表里，把该表作为成员函数的upvalue。
    * 局限性 
      基于对象的实现不涉及继承及多态。但另一方面，脚本编程是否需要继承和多态要视情况而定。
*** 使用MetaTable实现重载运算符
	#+begin_quote
: 
: MetaTable 和 MetaMethod
: 
: MetaTable和MetaMethod是Lua中的重要的语法，MetaTable主要是用来做一些类似于C++重载操作符式的功能。
: 
: 比如，我们有两个分数：
: 
: fraction_a = {numerator=2, denominator=3}
: fraction_b = {numerator=4, denominator=7}
: 
: 我们想实现分数间的相加：2/3 + 4/7，我们如果要执行： fraction_a + fraction_b，会报错的。
: 
: 所以，我们可以动用MetaTable，如下所示：
: 
: fraction_op={}
: function fraction_op.__add(f1, f2)
: ret = {}
: ret.numerator = f1.numerator * f2.denominator + f2.numerator * f1.denominator
: ret.denominator = f1.denominator * f2.denominator
: return ret
: end
: 
: 为之前定义的两个table设置MetaTable：（其中的setmetatble是库函数）
: 
: setmetatable(fraction_a, fraction_op)
: setmetatable(fraction_b, fraction_op)
: 
: 于是你就可以这样干了：（调用的是fraction_op.__add()函数）
: 
: fraction_s = fraction_a + fraction_b
: 
: 至于__add这是MetaMethod，这是Lua内建约定的，其它的还有如下的MetaMethod：
: 
: __add(a, b)                     对应表达式 a + b
: __sub(a, b)                     对应表达式 a - b
: __mul(a, b)                     对应表达式 a * b
: __div(a, b)                     对应表达式 a / b
: __mod(a, b)                     对应表达式 a % b
: __pow(a, b)                     对应表达式 a ^ b
: __unm(a)                        对应表达式 -a
: __concat(a, b)                  对应表达式 a .. b
: __len(a)                        对应表达式 #a
: __eq(a, b)                      对应表达式 a == b
: __lt(a, b)                      对应表达式 a < b
: __le(a, b)                      对应表达式 a <= b
: __index(a, b)                   对应表达式 a.b
: __newindex(a, b, c)             对应表达式 a.b = c
: __call(a, ...)                  对应表达式 a(...)	
	#+end_quote
*** 使用元表实现继承
    * 实现方法
      将基类设置为子类的元表、并将子类的元表（即基类）设置为自身（也是基类，也就是代码self.__index=self）
      #+BEGIN_SRC lua
      Robot = { name = "Sam", id = 001 }
      function Robot:New(extension)
        local t = setmetatable(extension or { }, self)
        self.__index = self
        return t
      end
      FootballRobot = Robot:New( {position = "right back"})
      fr=FootballRobot:New()
      #+END_SRC
    * prototype模式
      一个对象既是一个普通的对象，同时也可以作为创建其他对象的原型的对象（即类对象，class object）；
	  动态的改变原型对象的属性就可以动态的影响所有基于此原型的对象；
	  另外，基于一个原型被创建出来的对象可以重载任何属于这个原型对象的方法、属性而不影响原型对象；
	  同时，基于原型被创建出来的对象还可以作为原型来创建其他对象。    
	  #+begin_quote
: 考虑到上面的index方法，该方法主要是重载了find key的操作.    
: 如果我们有两个对象a和b，我们想让b作为a的prototype只需要：
: setmetatable(a, {__index = b})
: 
	  #+end_quote
** 包
   * 定义
     包是一种组织代码的方式。
   * 实现方式
     一般在一个Lua文件内以module函数开始定义一个包。module同时定义了一个新的包的函数环境，以使在此包中定义的全局变量都在这个环境中，而非使用包的函数的环境中。理解这一点非常关键。以前面的代码为例， “module(..., package.seeall)”的意思是定义一个包，包的名字与定义包的文件的名字相同（除去文件名后缀，在前面的代码中，就是“mypack”），并且在包的函数环境里可以访问使用包的函数环境（比如，包的实现使用了print，这个变量没有在包里定义，而是定义在使用包的外部环境中）。
   * 使用方式
     一般用require函数来导入一个包，要导入的包必须被置于包路径（package path）上。包路径可以通过package.path或者环境变量来设定。一般来说，当前工作路径总是在包路径中。
	 #+begin_quote
: 我们可以直接使用require(“model_name”)来载入别的lua文件，文件的后缀是.lua。载入的时候就直接执行那个文件了。比如：
: 
: 我们有一个hello.lua的文件：
: 
: print("Hello, World!")
: 
: 如果我们：require(“hello”)，那么就直接输出Hello, World！了。
: 
: 注意：
: 1）require函数，载入同样的lua文件时，只有第一次的时候会去执行，后面的相同的都不执行了。
: 2）如果你要让每一次文件都会执行的话，你可以使用dofile(“hello”)函数
: 3）如果你要玩载入后不执行，等你需要的时候执行时，你可以使用 loadfile()函数，如下所示：
: 
: local hello = loadfile("hello")
: ... ...
: ... ...
: hello()
: 
: loadfile(“hello”)后，文件并不执行，我们把文件赋给一个变量hello，当hello()时，才真的执行。
: 
: 当然，更为标准的玩法如下所示。
: 
: 假设我们有一个文件叫mymod.lua，内容如下：
: 
: local HaosModel = {}
: local function getname()
: return "Hao Chen"
: end
: function HaosModel.Greeting()
: print("Hello, My name is "..getname())
: end
: return HaosModel
: 
: 于是我们可以这样使用：
: 
: local hao_model = require("mymod")
: hao_model.Greeting()
: 
: 其实，require干的事就如下：（所以你知道为什么我们的模块文件要写成那样了）
: 
: local hao_model = (function ()
: --mymod.lua文件的内容--
: end)()     
	 #+end_quote
** 协作线程
   * 创建协作线程
     通过coroutine.create可以创建一个协作线程，该函数接收一个函数类型的参数作为线程的执行体，返回一个线程对象。
   * 启动线程
     通过coroutine.resume可以启动一个线程或者继续一个挂起的线程。该函数接收一个线程对象以及其他需要传递给该线程的参数。线程可以通过线程函数的参数或者coroutine.yield调用的返回值来获取这些参数。当线程初次执行时，resume传递的参数通过线程函数的参数传递给线程，线程从线程函数开始执行；当线程由挂起转为执行时，resume传递的参数以yield调用返回值的形式传递给线程，线程从yield调用后继续执行。
   * 线程放弃调度
     线程调用coroutine.yield暂停自己的执行，并把执行权返回给启动/继续它的线程；线程还可利用yield返回一些值给后者，这些值以resume调用的返回值的形式返回
   * 另一种迭代方式
     协作线程可以作为for循环迭代器的另一种实现方式。虽然对于简单的数组遍历来说，没有必要这么做，但是考虑一下，如果需要遍历的数据集合是一个复杂数据结构，比如一棵树，那么协作线程在简化实现上就大有用武之地了。
     #+BEGIN_SRC lua
     function enum(array)
       return coroutine.wrap(function()
        local len = #array
        for i = 1, len do
            coroutine.yield(array[i])
        end
      end)
     end
     function foreach(array, action)
       for element in enum(array) do
         action(element)
       end
     end
     foreach({1, 2, 3}, print)
     #+END_SRC
* 标准库
** math
*** 三角函数
所有三角函数都使用弧度单位,但可以用math.deg和math.rad来转换角度和弧度

+ sin

+ cos

+ tan

+ asin

+ acos

*** 指数和对数函数

+ exp

+ log

+ log10

*** 取整函数

+ floor

+ ceil

*** 随机数函数

+ random() :: 生成[0,1) 区间均匀分布的伪随机数

+ random(n) :: 返回一个区间在[1,n]内的伪随机整数

+ random(m,n) :: 返回区间[m,n]内的伪随机整数 

+ randomseed(数字) :: 设置随机种子

*** 常量

+ pi

+ huge :: lua可以表示的最大数字

*** 其他

+ max

+ min

** table库
table库中的函数将table作为 *数组* 来操作.
*** 插入和删除

+ insert($table,$element) :: 将$element插入到$table的末尾
+ insert($table,$position,$element) :: 将$element插入到$table的指定位置
+ remove($table) :: 删除$table中的最后一个元素
+ remove($table,$position) :: 删除$table在$position位置的元素
*** 排序

+ sort($table) :: 使用小于操作对$table进行排序
+ sort($table,$compare_function) :: 按指定的比较函数来对$table进行排序, 如果希望第一个参参数在第二个参数前,则比较函数应该返回true
*** 连接

+ concat($string_table) :: 返回字符串数组中字符串连接后的结果
+ concat($string_table,$sep) :: 返回字符串数组中字符串连接后的结果,$sep为字符串之间的分隔符
+ concat($string_table,$sep,$start,$end) :: 返回字符串数组中字符串连接后的结果,$sep为字符串之间的分隔符,$start为第一个要连接的字符串索引,$end为最后一个要连接的字符串索引
** string库
在Lua5.1中,字符串库中的函数还被导出为string类型的方法,因此 =string.upper(s)= 和 =s:upper()= 是一样的效果.

另外需要注意的是, *字符串的索引是从1开始,且负数的索引会从字符串的尾部开始计数,当函数中的两个参数表示返回时,通常包含了$end位置的字符*
*** 基础字符串函数

+ len($str) :: 字符串$str的长度
+ rep($s,$n) :: 返回字符串$s重复$n次的结果
+ lower($s) :: 返回字符串$s的小写形式
+ upper($s) :: 返回字符串$s的大写形式
+ sub($s,$i) :: 从字符串$s中抽取前$i长度的前缀, *索引是从1开始,负数的索引会从字符串的尾部开始计数*
+ sub($s,$i,$j) :: 从字符串$s中抽取从$i到$j个字符(包括$j位置的字符), *索引是从1开始,负数的索引会从字符串的尾部开始计数*
+ char($num1,$num2...$numN) :: 将数字$num1-$numN转换成字符串
+ byte($str) :: 返回$str中第一个字符的内部数值表示.
+ byte($str,$position) :: 返回$str中$position位置字符的内部数值表示.
+ byte($str,$start,$nd) :: 返回$str中从$start到$end之间字符的内部数值表示.
+ format($fmt,...) :: 格式化字符串,规则与C语言的printf一样
*** 模式匹配函数
+ find($str,$pattern) :: 在$str中搜索模式$pattern,返回匹配道德起始索引和结尾索引. 无匹配则返回nil
+ match($str,$pattern) :: 与find类似,但是返回目标字符串中与模式匹配的那部分字串.
+ gsub($str,$pattern,$replace) :: 将$str中所有匹配$pattern的地方替换为$replace,返回替换后的字符串,及实际替换的次数.
+ gsub($str,$pattern,$replace,$times) :: 将$str中匹配$pattern的地方替换为$replace,但最多匹配$times次,返回替换后的字符串,及实际替换的次数.
+ gmatch($str,$pattern) :: 返回一个函数,这个函数可以便利$str中匹配$pattern的地方,因此可以当成迭代器来使用.
*** 模式说明
*lua中使用'%'作为转义字符!!*

+ . :: 所有字符
+ %a :: 字母
+ %c :: 控制字符
+ %d :: 数字
+ %l :: 小写字母
+ %p :: 标点符号
+ %s :: 空白字符
+ %u :: 大写字母
+ %w :: 字母和数字字符
+ %x :: 十六进制数字
+ %z :: 内部表示为0的字符

*lua中的修饰符只能应用于一个字符分类,无法对一组分类进行修饰!*

+ + :: 重复1次或多次
+ * :: 重复0次或多次
+ - :: 也是重复0次或多次, *但使用非贪婪算法*
+ ? :: 出现0次或1次
** IO库
IO库为文件操作提供了两种不同的模型: 简单模型与完整模型. 其中

+ 简单模型假设有一个当前输入文件和一个当前输出文件,所有IO操作均作用于这些文件
+ 完整模型则使用显式的文件句柄. 采用的是面向对象的风格,所有操作定义为文件句柄上的方法
*** 简单IO模型
IO库默认将当前输入文件初始化为stdin,将输出文件初始化为stdout.

+ read() :: 从当前输入文件读取一行
+ read("*all") :: 读取整个文件
+ read("*line") :: 读取下一行,但不包括换行符,到达文件末尾会返回nil
+ read("*number") :: 读取一个数字,若当前位置无法读取到数字则返回nil
+ read($N) :: 读取N个字符的字符串
+ read(选项1,选项2...选项N) :: read可以指定多个选项,函数会根据每个选项参数返回相应的内容.例如 =read("*number","*number","*number")= 会读取3个数字
+ read(0) :: 用于检查是否达到了文件末尾,若还有数据可读取会返回空字符串,否则返回nil

+ write($str1...$strN) :: 将字符串或 *数值* 写入当前输出文件
+ input(filename) :: 以只读模式打开指定文件,并将其设置为当前输入文件
+ output(filename) :: 打开指定文件,并将其设置为当前输出文件
+ lines() :: 返回所有行的迭代器
*** 完整IO模式
完整模型是基于文件句柄的,文件句柄类似于C语言中的FILE*,表示一个具有当前位置的打开文件.

+ open($filename,$mode) :: 类似C语言中的fopen函数. $filename为要打开的文件名称,$mode为模式字符串. 若发生错误,则返回nil,一个错误消息及一个错误代码.
+ $f:read(可选参数) :: 与简单IO模型中的read类似,但$f为open返回的句柄.
+ $f:write(可选参数) :: 与简单IO模型中的write类似,但$f为open返回的句柄.
+ input($handle) :: 设置当前输入文件的句柄.
+ stdin :: 预定义的标准输入文件句柄
+ stdout :: 预定义的标准输出文件句柄
+ stderr :: 预定义的标准错误文件句柄
*** 其他文件操作
+ tmpfile() :: 返回一个临时文件的句柄,这个句柄以读/写方式打开. 会在程序结束时自动删除
+ flush() :: 将当前输出文件缓冲中的数据写入文件
+ $f:flush() :: 将$f文件缓冲中的数据写入文件
+ $f:seek($whence,$offset) :: 获取和设置$f的当前位置.其中$whence的有效值包括 "set","cur","end". 它总是返回文件的当前位置.
** os库
*** 文件操作
+ rename() :: 文件改名
+ remove() :: 删除文件
*** 日期和时间
+ time() :: 返回表示当前时间的数字
+ time($table) :: 返回表示$table中描述时间的数字. 这是$table需要有以下有效元素:
  - year :: 必填,完整的年份
  - month :: 必填,01-12
  - day :: 必填,01-31
  - hour :: 可选,00-23,默认为12
  - min :: 可选,00-59,默认为0
  - sec :: 可选,00-59,默认为0
  - isdst :: 可选,布尔值,true表示夏时令
+ date("*t") :: date函数是time函数的反函数,以table返回当前日期的表现形式.
+ date("*t",$secs) :: date函数是time函数的反函数,按照table的格式返回$secs表示时间的表现形式.
+ date($fmt) :: date函数是time函数的反函数,按照$fmt指定的格式返回当前日期的表现形式.
+ date($fmt,$secs) :: date函数是time函数的反函数,按照$fmt指定的格式返回$secs表示时间的表现形式. 其中标记的意义如下:
  + %a :: 星期几的简写
  + %A :: 星期几的全称
  + %b :: 月份的简写
  + %B :: 月份的全称
  + %c :: 日期和时间,例如Fri Nov 11 14:56:44 2016,可能随着区域和系统而变化
  + %d :: 一个月中的第几天
  + %H :: 24小时制中的小时数
  + %I :: 12小时制中的小时数
  + %j :: 一年中的第几天
  + %M :: 分钟数
  + %m :: 月份数
  + %p :: am/pm标志
  + %S :: 秒数
  + %w :: 一星期中的第几天
  + %x :: 日期,例如,MM/DD/YY,可能随着区域和系统而变化
  + %X :: 时间,例如,HH:MM:SS,可能随着区域和系统而变化
  + %y :: 两位数的年份
  + %Y :: 完整的年份
  + %% :: 字符'%'
+ clock() :: 返回当前CPU时间的秒数,一般用于计算一段代码的执行时间
*** 其他系统调用
+ exit() :: 终止当前程序的执行
+ getenv($环境变量名) :: 获取环境变量的值
+ execute($cmd) :: 执行一条命令,等价于C语言的system,返回一个错误码
+ setlocale($区域名,$分类目 :: 设置当前Lua程序所使用的区域
** debug库
在调试库中有一个重要的概念是栈层,它是一个数字,表示某一时刻某个活动的函数. 调用调试库的函数是层1,调用这个函数的函数是层2,依此类推.

*** 自省函数
自省函数允许检查一个正在活动中程序的各个方面,例如它的活动函数栈,当前执行的行,局部变量的名称和值

调试库中的所有自省函数都能接受一个可选的协同程序作为第一个参数. 这样就能检查那个协同程序的函数情况.

+ getinfo($函数或层栈) :: 得到一个table,包含了与指定函数相关的信息. 其中table中的字段有以下几种
  - source :: 函数定义的位置
  - short_src :: source的短版本,最多60个字符,可用于错误信息中
  - linedefined :: 该函数定义在源代码中第一行的行号
  - what :: 函数的类型. "lua"表示普通lua函数, "C"表示C函数, "main"表示lua程序块的主程序部分.
  - name :: 
  - namewaht ::
  - nups :: 该函数的upvalue数量
  - activelines :: 一个table,包含了该函数的所有活动行的集合.
  - func :: 函数本身
  - nparams :: 函数必填参数数量
  - isvararg :: 是否包括可变参数
+ getinfo($函数或层栈,$表示要收集哪些参数的字符串) :: 第二个参数指定希望获取哪个信息,这个参数中的每个字母都表示一组字段,这些字母有:
  - n :: 选择name或namewhat
  - f :: 选择func
  - S :: 选择source,short_src,what,linedefined和lastlinedefined
  - l :: 选择currentline
  - L :: 选择activelines
  - u :: 选择nups
+ traceback() :: 返回一个表示追溯结果的字符串 
+ getlocal($函数栈层,$变量索引) :: 返回局部变量的名字与他们的当前值. *如果变量索引大于活动变量的总数返回nil,如果栈层无效引发异常*
     lua按局部变量在一个函数中的出现顺序为它们编号,但编号只限于在函数的当前作用域中活动的变量.
+ setlocal($函数栈层,$变量索引,$newVal) :: 改变局部变量的值. 该函数发回变量名,若变量索引超过范围,返回nil
+ getupvalue($函数/闭包,$变量索引) :: 访问lua函数中所使用的 *非局部变量*
+ setupvalue($函数/闭包,$变量索引,$newVal) :: 修改lua函数中所使用的 *非局部变量*


*** hook
hook允许跟踪一个程序的执行. 有4个事件会触发hook:

1. 当lua调用函数时产生call事件

2. 当函数返回时产生return事件

3. 当lua开始执行一行新代码时产生line事件

4. 执行完指定数量的指令后产生的count事件.

注册hook的方式是调用 =debug.sethook($hook函数,$事件掩码[,$count])=

+ 第一个参数为触发的hook函数. lua会用一个字符串参数来调用hook函数,这个字符串描述了触发hook的函数("call","return","line","count")

  对于line事件来说,lua还传入一个表示代码行号的参数. 

  在hook函数内部可以调用debug.getinfo来获取更多的信息.

+ 第二个参数为一个字符串,描述了要监控的事件. 'c'表示监控call事件,'r'表示监控return事件,'l'表示监控line事件

+ 第三个参数为一个可选的数字,用于指定多久获得一次count事件.

若要关闭hook,只需要不带任何参数调用 =sethook= 即可.
