* 源于实践的ERP123
** ERP123的价值
1. 渐进的提升管理水平
2. 控制投资风险
3. 积累实施能力
4. 阶段性成功能树立信心
5. 用于评估企业信息化水平
** ERP123具体内容
1. ERP1：完成财务业务同步管理（随时算细账）
2. ERP2：建立企业的计划管理体系（销售、生产、采购计划的关联和协调）
3. ERP3：完成整体信息化管理系统（全面预算管理）
** ERP123应用基础
1. 为企业的数据进行标准化工作（编码）
2. 对企业的管理工作进行专业化分工
3. 为企业建立价值评估体系（运用财务系统对企业各流程进行价值评估）
** ERP123方法论
1. 企业管理流程：销售、生产、采购三大只能驱动原材料到产品的转换，再加上库存和财务两大只能展示物料的状态和价值
2. ERP1（解决繁琐的数据记录及处理问题）+计划管理要素->ERP2（物料清单、需求规划、生产订单）+管理要素->ERP3（主生产计划、产能管理、车间管理、质量管理）

* ERP应用前的思考
** 是否需要ERP（内部原因？内部因素？）
1. 竞争对手是否实施了ERP
2. 企业规模的大小是否还能做到集中管理或者是否还能忍受分散管理的不便
3. 数据不同步是否使你烦恼
4. 掩盖隐患的汇报
5. 企业是否正在扩展
** 需要怎样的ERP
*** 明确行业属性
a. 离散行业：生产过程中基本上没有物质发生变化，只有物料的物理形状和组合发生改变，即最终产品是由各种物料装配而成，并且产品与所需物料之间有确定的数量比例
	ERP应用特征为：可以用BOM来准确描述产品构成，就可以用MRP来作为企业的计划方法。
	ERP实施过程为：先完成财务同步管理（ERP1）->再完成销售、生产、采购计划管理（ERP2）->最后选择车间管理、全面预算管理（ERP3）
b. 流程行业：生产过程中物质发生了改变，最终产品与所需物料之间的数量比例关系容易随生产条件的改变而改变，且最终产品所需物料的种类极少，以至于可以非常简单计算出来
	ERP应用特征为：没有必要、也不能用MRP来作为其计划办法，因为物料少，且最终产品与所需物料之间的关系也基本上不能用物料清单来描述。
	ERP实施过程为：财务业务同步管理->预算管理来代替计划管理->全面预算管理及其他功能
c. 混合行业：流程行业的企业中，产品包装成本占有较大比例的一类企业。这类企业前期生产是流程的，后期包装是离散的
	ERP应用特征为：前期生产可以不考虑计划管理，后期生产由于完全可以红BOM来描述产品，所以可以用MRP来进行计划管理
	ERP实施过程为：财务业务同步管理->销售、生产、采购计划管理->全面预算管理
d. 流通行业：不进行产品生产，只进行产品买卖。
	ERP应用特征为：不管什么形态的企业，都完全可以选择ERP1来进行财务业务同步管理，都完全没有必要应用MRP。
	ERP实施过程为：财务业务同步管理->更专业的管理软件来完成计划管理/预算管理->全面预算管理
e. 服务行业：没有实体产品
	ERP应用特征为：由于不涉及产品，采购的只是一些产品，销售是一种服务，所以基本也可以应用ERP1.
	ERP实施过程为：财务业务同步管理->根据规模考虑选择专门正对您的业务进行开发的专业管理软件来升级到ERP2->全面预算管理
*** 判定管理信息化程度
a. 生产技术的信息化程度
b. 管理技术的信息化程度
c. 定位管理瓶颈：中国企业普遍的管理瓶颈都在销售管理方面
*** 如何实施ERP
1. 向ERP专家咨询
2. 整体规划分布实施
3. 人员培训
*** 如何投入
1. 组建且项目团队
2. 确定是否IT外包
3. 选择ERP供应商
	a. 有成熟的ERP产品
	b. 有较强的实施服务能力
	c. 是一个长寿的企业
	d. 能够不断为顾客进行投入
4、精打细算分类投入
	a. 软件产品费用
	b. 实施费用
	c. 培训费用
	d. 服务费用


*  ERP1――财务业务同步管理
** 手工管理面临的问题
*** 传统财务报表的局限
	a. 报表目标过分抢掉国家宏观经济管理和调控服务。
	b. 现行财务报表所提供的信息主要是面向过去的财务信息，并且统一运用货币计量，缺少对使用者未来决策有重要参考价值的信息
	c. 现行财务报表模式是立足于企业已发生的确定性交易和事项，对这些事项的分类，都是从事项的实质性角度来确立的，它对使用者决策所需信息的相关性较低
	d. 滞后严重
*** 无法监控业务状况
a. 无法监控销售管理业务：
	销售有区域和产品两个角度
	销售产品种类丰富
	销售业务每时每刻都在进行
	任何销售过程都不可避免会出现一些状况
b. 无法监控库存管理业务
	库存种类过多
	库存对象有不同的批次分类
c. 无法监控采购管理业务
	对采购量的控制力度较弱，原因是对库存量的把握不及时
	对采购资金的控制力度不够，原因在于财务现金流量不清楚
*** 业务得不到财务的支持
a. 销售管理得不到支持
	销售管理需要财务给予的最大支持体现在收款方面
	销售业务得不到财务支持的另一个方面是反映在产品的销售定价方面，在很多手工管理状态的企业中，产品根本就无法准确核算到单品成本
b. 库存管理方面得不到支持
	库存管理需要财务给予的支持来自于对存货的核算。
c. 采购管理方面得不到支持
	采购管理方面需要财务给予的支持主要来源与应付款（确定那些应付款应当立即支付，那些供应商的应付款还可以缓一缓）
	采购管理需要财务支持的另外一个内容就是采购资金的失效，即在什么时间，可以支付多少金额。
*** 管理中不能实时掌握企业运营
**  ERP1应用方案
	ERP应用方案将围绕规范企业的销售、采购、库存、财务管理，提高业务运作效率来展开。以实现企业财务业务同步管理为目标，既能够将销售、采购、库存管理业务中的各种原始单据实时生成记账凭证转到财务手中，做到财务对业务的实时反应，谁是可以对企业的经营情况算细账
*** ERP1的管理内容
a. 销售管理
	售前管理：以销售报价为核心内容
	销售执行与控制：以销售订单为核心
	售后统计分析：以销售管理过程中的数据为内容
b. 库存管理：企业物流管理的核心地带，对物品进行精细化管理
	解决手工管理低效率的输入问题
	随时方便地盘清库存
c. 采购管理：企业资金流出的最大出口
	钱少重复购买
	供应商管理（供应商信息共享）
d. 财务管理：最基础的管理职能承担着对企业的物流运作过程进行价值评估的作用
	几乎所有涉及到业务活动的原始单据，都可以自动生成财务记账凭证
	凭证自动计入各种账簿
	实现企业的实时管理
e. 其他扩展应用
	售前分析：通过可用量（ATP）运算实现售前对可交付产品数量的确认
	合同管理:实现对供应商和客户合同进行全程管理
	CRM：实现从售前、售中跟进到售后交付的全过程客户管理
	网上银行：帮助企业出纳网上银行自动对账
	网上报销：方便快捷处理企业内部员工日常借款、报销业务，以及在报销时的费用控制
	人力资源管理：实现标准、规范、便捷的人事、合同、薪资等管理，为企业建立标准、统一的人力资源工作平台，极大地提高办公效率
	办公自动化：为企业规范办公流程，实现及时沟通与协同办公，保障企业制度的高效执行
f. 增值应用模块：在不影响核心应用的基础上，充分利用已经实施的ERP1数据，为企业增加ERP的使用价值
	管理驾驶舱：企业管理的控制室，总经理的助手，提取分析ERP中的各种数据
	成本管理：提供成本预测、成本核算、成本分析
	预算管理：控制企业经营
	资金管理：根据应收、应付与现金的运行状态，做出资金预测，制定资金使用计划，帮助企业随时掌握企业未来的资金流向、流量和盈缺情况，防范于未然
*** ERP1的应用流程
一般而言，软件供应商通常都是根据企业对一类业务的处理逻辑设计应用流程的，尽管每一项管理内容仅仅是这种应用逻辑上的一个环节但无论什么样的流程经过细分的结果，最终肯定落实在一个底层的软件功能模块中，所以，从这个意义上讲，流程帮助人们认识ERP产品的应用方式，最终真正认识每一个功能模块的作用。
a. 销售管理应用流程
	销售订单生产（销售报价直接生成、销售合同生成、直接手工编制）-（审批正式下达销售任务）->销售发货->销售出库确认->销售开票，应收单据审核，销售成本结转->收款工作->销售订单管理工作
b. 库存统计分析应用流程（以出库业务和调拨业务为主）
	物品出入操作记录在库存账里面（现存量、不合规品查簿、流水账、呆滞积压查簿、库存台帐、供应商库存、代管帐、入库跟踪表、委托代销备查簿，货位卡片和货位汇总表）->库存统计表（库存展望、业务类型汇总、存货分布表、收发存汇总表和限额领料汇总表等）、储备分析（安全库存预警、呆滞积压分析、短期存货查询、超储存查询、库龄分析，缺料表）
c. 采购管理应用流程（采购订单为核心的应用操作）
	采购订单（物料申请、采购合同生成、手工编制）-（审批）->采购到货维护->采购到货检验->采购入库或不良品处理（退货，降级入库）->采购订单关闭
d. 财务管理应用流程
	薪资福利管理就是对“人”这个资源进行核算
	现金收支与银行对账、应收管理、应付管理就是对“财”进行核算
	固定资产、存货核算、跌价准备就是对“物”这类资源进行的核算
	凭证处理（对资源进行核算）-对凭证分类处理->各种帐表查询-评价->财务报表、现金流量表-分析->财务分析
*** 实施ERP1的基础（标准化工作，核心是简历企业所有管理对象的标准编码）
	a. 存货（存货编码、存货代码、存货名称、规格型号、计量单位组、主计量单位、系统默认单位）
	b. 供应商与客户（编码、名称、简称、所属分类、所属地区、所属行业、税号、法人代表、开户银行、银行帐号等）
	c. 部门：企业下属具有分别进行财务核算或业务管理要求的单元体（部门名称、负责人、电话、地址、部门属性、上级部门、传真等）
	d. 人员（人员编号，性别、行政部门名称、人员属性、人员类别、银行账号、照片、年龄、职称）
	e. 仓库（仓库编码、仓库名称、所属部门、仓库地址、电话、负责人、几家方式、是否货位管理、仓库属性）
*** 同步管理应用分析
a. 销售业务与财务的同步管理
	销售部门本身可以用销售订单直接产生发货单，而无须再重新填制发货单
	库存管理可以根据发货单直接生成销售出库单，而无须重新填制销售出库单
	核算库存时可以直接根据销售出库单产生记账凭证，无需重新再做凭证
	销售发票开出时，可直接取用销售订单中的客户、品名、数量、价格
	可以根据销售发票直接产生记账凭证
b. 采购业务与财务同步管理
	可以通过采购订单直接生成到货单
	可以通过采购到货单直接生成采购入库单
	可以根据采购订单直接生成采购发票
	可以根据采购入库单直接生成记账凭证
	可以根据采购发票直接产生记账凭证
c. 精准的库存可用量共享
	可用量与四个因素有关，即现存量、冻结量、预计入库量、预计出库量。其中现存量和冻结量是一个固定状态，而预计入库量和预计出库量是根据不同企业的管理要求自己选择设置的
d. 给财务对业务信息的共享
	可以根据出入库单直接自动生成记账凭证，无需再输入凭证
	可以根据采购和销售发票直接自动产生记账凭证
	可以铜采购管理共享供应商信息，直接引用方便了应收款的管理
	可以根据已经有的记账凭证找到业务单据，极大减少了差错时间。
** 管理价值体现
*** 解决的问题
a. 部门间沟通变简单了
b. 提供了财务对业务的支持，系统完整的应用应付管理，使得销售主管和采购主管能够胸有成竹地面对供应商和客户，这将会大大提高企业的信誉
c. 库存核算功能对库存资产的精确核算，为仓库主管消除了后顾之忧
*** 对企业效益的贡献
a. ERP是提高管理的重要因素，但是不是全部因素
b. ERP1实现了相对精细管理，天天都可以算细账
*** 规范业务管理
a. 数据的规范
b. 业务处理流程规范化（每一个数据都是可以找到负责人的，其而每一项数据只能有一个出处，与负责制很符合）
*** 各行业的应用变通
a. 工业企业和商业企业之间，差异性大多表现在动态数据上，而静态数据的差异是很小的
b. 服务行业不能用存货来进行管理，这种产品没有存货价值，种类有限。	



* 销售生产采购计划管理――ERP2
** 面临的问题
*** 库存积压（为避免停工待料按时交货而储备较多的产品和生产用料）
从作业标注啊衍生出的定额管理->以概率论和数理统计为基础的订货点法->以独立需求和相关需求为理论基础的MRP
*** 停工待料
a. 产生的原因：计划不周到、计划不细、客户多变、供应商失信、运输发生意外、采购人员失职等等
b. 再以销定产的经营方针指导下，生产计划一定是根据销售计划来制定的，采购计划又是根据生产计划来制定的。
*** 交货延迟
a. 产生的原因：停工待料是一个方面，单不排除由于计划安排不周而直接造成交货延迟的情况
*** 责任互相推诿
** ERP2应用方案
*** ERP2的管理内容
ERP2=ERP1+MRP，BOM，生产订单，委外管理
a. 物料清单（BOM）
b. 物料需求计划（MRP）
	MRP依据销售订单及需求预测，利用物料清单资料，同时考虑现有库存可用量等信息，计算物料净需求并提出新的生产订单、采购订单、委外订单。这一过程成为物料需求计划
c. 生产订单
	生产订单承担着生产任务下达，生产任务执行监控，生产任务完成统计的只能
	生产订单还可以作为生产领料的依据
d. 委外管理（通常在SCM中）
	委外的核销是要连同委外加工所发出的物料一起进行核销的，入库了多少委外品，出库了多少委外加工所需物料，是要对应上的。
*** 应用流程
a. 物料清单应用流程
简历物料清单的基础资料（物料基本资料维护：将产品及构成产品的物料分类成产成品、半成品、原辅料、包装物、委外品等。物料规划资料维护：在存货档案中将产品及构成产品的物料的计划属性进行定义如自制品、采购件、委外件、虚拟件等）->物料清单资料维护：按产品结构建立起产品与物料之间的多层次关系（物料清单资料维护，物料清单物料取代，物料清单物料删除）->物料清单查验与计算（物料低价码推算、物料清单逻辑错误资料表）
b. 物料需求计划应用流程
从销售管理模块中读取未完成的销售订单，销售预测手工输入预测订单->
订单选择：对未完成订单和预测订单进行处理。决定与测量和销售订单量的组合方式。最终确定独立需求（相当于确立了主生产计划）->
物料需求计划编制：根据确定的产品品种、数量、时间进行物料需求的计算。计划展开的结果得到了生产订单、采购订单、委外订单。
c. 生产订单管理应用流程
在ERP2的应用层面，由于还没有涉及到车间管理，所以在MRP计划展开得到生产订单后，只能进行一些局限在生产订单管理范围内的生产管理。
生产计划管理生成生产订单->
生产主管审核订单，下放生产任务通知->
生产订单执行：ERP2应用层面仅仅可以执行三个内容（依据生产订单进行，车间生产领料，进行半成品入库和进行产成品入库）->
对出库入库进行统计分析，提供给财务进行成本核算（在制品统计、生产完工产品统计和车间领料出库）->
生产订单关闭
d. 委外管理应用流程
审核委外计划订单：采购主管或者生产主管审核->
委外订单执行：委外订单备料计划确认，委外订单发料，委外加工材料成本核算->
委外订单到货维护：委外入库、委外加工发票、委外结算（发料情况、收货情况和发票情况吻合）->
关闭委外订单：根据委外入库情况对委外订单的执行情况进行查询统计
*** ERP应用基础设置
ERP2的应用基础设置主要是增加关于计划的属性设置：在ERP1已经简历的存货档案中增加一些没有的存货，对已存在的存货设置一些计划属性，进行一些参数设置
a. 增加存货的计划属性设置
自制
委外
外购
ATO模型：ATO模型是指在客户订购该物料时，其物料清单可列出其可选用的子件物料，即在ixiaos管理系统中可以按客户要求订购不同的产品配置。具有该属性的存货可用于生产制造中的业务单据和模拟报价功能，以及对存货的参照过滤。
PTO模型：具有与ATO相同的属性，所不同的是PTO可以安选配子件直接出货
虚拟件：无库存的装配件，它可以将其母件所需物料组合在一起，产生一个子件配件。这些虚拟件的木剑的装配成本将会包括虚拟件的物料成本，但不包括其人工及制造费用等成本要素。
b. 物料清单的主要内容设置
母件编码：可参照存货主档输入且必输入
母件损耗率：预设为0
版本代号：建立主清单时必输入，简历替代清单时可不输入
版本日期：表示物料清单版本的生效日期，建立主要清单时必输入，默认为系统日期。“母件+结构自由项”唯一
替代标识：建立替代清单时必须输入。“母件+结构自由项”的替代标识唯一
替代说明：替代物料清单的说明，建立替代清单时必须输入
基本用量：每一个母件需要多少子件的数量
子件消耗率：预设值为0.离散型制造业适用
c. 计划的时间参数设置
MRP计划展开时要用到最主要的时间参数就是时栅。时栅即使一个时段，在MRP进行计划展开时，会按照时栅规定的时段将相应在这个时段中的需求进行汇总
*** 计划管理应用分析
a. BOM建立与运用分析
	用于物料需求计划
	用于生产领料
	用于产品成本核算
	用于销售报价
b. 物料需求计划应用分析
	MRP将销售管理、生产管理、库存管理、采购管理、委外管理这些管理只能间内在的关联关系表达的淋漓尽致，最充分地体现了ERP系统对企业资源规划的整体性
c. 生产订单的关联应用
	用于销售管理：销售人员如果想知道他所负责的销售订单生产状况，可以通过销售订单查询到对应的生产订单
	用于库存管理：自动产生生产订单领料单，直接做配比出库单，直接做半成品或成品入库，直接产生限额领料单
	用于采购管理：
	用于车间管理：
d. 委外管理的关联应用
委外件与采购件的不同在于委外件有子件，而采购件无子件
	用于库存管理
	用于财务管理
	用于生产管理
** 管理价值体现
ERP2标准着企业信息话管理的应用层次已经由业务操作层上升到计划管理层。
*** 解决的问题
a. 提供高效的计划管理工具进行规划库存物料的管理和压低库存
b. 保证绝大部分物料能够按照最合理的数量进行采购和存储
c. 最大限度地减少企业交货延迟的情况
d. 采购任务的安排更加客观公正，分工明确，责任清楚，减少相互推诿和产生的内讧
*** 协调创造价值
a. ERP1降低企业的非结构性库存积压，ERP2降低企业得结构性积压
b. 提出为销售和市场而生产的理念
*** 变被动管理为主动管理
a. ERP2的应用，扩大了您的管理范围和管理的深度
b. ERP2的计划管理功能，可以让您随时模拟企业的运作过程
** 行业用用特点
*** 离散与混合制造业应用特征
a. 离散制造业的应用特点：
	离散制造业就是ERP的原型
b. 混合制造行业（包装成本凸显的流程制造行业）应用特点：
	基本上没有半成品和在制品，产品构成是标准的，所建BOM为标准BOM，无替代件生产提前期非常明确，MRP应用的理想场所
c. 流程制造业应用特征：
	生产物料少，一般没必要使用BOM，计算计划量简单，一般不适合应用MRP这种以BOM为核心的计划管理方法。
	在实施ERP2时，建议只采用生产订单对其生产过程进行管理。而其计划管理建议选用预算管理来替代计划管理。
d. 其他行业特点：指商业企业和服务类企业
	这类企业的特点是没有生产活动。需要专门的软件定制
	并不管什么杨的业务类型，预算管理都能帮助完善计划管理

* 全面信息化管理――ERP3
** 全面信息化描述
支撑全面信息化管理的基础就是企业经营管理及软件技术应用这两个平台。企业经营管理平台由企业标准化管理及明确的管理专业化分工构成。软件技术应用平台则是由ERP及相应的网络技术构成
** ERP3应用方案
*** ERP3的主要管理内容
a. 产能管理：帮助企业计划人员将生产计划按照工艺路线和工序级计算出能力需求
	解决能力与需求之间的冲突，在企业时间应用中，能采取的措施就是调整销售订单和预测订单，重新生成主生产计划和物流需求计划。
	粗能力需求计划（RCCP）用于验证是否具有足够的可用产能以满足主生产计划的能力需求。限于工作中心的关键资源
	细能力需求计划用于合适是否有足够的可用能力以满足MRP计划的能力需求。
b. 车间管理：是生产订单所规定的生产任务具体执行落实的过程管理，记录车间所有活动
	车间管理负责维护工艺路线和替代工艺路线，同时支持公用工艺路线。
	车间管理维护的工艺路线也是作为产能管理，产品报价模拟的依据
c. 成本管理
	成本核算：成本控制的基础。
	成本计划：成本的计划管理主要是为成本预测和分析提供一种依据
	成本预测：运用移动平均和年度平均增长率法已经计划（历史）成本数据对成本中心总成本和任意数量的产品成本进行预测
	成本分析：分析计划成本与实际成本差异，分析产品的成本项目构成比例
d. 质量管理
	来料检验
	产品检验
	在库检验
	发货检验
	退货检验
	工序检验
	其他检验：处理流程制造行业的生产过程检验、处理临时性非程序性检验业务的检验
e. 预算管理
预算管理是指从企业的整体出发，通过科学预测，以货币或数量的预算指标形式明确企业预定期间内的经营成果、财务状况，从而对企业及个业务部门的经济活动进行调整与控制。
	预算目标管理：量化指标与非量化指标
	预算假设建立：对预算对象所属期间的经济环境进行合理设定
	预算体系搭建：预算项目、预算类型、预算版本、预算表设计、预算表格式、预算表审核、预算表导航
	预算编制：录入预算数据
	预算调整：
	预算控制：制定预算控制对象与控制规则。
	预算分析：将编制的预算数据与预算实际执行行数进行对比
f. 资金管理
	资金预测：预测企业在一段时间内资金的短缺和盈余情况，以防范支付危机，提高资金的是要用效率
	筹投资管理：调整企业筹资结构，实现最优资本结构。合理计划投资结构，打到资金的合理使用
	资金盈缺分析：及时弥补资金缺口，合理安排盈缺资金避免资金闲置。
	资金风险提示：预警
g：管理驾驶舱（BI？？）
面对企业中高层管理中的产品，依据系统中的数据为管理中提供各种查询分析功能
	为企业中高层管理中提供信关系信息平台
	及时地传送关键信息
	规避风险
	增强ERP系统的易用性
	支持PDA的应用
*** ERP3主要应用流程
a. 产能管理应用流程：生产模拟
	准备工作：设置一些进行产能计算所必须的基础数据->
	产能管理参数设定：资源需求规划RRP、粗能力需求计划RRP、能力需求计划RCCP->
	资源需求计算（资源需求汇总表）、粗能力需求计算（粗能力需求汇总表，关键资源负载明细表）、能力需求计算（产能问题检验，能力需求汇总表，资源负载明细表）
b. 车间管理应用流程
	准备工作：最重要的是物料工艺路线维护->
	生产订单工序计划生成：将已审核的生产订单产生各生产订单的工序资料->
	生产订单工序资料维护、重复计划工序资料维护->
	生产订单工序转移单：在工序内或工序间移动物料->
	生产订单工时记录单：个班次或员工实际完工数量及耗用工时。
c. 产品成本核算应用流程
	采集数据：生产数据采集、成本分摊数据采集、材料成本数据采集、期间费用数据采集->
	产品成本计算->
	成本核算报表
d. 质量管理应用流程：贯彻于企业的各项业务活动中
	质量管理与采购管理通过采购到货单相连
	质量管理与委外管理系统通过委外到货单接口
	生产的产成品、半成品，在入库前由生产订单报告检查
	车间管理与质量管理通过工序转移单接口
	销售发货时，通过发货单报检
	销售退货由退货单确定是否质检
	库存中的存货，可以进行周期检查
	合同管理通过采购管理、销售管理中的到货单、发货按携带合同号到质量管理，可以实现对合同的质量管理
e. 预算编制应用流程
	预算目标->审批->按公司经营目标下达预算目标->部门预算编制->部门预算报送上级->公司审批->预算发布->预算下达->预算下达的部门预算
f. 资金数据采集应用流程
	资金管理就是通过对各管理业务中有关资金使用数据的采集汇总来进行资金管理的，再次基础上实现资金预测、筹划、分析
*** ERP3应用基础设置
a. 产能及车间管理基础设置
ERP3需要在ERP2建立的BOM基础上，对每一个自制件进行有关生产关于路线的基础设置。内容包括
	工作中心：由一个或多个人员、设备或供应商组成
	资源：计划、执行或成本计算所要求的任何事务
	工序：制造过程中的一个步骤
	工艺路线：对产品制造工序的一个序列
	主要工艺路线：制造产品中最常用的一组工序
	替代工艺路线：通过指定物料和替代标识来替代工艺路线
	公用工艺路线：任何具有统一物料清单类型的两个物料均可以共享公用工艺路线
b. 成本管理基础设置
	部门档案->
	产品结构（物料清单）->
	选择成本核算方法和数据精度、定义材料费用来源、定义制造费用来源、定义其他费用来源、定义折旧费用来源、定义人工费用来源->
	选择核算成本中心、定义成本中心（服务）->
	定义产品属性、定义费用明细与总账接口->
	定义分配率、建账期初余额、定额管理
c. 质量管理基础设置
	检验标准
	资料检验方案
	检验项目
	检验指标
	工艺路线质量信息
d. 预算管理基础设置
	预算项目
	预算指标
	预算周期
	预算口径：归集预算数据或进一步标识预算数据的分类
	预算基准：编制当期预算时的参照数据
	预算类型：预算表的抽象分类
	预算假设：对预算对象所属期间的经济环境进行的合理设定
e：资金管理基础设置
	收付款预期
	设置预测模板
	定义筹投资类别
	单位定义
*** 全面应用分析
a. 完善计划管理
b. 完整的生产管理
c. 用预算管理提高管理能力
d. 掌控企业资金
** 管理价值体现
1. 以在最佳方式生产
2. 完整体现集中管理优势（通过数据的集中，充分掌握下情，实现了对权利的监督）
3. 实现管理驾驶舱（对那些集中管理相当重要的数据的展现方式）
** 行业应用特征
1. 离散制造行业应用分析
离散制造业在选择ERP3的应用时，一定要将体现这个价值点的主生产计划、产能管理、车间管理、质量管理、工程变更这样一些模块作为其主要的实施应用功能。
2. 混合制造行业应用分析
大多数混合行业的车间管理和产能管理显得没哟在离散制造也中那么重要。如果需要供需检查的话，可以将工序检查变通为一种制品检查就可以了
3. 流程制造业
车间管理简单，产能计算也简单，可以不考虑生产计划、产能管理、车间管理、工程变更等模块。如果非常有必要的话，应该进行生产设备的生产状态管理。
4. 商业企业
在实施ERP3的时候就要注意将专项开发的应用与ERP的应用进行整合。



* ERP123之后的扩展
一. 电子商务
二. 供应链
三. 商务智能
四. 企业办公自动化系统OA
OA着眼于协同工作、公文处理、文档管理、行政办公等。ERP着眼于企业的销售、采购、生产、库存、财务等过程及资源控制与计划
OA侧重于企业的日常办公，ERP侧重于企业的具体业务过程运作
五. CAD
1. CAPP计算机辅助工艺规划：将产品设计与产品生产相结合的信息化应用系统
2. PDM产品数据管理ishi一种对制造企业产品形成过程中的有关信息和过程进行统一管理的技术，是一种利用数据模型对制造企业的产品形成过程进行管理的方法
六. 过程控制
ERP对企业管理的最大贡献在于对企业经营活动中所产生的数据的实时采集，而过程控制则更强调对生产现场各种信息的实时采集与集成且过程控制采集的数据更加细致。
七. 自动化仓库管理
