#+TITLE: 你为什么想不到
#+AUTHOR: DarkSun
#+EMAIL: lujun9972@gmail.com
#+OPTIONS: H3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* 为什么聪明人也犯傻
** 盲点是思维的一部分
** 三个最常见的盲点
   * 我不清楚自己不知道
   * 只见树木不见森林（缺乏系统思维）
   * 对自己范的傻没有意识到
** 关键在于态度
   将他人视作白痴很容易，但是这并不会有多大好处，因为这对你理解那些看起来不可理喻的观点或行为没有任何帮助，同时也绝不会动摇对方
** 改善
   1. 认识到盲点的存在是改善的开始
      当我们试图将他人的行为解释为道德败坏时，我希望大家能三思而后行，理由有二：
      第一、当我们进行详细考察时，那些表现为简单的贪婪、自私或懒惰的行为往往会显露出它复杂的本质
      第二、认为他人无药可救反而会使人的改变变得困难
   2. 支持与责备结合是劝他人改善的最佳方式
   3. 给别人提供改过的机会
** 小结
   本书将从教育学、创造性研究、认知心理学、批判思维、儿童发展及哲学等领域摄取各种知识来解释和支持我的观点：人们很多时间所表现出的愚蠢是盲点所致。本书的第一目的就是描述最常见的十种盲点并提供一些克服他们的策略。
   第二、我还将让大家更清晰第意识到，我们是多么经常讽刺那些和我们不同的人，并总是将他们的观点和行为认为是愚蠢或不道德的。本书中将会提出一个不同的解释：也许不是智力或道德的问题，而是我们自身的盲点妨碍了对一些事情的理解。我希望“盲点”这种视角能够改变我们对一些分歧问题讨论的基调，当他人因为盲点引发伤害时，我们秉承以盲点来解释行为的这种意识或心态，用以帮助我们更有支持性的方法来挑战他人的错误。
* 听从你的心
** 盲点1——在大脑思考之前身体先下意识的就产生了行动
   * 缺乏思考导致愚蠢的错误（下意识的行动不经过大脑）
   * 欠缺对思考机会的敏感性（不能辩证的思考问题）
** 原因：
   压力和惯性破坏思考意识
** 策略：情绪是最好的信号
   1. 使用危机中的情绪作为暂停信号
      如果在危机中体验到惊慌、时间压力或挫败感、那就意味着我们该暂停了。
   2. 在压力情景下获取更多时间思考
   3. 在日常生活中安排反思时间
      * 进展如何
      * 学会了什么
      * 达到预期了吗
      * 下一次我们能有什么不同
      * 关于那件事，什么让我感到惊讶
      * 如果还没参与此事，现在我们要开始吗
      * 如果我们公开承诺此事，现在我们要继续吗
   4. 拓展视野
   5. 去思考、去行动
      反思只是生活的一部分，另一部分就是投入地去体验。
** 小结
   如果不停下来仔细思考就会导致作蠢事。同时，意识到“现在应该停下来思考”也是很难的事。处于危机中或每天按部就班的生活很容易让我们忽略思考的机会，而忘记我应该停下来进行思考。在压力情景下，我们应该联系让我们意识到能提醒自己思考的线索，而一成不变的生活中，我么也应该定期安排反思时间，打破乏味的沉寂。
* 看清自己缺什么
** 盲点2——电视里的人看起来都很蠢
** 原因：
   我们很难知道自身的只是缺陷是什么，这是我们思维方式的一部分。我们一贯的思维方式就是假定自己知道的答案是正确的，而不会习惯地质疑自己。
** 策略：有缺陷才是正常人
   1. 创建问题地图
   2. 创建已知和待知列表
   3. 质疑已知列表
   4. 承认知识是通过经验得到的，不知道也很正常
   5. 支持自己
      当别人认为我们愚蠢时，我们需要给以自己支持。学会用两个问题保护自己：
      * 我怎么知道哪些知识
      * 你是怎么学到的
   6. 尊重人们的不同兴趣并不意味这可以纵容自己在某个领域的无知。不同领域的知识，不同的智力有不同的用途。
** 小结
   我们非常容易给他人贴上愚蠢的标签，原因仅仅是他们不知道人们认为每个人都应该掌握的某些知识。缺乏知识不是盲点，关于无知的盲点反而是我么往往不知道自己有哪些知识不懂，这种知识缺陷很难被发现，我们可以通过使用诸如问题地图、已知，待知列表等方法在某种程度上进行弥补。但是既然没有人是万能的，所以我们也应该学会一些方法，来应对他人将自己的无知是做缺点或愚蠢的情况，如果我们认同每个人都会被不同领域所吸引，能真正认为所有的智力都有价值，那么我们就更能尊重人们展示出智力的多样性。
* 习惯使大脑变迟钝
** 盲点2——忽视身边事
** 原因
   1. 我们队环境产生适应性的趋势和感觉偏好，正是没有注意这一盲点的两大重要根源。
   2. 习惯导致忽视
   3. 忽视内部世界：缺乏对内心的审视
   4. 没有注意自己的思考内容
   5. 没有注意自己的思维风格和学习风格
   6. 将熟悉的事物视作正常的确是人类适应环境的一种能力，但有时候也要为这种适应付出高昂的代价。
** 策略：给你的生活上点色
   1. 识别感觉缺陷
      * 想一想别人经常对我们的抱怨
      * 看看那自己的长处在哪方面
      * 我们习惯使用的语言也反映了我们的主导感觉风格。
   2. 寻找新鲜的方法体验熟悉的事物
   3. 跟陌生人对话
   4. 发现自己的学习风格
** 小结
   习惯和适应不仅导致我们错过环境中某些方面的信息，还会忽视内心世界的变化。稍纵即逝的思维和情绪在思维中升腾，然后消息殆尽，几乎都来不及感知。此外，我们个人注意的偏好差异是一个过滤器，它对某些信息很敏感，而完全忽略其他的感官信息。本章讨论的各种应对策略是为了帮助我们找到方法，探寻哪些信息会被过滤，从而用新鲜的方法体验熟悉的事物。
* 给自己一个真实的拥抱
** 盲点4——对自己的双重标准（当局者迷，旁观者清）
   * 人们对待自己态度诡异
     一方面我们承认看清楚自己很难。
     另一方面当别人表现出类似的问题时，我们仍然会表现出不理解。
** 原因
   导致出现这一盲点的部分原因是我们从来没有直接认识过自己。
** 策略：他人的意见比你想的更有益
   1. 利用偶然性察觉
   2. 获取他人的反馈
      在选择反馈前先问自己一些问题
      * 此刻我需要何种反馈
      * 谁技能支持我又能给我真实的反馈
      * 他人主动给以的反馈虽然很难接受，但还是客观而真实的
      * 他的观点有多正确
   3. 审查自我信念
      * 如果去做自认为不可能的事情，哪些糟糕的情况会发生
      * 我必须一步到位还是循序渐进
      * 自我意象阻碍了我们？
   4. 检查你的“是的，但是....”
      * 让不可能的问题情境消失
   5. 允许经验改变你
      只有当我们允许经验改变我们时，智慧才会出现。但是，这种智慧要求我们允许经验揭露自己的本真，揭露我们以前忽略的某样东西。
** 总结
   我们总是看不清楚自己。然而其他人会对我们有清晰的认识，因此需要获得他们的反馈以克服自身这一盲点。但是获得有用的反馈也不如想象中那么简单。本书提供额一些策略帮助人们获得由价值的反馈。此外本章还提供了一些方法帮助挑战有关自己的某些观点，尤其是关于自我力量的信念。最后。国家和个人一样，也会存在看不清楚自己的盲点
* 你总从自我的角度看问题吗？
** 盲点5——以自己的视角为主（兼听则明、旁听则暗）
** 原因
   以自己的视角为主是自然倾向
** 策略：多听、多度、多看
   1. 弄明白他人为什么会做蠢事
      运用个人经验使你设身处地地站在他人的角度思考问题
   2. 真正倾听鲜活的故事
   3. 使用艺术品和模拟练习来体验不熟悉的世界
   4. 否决前询问自己：什么时候我也需要这么思考？
   5. 我们有哪些共同的基础
   6. 世界并非非黑即白
   7. 开放有效地利用各种视觉
** 小结
   人们常常存在的一个盲点：无法从他人的角度看待问题。克服这一盲点需要积累大量有效经验。除了了解事实性知识以外，我们还需要通过想象来了解他人眼中的世界。能帮我们做到这一点的方法包括：真正倾听，进行模拟练习，通过电影、小说或其他艺术形式进入不同世界体验。由于这一盲点会影响我们队他人的理解或导致对他人的误解，所以它在很大程度上影响我们的人际关系。看上去通情达理是意见好事，但是有时我们也会强烈拒绝真正地体验他人的观点，因为如果这么做，我们对质疑自己的伦理道德信念感到恐惧。但是只要我们理解自己遇到的危险，就能发现解决这一两难问题的方法。
* 落入分类的陷阱
** 盲点6——认为“物以类聚，人以群分”是捷径（用一类事物来代表某个具体事物）
** 原因
   将事物分类是人类思维的自然倾向
** 策略：分类标准不是单一的
   1. 转变分类体系——通过不同的分类体系看世界
   2. 警觉将问题简化为老生常谈的回答
   3. 看到本质，跳出思维的狭隘性
      问问自己，“此刻我么真正需要的是什么”或“此刻到底会发生什么”
   4. 不要给他人贴标签
   5. 转换分类方式看人
** 总结
   我么常常会被分类局限了思维。对事物和事件进行分类让人类形成了一个盲点，这是因为分类不可避免地减少了事物的复杂性，但同时也规避了事物独特的特征。文中提出的应对策略，如转变分类，都旨在帮助人们恢复对事物复杂性的认识。此外，对人进行分类这一问题也引发了很多争议。当我们对人的分类导致忽略某群体的复杂性时，我们就可能会毫无意识地侮辱或者贬低他们。
* 迅速下结论省时省力
** 盲点7——仓促下结论的心理期待
** 原因
   * 不是所有知识都来自直接观察
   * 推理能力与受教育程度无关
   * 人们很难忽略某一表述的真实性而仅仅关注表述之间的逻辑关系
   * 在日常生活中，如果找不到适合的方法来组织相关的信息，尤其是要理解的事物包含一些变化的条件时，我们常常会被搞糊涂
   * 在日常生活中，我们会推理各种实际的事情，但是大多数情况下，这一推理过程是隐性的。它已经自动化了，以至于得到结论后，我们根本没有意识到过程到底怎么回事（太多的“显而易见了”）
** 策略：让思考过程显现出来
   1. 让推理过程可见
      * 我的理由是什么
      * 我应该怎样回应同事
   2. 敏锐捕捉谬论的启发
      * 常见的谬论 :: 攻击他人，而不是评价他人的观点。
		      拒绝某一解决问题的方法，而不是看到许多选择。
		      以非此即彼的方式思考，而不是看到多种选择
		      使用情绪诉求而不是用理由来支持选择 
   4. 注意常识背后隐藏的信念逻辑
   5. 通过反对者找到自己的逻辑漏洞
   6. 常常，人们很难说出自己的观点是基于什么推导而来的。这并不一定意味着观点没有理由。也许是因为人们拥有来源于个人经验的内隐知识，但是人们却难以有外显的意识。
** 小结
   人们用来解释谈话的意义及解决问题时所用的自然逻辑和解决正式逻辑问题时的思维方式不一致。当我们面临真正的逻辑难题时，在日常生活中能很好发挥作用的自然逻辑就会让我们误入歧途。
   
   但是，既然自然逻辑在日常生活中能很好的发挥作用，为什么我们又在思考某些日常生活事件时存在困难呢?原因是人们总是看不到自己的思维错误，这些隐藏在思维内容下面的推理过程常常是我们看不到的，这就导致我们可能会犯错。解决的方法就是尽可能让推理过程变得可见，这样就能更细致地考察它。但是当人们试图说服他人时，往往会忘记细致的思考。事实上，在政治领域，说服他人的方法往往依赖于人格特征攻击、情绪诉求等策略，而不是逻辑推理。最后在某些人眼中，逻辑思维存在着不良的名声，因为它总是和冷漠、线性思维及傲慢的态度联系在一起。
* 我相信他看到了怪物
** 盲点8——人们情愿相信诡异的事情
   是什么让人相信那些无稽之谈
** 原因
   * 很多事情不能直接观察，只能依靠相信别人
   * 大多数情况下，人们都会相信那些一直被教育要信任的个人和组织——和自己有共同的价值观、世界观的人。
   * 纷争一方的支持者通常会忽略或不接受另一方提供的证据
   * 我们会选择性忽略一些不符合已有世界观的信息片段，并且会毫不思考地久接受符合世界观的信息片段。
** 策略：沉住气，证据不足时别开口
   1. 停下来并自我询问以找到清晰的证据
   2. 放开态度——“这对你来说意味着什么”
   3. 从两方面深入考察证据
   4. 积极寻找和先入为主观点相悖的例子
   5. 调查信息来源的可靠性
** 小结
   热衷批判性思维的人鼓励人们要在严密的证据基础上来确定自己的信念。然而，我们发现对证据进行评定比表面上看起来要复杂的多。因此，我们经常只是简单地接受和我们固有观念吻合的证据，拒绝冲突的证据，而不是将自己的信念完全建立在所有证据的基础之上。这就导致了模糊证据的盲点：我们无法清晰地看待证据。为了弥补这一盲点，我们需要对已有的证据进行更细致的考察，并使用一些策略，如积极寻找反证。最终，这将会让我们修正自己的世界观，从而让自己看待世界的角度更完整、更精确。
* 大部分原因来自想象
** 盲点9——简化一切
** 原因
   * 童年养成认定前后发生的事情具有因果关系的思维模式
   * 当面临一些不寻常事件时，我们总是立即想看到这些事与什么相像，通过这种方式来理解它们。
** 策略：列出并分析各个原因
   1. 当我们尽力米面隐藏原因导致的盲点时，有两个关键步骤。
      * 事件的原因是否比我们已经认识的原因更复杂
      * 这些事件的发生是否真的有内在意义，或者只是个巧合
   2. 列出可能原因列表
   3. 分析原因
** 策略：考虑巧合与偶然
   1. 完全是巧合的概率有多大
   2. 一些偶然性事件在人的一生中发生的概率多大
** 小结
   经常我们都会得出错误的结论，认为是A导致了B。因为我们寻找的原因总是隐藏的，也是复杂的，我们总是满足于更明显和简单的解释。此外，我们还会犯另外的错误，因为很难决定我们看到的事件之间的关系到底是有内在联系的还是仅仅只是巧合。克服这一盲点的策略包括：寻找更复杂的原因，有意识地尽量考虑是否我们发现的关系只是巧合的可能性。最后，本部分还讨论了坚持“没有意外”信念的危险性。
* 沉溺在细节里的人
** 盲点10——看不到全景（缺乏系统的观念）
   一般来讲，我们并不是看不到不同的树木，只是因为过分关注个别的树，导致错过了整体的森林。
** 原因
   我们并不善于退后一步以更大的观点来看待问题。
** 策略
   1. 表格、图形和模式让系统可视化
   2. 询问“更大的系统如何影响这个特别的部分”
   3. 从群体系统的角度思考人与人之间的关系
   4. 注意开始变化的时刻
      过分关注当下，会导致我们无法看到更大、更历史性的图景。
   5. 考虑决定带来的长期后果、意外结果
      * 这个行动的可能后果有哪些
      * 我能想到与心理预期相反的糟糕结果吗
      * 抽象思维影响把我大图景的能力
      * 我们经常不回采取抽象方式思维或不回从更广的角度思考问题的一个原因，就是因为具体的、即刻的思维在许多情境下就足以应对问题。
      * 低年龄的孩子们一直持续具象思维，直到进入青春期后，才开始使用抽象思维。
      * 抽象程度过高，难以理解
** 小结
   人们往往无法看到事物之间的联系，无法看到整体大图景。经常，我们都可以被称为点特征人，总是只看到眼皮底下的事情。为了弥补这种只见树木不见森林的盲点，我们可以采取的方法包括：有意识地采取系统的观点，有时可以通过图表来表述各种元素只见的关系。人们容易忽略整体图景的一个原因是：要保持更大系统的视角要求我们以更抽象的方法来思考。最后承认系统对元素的巨大影响力意味着我们也要理解社会系统影响人和塑造人的力量。这就引发了一个问题：在采取行动或作出决定的过程中，我们能在多大程度上合理地归因于系统。
