#+TITLE: 关键20小时-快速学会任何技能
#+AUTHOR: lujun9972
#+TAGS: Reading
#+DATE: [2019-01-26 六 19:34]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* 快速习得技能的方法
技能讲究实用，偏实践.

快速习得技能的10个方法可以让我们不知不觉地对某个技能产生临时性的痴迷。还可以帮助我们判断某项技能到底值不值得我们为之执着。

** 优先学习自己感兴趣的技能
人们对于自己在意的事情，往往学得很快。

** 集中精力
不要尝试一口气学习多个技能，要像快速习得技能，就该把精力集中在一两门技能的学习上。

别的技能可以放在 "将来某时/也许"的清单中.

** 制定学习目标
如果你想学习真本事，那么首先应该明确学完这门技能后要求自己能达到什么样的水平。

制定目标时要有分寸，不能唾手可得，也不能好高骛远。

** 分解技能
定下想学习的技能后，把该技能细化成若干步骤。

在这些细化的步骤中挑选出至关重要的那些步骤，集中时间和精力进行学习。

** 获取工具
大部分技能的学习都离不开必要的工具，比如要学习编程就需要电脑

** 排除学习中的障碍
这些障碍可能来至于下面这些方面:

+ 训练前的准备工作
+ 缺少训练工具
+ 环境干扰
+ 情绪障碍

** 腾出专门时间学习新技能
为技能习得腾出时间的最佳方法是筛选出低效时间，将至淘汰。可以尝试一下时间记录法。

另外，建议你下决心保证20小时的训练量。一旦训练开始就别停下来。即使中途卡主也要坚持住。

** 及时反馈
尽可能快地了解你在技能习得中的表现。

如果反馈及时，我们会很容易把实际操作情况和目前所获得的结果联系起来加以分析，在作出适当调整。这样有助于快速学习。

** 计时训练
初学一门新技能时，尤其学习状态不佳时，往往容易过分估计实际投入训练的时间。

可以尝试使用番茄钟工作法进行计时

** 大量训练
力求完美容易让人产生挫败感。别去想完美的表现，必要的训练量和训练速度才是制胜法宝。

* 有效学习的方法
学习讲究理论化，偏抽象

** 收集信息
这一步的目的就是尽可能快速地了解重要的基础技能、关键步骤以及必要的学习工具。

你不用采用精读的方式了解信息，泛泛而读即可。
如果某一概念或学习工具被不同参考书反复提及，那么请你留意并在实践前做好相应准备

** 克服困难
在早期学习过程中肯定会有很多让人疑惑不解的地方。有目的地对此进行研究，直到问题解决。

不愿意克服困难时影响技能学习的主要因素。

** 关联类比
通过类比将新知识与旧心智模型进行关联，有助于新知识的习得。

** 应用新知识进行应急演练
为最坏的情况做准备，你会快速发现原本不太注意的学习要点

** 咨询交流
在投入时间和精力学习新技能前，有必要和内行聊一聊

** 排除干扰
我们要尽可能地预见可能存在的干扰因素，试着减少或消除它们。

电子干扰(电视、手机等)和生物干扰(家人、同事、宠物等)是最大的两个干扰源。

** 间隔重复
使用Anki、SuperMemo、Smartr等工具协助进行复习

** 归纳定式
大多数技能学习都有一套固定的模式。


** 尊重生理
最佳学习周期是90分钟左右。大脑和身体需要一个自然的休息期。

