#+TITLE: 奇特的一生
#+AUTHOR: DarkSun
#+EMAIL: lujun9972@gmail.com
#+OPTIONS: H3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* 谈谈有什么样的日记
  * 每天都是短短的明细账，没有记叙，没有细节，没有思考，没有情绪
  * 每个月到月底他都要做小结，画了一些图，列了一些表。到年终，有根据每月小结做一份年度总结，列出一览表。
* 作者想追根究底，了解事情的起源
  * 柳比歇夫二十多岁刚开始从事学术工作的时候，也明确地知道他要达到什么目标。他提出了他的工作纲领，并从而预决了他的活动的整个性质，事实上是至死不渝。
* 他的方法是怎么起的头
  * 他规定，短距离，二三公里路，最好步行，省得为了等车浪费时间、损害神经。
    步行还有一个好处，因为反正需要散步。
  * 我在一天之内是怎么安排读书时间的？ 
    1) 清早， 头脑清醒，我看严肃的书籍（哲学、数学方面的）。
    2) 钻研一个半到两个小时以后，看比较轻松的读物 —— 历史或生物学方面的著作。
    3) 脑子累了，就看文艺作品。
  * 计划就是挑选时间、规定节律，使一切都各得其所。头脑清醒的时候应当钻研数学，累了便看书。
  * 要采取这种方法，必须知道一切有效时间，洞察实践中一切空白点，所有时间一视同仁，也没有休息的时间，所谓休息的时间，是两种工作的交替。
  * 对时间的结算也是下个月计划的开始。
  * 实际与计划不符时，需要找出原因。
  * 做计划时列出主要任务。并将任务分解为行动
  * 除了年度计划，柳比歇夫还把他一生的时间制订成一个个五年计划。每过五年，他把度过的时间和平过的事分析一通，可以说是做个总的鉴定。
* 谈谈矛盾
  * 他的时间统计法不是一个节俭的计划工作者的预算，把他的时间统计法比作想向时间做自我剖析更为恰当。
* 幸福的倒霉鬼
  * 天才永远是哪个总其成的人。一种事业总有许多先驱者为之贡献智慧，最后轮到一个人来完成它，这个人就是天才。
  * 除了时间统计法之外，他还有几条守则
    1) 我不承担必须完成的任务
    2) 我不接受紧急的任务
    3) 一累马上停止工作区休息
    4) 睡得很多，十小时左右
    5) 把累人的工作同愉快的工作结合在一起。
* 伤感和自白
  * 柳比歇夫所有的不是夺目的闪光,而是忍耐.是从不放松的自我检查.他日复一日提高对自己要求的标准,毫不容情.

* 网上看到的不错的点评
  #+begin_example
      说明：里面有原文，有自己的理解。 
    　　偶粗浅的进行了下总结，主要目的是想提取柳比歇夫采用的方法，为我所用。 
    　　时间统计法不仅仅是记录时间的流向，还包含了精力管理，计划管理。 
    　　个人感觉里面很多理念和gtd也有类似相通之处。 
    　　很多人有对金钱记账的习惯，这是很好的习惯。但偶感觉时间尤其值得去记录。因为金钱没了，浪费了，还可以再赚，但时间没了，那可是再也回不来了。 
    　　 
    　　 一、产生原因 
    　　 柳比歇夫在年轻时（一九一八年），已经提出了他一生的奋斗目标-创立生物自然分类法。 
    　　他善于统计，通过计算得知，为达到目标，需要比常人或现在的自己付出更多的精力和时间。所以他开始找寻方法。 
    　　 
    　　二、过程 
    　　 他是逐步完善他的时间统计法的。 
    　　 开始，他只是充分利用一切时间下脚料，但后来时间下脚料越利用越少，而时间需求越来越大。 
    　　 于是他不断完善自己的时间统计法。 
    　　 他通过时间统计法，对自己进行了研究和试验。试验在写、读、听、工作、思考各方面，他到底能干多少，怎么干。 
    　　 他不让自己负担过重，力不胜任。 他循着他能力的边缘前进，对自己能力的掂量愈来愈精确。这是一条永不停顿的自我认识之路。 
    　　 最终，他形成了一套集时间记录，总结，计划于一体的系统化工作方法。这个方法包括精力管理和时间管理。对于精力，他根据自己的身体情况，精力旺盛和低迷的不同状态去安排计划，安排事情。 
    　　对于时间，他计算出一天可以用于工作的纯时间，用于去完成达到自己的目标。 
    　　 
    　　 时间统计法成为了他生活的框架。 
    　　 他在回答自己朋友的质疑时，回答：我习惯了这种方法，没有它，我什么也干不了。 
    　　 （个人认识：胜间和代的书中，多次提到，要有自己的框架，我理解的是应该有自己的系统 ，柳比歇夫根据自己的工作和身体情况，形成了自己的框架。） 
    　　 
    　　三、达到的效果 
    　　 1.柳比歇夫一生无数的成就。 
    　　 2.获得了大量的时间。确切的说是大量的时间去做达到目标的事。首先是很强的时间观念，让他不浪费时间到无意义的事上，再是做的计划，使柳比歇夫尽可能的不偏离自己的计划轨道。 
    　　 3.身体虽不好，但长寿，一生基本健康。因为他是根据自己的身体规律去工作，投入和产出达到了一定的平衡。他睡眠时间很长，有十个小时；他累了就去休息。这些对身体的投入，保证了他产出时需要的精力。 
    　　 4.证明，如果把才能集中到一个目标上，可以取得多么多的成就。 
    　　 5.可以了解到自己的变化，看书的数量，各种类的比重，时间的具体流向。 
    　　 6.对自己的做事能力做到心中有数，为做计划时提供很好的参考。比如通过统计总结出自己看一本书需要3个小时，那么在计划时，就将预算中拿出3小时归这本书。 
    　　 
    　　四、时间统计法介绍 
    　　 他利用统计学的知识对时间进行统计，分析。 
    　　每天一小结，每月一大结，年终一总结。 
    　　 1..1每天记录，什么都记下起讫时间，任何活动-休息、看报、散步，都记下时间，多少小时，多少分钟。误差不超过5分钟。 
    　　 不断看表,无休无止的进行自我工时标定。（建议想进行时间记录的朋友，买个便宜实惠的手表带下。毕竟看表比看手机方便多了。看表只需要一抬手腕，看手机需要从兜里掏出来，有时侯还要翻好几个兜。人很多时候会因为偷那么一点点懒而不去做一些事情，当然也包括看表了。） 
    　　多年来经常看表的结果，柳比歇夫肯定形成了一种特殊的时间感。借助于一种内在的注意力，感觉的到时间的流逝 
    　　小结所用的时间也记录。他的每篇论文都有时间成本。（看到有些朋友在用一小时一记录自己时间流向的方法，个人感觉那和时间统计法提倡的稍有出入。应该还是像柳比歇夫那样，什么都记下起讫时间为好） 
    　　（开始很容易忘记去进行时间记录。这里提供个我觉得可行的方法进行参考。忘记记录时间，应该是没有那个习惯。通过每天的不断提醒，让大脑形成下意识的反应，这个问题就解决了。 
    　　第一次提醒。我是每天早上记录晨间日记的，用的台湾人那个软件，morningdiary，软件开始有个界面，我上面写了些自己想养成的习惯，每天看一下，设想下什么情况会用到这种情况。这是用到了一个心理建设的作用，就类似运动员在训练时，不断设想自己是在正式的比赛那样子。里面其中一条就是记录时间的具体流向。 
    　　第二次提醒。晨间日记里我设了个成功日志，每天记录五件成功的事，里面记上一笔自己记录了时间。一是对自己肯定，二是又在潜意识里重复强调了下记录时间） 
    　　 1.2他的日记很简短，只记和自己工作或自身相关的事。国家大事在上面基本没有反应。--记录所用语句很短，只记下开始时间，结束时间，尽量少的句子记下做过的事。比如：10:00-10:20，阅读《奇特的一生》。还有就是记录工具便于携带，便于记录的问题。我目前是用一张A4纸进行记录） 
    　　 每天临睡前进行时间统计。计算时间花在什么地方了，花了多少。最后算出基本消耗时间。每天合计第一类的工作时间。（他每天的统计，结算，详细到了无情的地步，什么也不隐瞒，什么也不缩小。） 计算的是纯时间，即刨除工作中的任何间歇。毛时间就是用在这项工作上的所有时间，包括纯时间和休息时间。 
    　　以下，就是柳比歇夫的日记结构： 
    　　“乌里扬诺夫斯克。一九六四年四月七日。分类昆虫学（画两张无名袋蛾的图）——三小时十五分。鉴定袋蛾——二十分（1.0） 
    　　附加工作：给斯拉瓦写信——二小时四十五分（0.5）。社会工作：植物保护小组开会——二小时二十五分。 
    　　休息：给伊戈尔写信——十分；《乌里扬诺夫斯克真理报》——十分；列夫•托尔斯泰的《塞瓦斯托波尔纪事》——一小时二十五分。 
    　　_____________________________________________ 
    　　基本工作合计——六小时二十分。” 
    　　“乌里扬诺夫斯克。一九六四年四月八日。分类昆虫学：鉴定袋蛾，结束——二小时二十分。开始写关于袋蛾的报告——一小时五分（1.0）。 
    　　附加工作：给达维陀娃和布里亚赫尔写信，六页——三小时二十分（0.5）。 
    　　路途往返——0.5。 
    　　休息——剃胡子。《乌里扬诺夫斯克真理报》——十五分， 
    　　《消息报》——十分，《文学报》——二十分；阿•托尔斯泰的《吸血鬼》，六十六页——一小时三十分。听里姆斯基-柯萨科夫的《沙皇的未婚妻》 。 _____________________________________________ 基本工作合计——六小时四十五分。” 
    　　 --每天小结，睡前，纯时间的工作统计，总类统计，分类统计。 
    　　 
    　　 
    　　 2.每月小结，将这月第一类工作时间，第二类工作时间分别合计出来。然后是第一，二类的工作的详细的一览表。借助图和表的形式。 
    　　--每月小结，详细统计这月中的时间消耗。模式：总类时间，分类时间，详表。 
    　　 第一类的非常详细，第二类的同样非常详细。 
    　　 3.年终，根据月小结做份年度总结，列出一览表，旁边注着数字，又是加又是乘。要求进行自我分析、自我研究，效率有什么变化，为什么? 
    　　 年度总结篇幅巨大，很详尽。什么记录都有。看了多少书，什么书，各国文字的文艺作品看了多少等。 
    　　 即使月小结中已详细记录，年度总结中也再统计一遍。把所有干了的，读了的，看了的统统收集到一起，加以计算，分门别类。一年来的工作和休息-简直什么事都要结算累计。例：娱乐-六十五次。接着列清单，列举看过的戏、电影、听过的音乐会、参观过的展览会 
    　　 年度总结有个欠债的账单，列着每月看完的书留下的尾巴。每年重复一次，没有减少。 
    　　 每份小结、总结的末尾都注明了他们的代价-花了多少小时多少分钟。 
    　　 
    　　 柳比歇夫是统计高手，他的方法应该是借鉴了统计学中的一些方法，我目前还没有看统计学相关知识，不过感觉，应该了解下相关知识，在统计总结时会起到更好的效果。 
    　　 看到有网友用excel做统计总结，不错的主意，自由定制性很强。我刚想到用家财通记金钱的软件来记录时间消耗，还在试验阶段，不晓得效果咋样。呵。我把时间消耗去向先分成两个主类：精力积累和精力消耗。精力积累又分为基本活动和磨刀之举。基本活动包括睡觉，吃饭；磨刀之举包括健身，小憩等。还不成熟，有待完善。 
    　　 
    　　五、有关计划的部分 
    　　 计划有月计划，年计划，五年计划。 
    　　 月计划 
    　　先是通过时间统计法，了解到自己每天，每月能用于工作的时间有多少，以此为标准容器；通过时间统计法，还了解到自己做每样工作需要消耗的时间，于是以这两个标准，安排工作和活动。 
    　　 每天分为必须活动，非必须活动。睡觉，吃饭、这是必须的标准活动。一般约消耗十一二个小时；非标准活动，即办公、学术工作、娱乐等，约占十二至十三小时，这是毛时间。纯可利用时间是十小时，分成三个单位，或六个半单位。根据自己身体的节律，精神状态去安排工作、活动进行计划安排。 
    　　 这样每月预算三百小时。总结、计划占百分之一，顶多百分之二，即三到六个小时。 
    　　 计划就是挑时间，规定节律，使一切各得其所。 
    　　 用去的时间，应该同他从事的工作相称（我觉得是说时间花费的多少和工作的重要，紧急程度相符） 
    　　 需要高深学识的工作，一天至多干七八小时。 
    　　 除最富于创造性的第一类工作，所有规定的工作量都竭力完成。 
    　　第一类工作包括中心工作（写作、搞研究）和例行工作（看参考书、做笔记、写信等）。 
    　　第二类工作包括做学术报告、讲课、开学术讨论会、看文艺作品，不属直接科研工作的活动都包括在内。 
    　　（第一类工作和第二类工作的的分类方法，应该是以他要达到的生物学目标为标准） 
    　　 年计划 
    　　 总结完上一年，就该制定下一年计划了。下一年计划是根据柳比歇夫提出的任务大致安排的。 
    　　 五年计划 
    　　 除年度计划，他把一生时间，制定成一个个五年计划。每过五年，把度过的时间和干过的事分析一通，做个总的鉴定。 
    　　 做月计划，年计划，五年计划，总结时比对完成情况，原因是什么。 
    　　 
    　　 
    　　 
    　　六、柳比歇夫的读书方法 
    　　 写很多东西，备而不用。（写的过程就是整理自己思路的过程，就像《你的知识需要管理》中介绍的，要去写出来，与人共享） 
    　　 读的慢。（但由于做摘要，所以不容易忘记） 
    　　 不太了解的书，尽量做摘要。重要的论著，摘要详尽；最重要的论著，要写个提纲，评论性简介。 
    　　 读的东西很多，很杂。反映出来就是柳比歇夫即是某个领域的专家，又是个杂家。 
    　　 
    　　 
    　　七、柳比歇夫的分类方法 
    　　 他用各种各样的体系，把生活安排的井井有条。保管资料的体系，通信的体系，保存照片的体系。 
    　　 凡他碰到的东西，他都想加以分类，把他们相同和相异的程度确定下来。（相同和相异是分类的标准） 
    　　 很多科学家认为，事务性的工作并不是分散精力，而是利于创造的一项条件（条理清楚了，利于大脑摆脱杂事的束缚，集中精力到当前工作中。有点gtd的味道） 
    　　 他对自己的文件进行分类，装订成册，信件、手稿都用打字机重新打过。把形形色色的杂志中需要的文章另行分类，装订成册。书籍，特别是杂志上的单篇文章，如果不编入系统的体系中，往往就会湮没在浩瀚的藏书中。 
    　　 通过目录卡片，登记自己收藏的文章、书籍和小册子。目录卡片有个总的索引。 
    　　 柳比歇夫把事务性工作看成是休息，是享受 
    　　 他做这项工程浩大的工作是出自他的需要，出自工作的需要。在需要的情况下，人什么都能学会。没鞋穿，就用树皮编成鞋。 
    　　 
    　　八、柳比歇夫根据自己的工作和身体情况，总结的几条规则 
    　　 不承担必须完成的任务 
    　　 不接受紧急的任务 
    　　 一累马上停止工作休息 
    　　 不同内容书籍交替着看 
    　　 睡的多，一天十小时左右 
    　　 累人工作和愉快工作结合在一起 
    　　 这几条守则是按他自己生活和身体的特点拟定的。他研究自己工作能力的心理特点，研究最适合自己工作能力的日常生活制度 
    　　 一切服从于生物学，凡是无助于此的，一概置之不理。 
    　　 时间是最宝贵的财富，不能乱用到怄气上，不能乱用到竞争、角逐和满足虚荣心上 
    　　 
    　　 
    　　 
    　　九、柳比歇夫对待时间的态度 
    　　 柳比歇夫热爱时间，珍惜时间，把它看成是进行创造的条件 
    　　 他不但尊重和热爱现在，而且尊重和热爱过去。他强烈感受到时间与时间之间的联系 
    　　 他为自
  #+end_example
