#+TITLE: 爱上双人舞
#+AUTHOR: DarkSun
#+EMAIL: lujun9972@gmail.com
#+OPTIONS: H3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* 恋爱婚姻关系中的相关概念与技巧
** 爱一个人，就有了爱一个人的义务，但是并不意味着有了他爱你的权利
** 老是抱怨对方不好的人，爱上的是心里的一副相片，而不是哪个活生生的人。
   所以，内心的照片也许可以用做开始找对象时的标准，但是，要懂得把它放下，特别是当已经遇上一个让自己满意及感觉很好的人时。这个时候，也许应该把照片放在一旁，只凭那个人本身的条件 ( 而不是符合照片多少 ) 冷静认真地思考一下:那些条件，是否能够在漫长的岁月里和自己 配合，共同创造成功快乐的人生。
** 婚姻的5个致命伤
   1. 坚持我是对的
      * 一个人如果没有准备放弃一些自己的想法，和准备接受一些与自己不同的看法，是无法成功地与任何人共同生活的
      * 除了两三点绝对不能放松的要求外( 这些应是不惜离婚也要坚持的东西) ，在所有其他的事上马上降低 你的标准。就算对方的做法不是最好，只能符合最低的标准便接受。这是给对方空间和爱的表现。尤其是当配偶在他人面前的表现不符合你的理想的时候，你应给他/她支持而不是做第一个批评的人。
   2. “托付心态”
      * 正确的心态应该是，我有足够的能力照顾自己的人生，你也有足够的能力照顾自己的人生，而两人在一起的时候，更能增添额外的火花，产生一些独自一人不能获得的成功快乐
   3. 不愿意讨论，对方与自己的内心感觉
      * 不要把情绪压制在心里，多与对方沟通沟通
      * 把情绪说出来与把情绪发泄在他人身上是俩回事。一个人有情绪，同时自知有情绪，能够与别人讨论自己的情绪状况，是思想成熟的表现。
   4. 维持表面的和谐
      * 夫妻之间应该建立一种就矛盾冲突进行讨论的机制。这里说的是平行静气得讨论，双方都给对方同等地位、相同的权利。
       	这个机制应该能够让两人平静地说出自己不能接受对方怎样的语言行为，并且商定如何解决。
   5. 不知如何处理冲突
      * 所谓有效地处理冲突，并不是指使冲突一定如你所愿解决（因为你不能控制另一个人），而是能够清楚地表达自己、了解对方的看法、认识所有的选择，而且过程是平静和理智的。
** 共同价值与共同信念
   两个人对事情的看法（应该怎样）一致，就是共同信念；而两个人追求的价值（对事情里什么重要，想因此得到些什么）却无须一致，对方最求这些价值，自己可以接受，便是共同价值
** 爱往往使两人同住在一间房子里，但是，能否愉快地一起生 活，几乎与他俩之间有没有爱没有必然关系
   快乐地生活 在一起需要一份“ 爱 ”以外的心态，再加上一定的技巧。欠缺了这两点，爱只会驱使一个人去忍受和原谅对方在共同生活里造成的痛苦和伤害。越多的爱便导致越多的忍受，承受越多的痛苦和伤害。更可怜的是如果对方也有一份很深的爱，对方会因为看到自己的痛苦而亦会感到痛苦、内疚、无力。这样的“ 互馈机制 ” 会把两个人推向深渊。心理治疗上称之为“相互依赖” 
** 一对男女要获得美好恒久的爱情，直至共同走向婚姻，需要另个条件
   1. 对对方没有要求
   2. 两人都做到自己照顾自己的人生
* 必须得成长
** 成长是一个过程
   在这个过程中，需要培养出独立的思考、决策能力，养成良好的行为习惯，积累成长的经验，这其中包括成功的经验，也包括失败的经验。
** 36项心理素质
   1. 思想态度
      对所有的人、事、物都抱着 “ 三赢 ”
      常怀着 “ 我如何能做得更好 ? ” 的态度
      经常思考如何提升自己的能力
      在困难时能够刻苦坚持
      灵活
      有创意，富于幽默感
   2. 学习提升
      对很多的事物都有兴趣
      有效地运用内感官
      想掌握有关的学问和知识
      多问 “ 为什么 ” 和 “ 如何，，
      不满足于简单答案而想了解更多
      有尝试的勇气，可以付诸行动
   3. 自我管理
      自己可以做的不假手他人
      白己想要的自己去争取、创造
      以自己能够照顾自己为荣
      爱护和尊重自己
      有效的时间管理
      有效安排自己要做的事
   4. 人格发展
      认识自己拥有和未有的能力
      能够改变妨碍自己成长的信念
      具备有效思维的能力
      肯定自己拥有与别人一样的资格
      尊重每一个人的界限
      认识和珍惜自己能够做到的对世界的影响
   5. 情绪职能
      明白情绪其实是来自本人的信念系统
      接受自己的情绪
      具有管理自己情绪的能力
      关心别人的感受
      明白负面情绪的正面意义
      能够接受 “ 失去 ”
   6. 人际沟通
      有效表达白己的意思
      能够主动与人接触
      接受跟自己不同的人
      能够妥善处理别人的不当言行
      能够面对公众说话
      良好的谈判辩论能力
** 埃里克.埃里克森的“成长的五个阶段”
   21岁之前五个阶段的主题成长需要是 :
   1. 第一个阶段 :1 岁以前 — 信任与不信任
      若在这一阶段孩子的需要得到满足，孩子会觉得生长在一个安全的地方。长大后，会是一个开朗及信任别人的人。
      若家长未能在这一阶段满足孩子的需要，孩子会觉得生长在一个不安全的地方。
   2. 第二个阶段 :2 岁一 3 岁 — 自主与羞愧
      孩子的需要或行为 :孩子开始学习如何控制自己的生理机能，注意到身休的能力及限制( 如控制大小便 ) 。
      若这一阶段孩子的需要得到满足，受到家长支持及尊重，他会获得充满自主能力的感觉，觉得他自己对这个世界 有一份影响力。
      若家长未能在这一阶段满足孩子的需要，孩子在成长中得不 到鼓励，或受到恶意的批评及嘲笑，尤其是在他尝试学习如何控制大小便的过程中，他很容易产生害羞及羞愧的感受。
   3. 第三个阶段 :4 岁一 5 岁 — 主动与内疚
      孩子的需要或行为 :喜欢幻想、创造及按照白己的主意行事 ;发展出主动性。
      若在这个一阶段孩子的需要得到满足，受到家长的支持，他会常常说出他的想法，表达他的情绪，并且他会发展出一份健康的好奇心。
      若家长未能在这一阶段满足孩子的需要，家长不支持他，反而因他做出的尝试而处罚他，他会觉得内疚、有犯罪感，因而停止他的主动性，或者秘密地进行。
   4. 第四个阶段 :6 岁一 11 岁 — 勤勉与自卑
      孩子的需要或行为 : 这一阶段的孩子，会开始与别人竞争及比较。
      若在这一阶段孩子的需要得到满足，老师和家长鼓励孩子学 习并表示孩子与其他孩子有同样的能力，孩子将会受到激励而变得有活力。
      若家长未能在这一阶段满足孩子的需要，经常严厉地批评或 忽略了孩子，孩子会不信任自己，或者不会自觉地做事。他会产生不配做某件事 或不及别人的感觉。
   5. 第五个阶段 :12 岁一21岁 - 对身份与角色的困惑
      孩子的需要或行为 :找出怎样适应世界的方法 ;接受自己生理上的变化 ;界定自己对于异性的身份 ;界定在同性和同辈里的身份 ;确定人生应怎样过。
      若在这一阶段孩子的需要得到满足，允许他去探索自己的梦 想及感觉，尝试新的想法，他会发展成为一个接受自己的人。
      若家长未能在这一阶段满足孩子的需要，不支持他，又不引 导他去探索，而只是过早地强逼他进入某一个角色，他会形成反叛的个性或者变成一个轻浮的人。
* 八大婚姻问题
  1. 自己提升了，而对方尚在原来的地方
  2. 对方失去吸引力
     * 想要婚姻关系不会发展出“对方失去吸引力”的问题，需要从新婚开始便有良好的沟通，并且懂得培养出共同的爱好和活动
  3. 对方不了解自己
     * 真正相处之道不是“了解”而是给予一方“空间”。我不了解，但是我接受你是这样的，并且在接受的同时找出能够愉快相处的方式
     * 不要相信“顺其自然”的方式能够使两人关系更好。“顺其自然”是任由流水把两人拉远，直到远的无法联系才突然觉醒。
     * 不要因为误会分手，而应该是因为了解（无法在一起的原因）才分手
  4. 意见不合
     * 两人之间有没有保持足够的沟通
     * 两人有没有准备放弃一些个人的信念价值，建立更多的共同信念和共同价值
  5. 有了第三者
  6. 因为孩子或工作，忽略了对方
     * 夫妻间的关系比他们跟汉子的关系更为重要。夫妻是一个系统，孩子是后来加入的，因此在这个系统里的地位比父母两人的低
  7. 移民或工作使我们两地分隔
  8. 家中的老人使我们关系紧张
     * 如果还没有充分成长，没有准备好离开父母的系统去建立自己的系统，请不要做结婚的决定，待自己内心把这件事搞清楚之后再结婚。不然的话，只会扼杀一份珍贵的感情关系和一个可能是很好的婚姻对象。
     * 每个系统都有一些与别的的系统不同的事情和规则，系统内的人需要遵守，系统外的人需要尊重
* 如何能维持恩爱和谐
  1. 两人要经常进行诚挚的对话，让对方了解自己的感受。就像跳舞的舞伴一样，两人不断地通过感觉调整动作对对方进行配合。
  2. 良好有效的谈话沟通，需要以下的主动因素
     * 想沟通、在于对方的存在、建立平等的态度立场，不要心不在焉
     * 对方的情绪状态能支持一次良好的沟通
     * 听到对方表面的立场，想一想是否跟自己的一致。假如是的，马上给予肯定。
     * 加入对方说的跟自己的立场不符，设计几条跟的居住，每一条都要对方有“是的”的回应，之后再说出自己的看法
     * 找出对方立场所追求的意义、价值、感觉。从中找出你可以接受的内容，给予肯定，表示接受，然后引导对方去找出其他选择
     * 加入过程中任何一方有负面情绪出现，以最快、最简单的方式终止谈论，避免造成大的负面经验记忆。然后运用处理情绪的技巧去帮助自己或者对方
     * 检讨思考，找出可以改善的地方，并在适当的实际，再做沟通
  3. 没对配偶都应该有留给自己的时间，留给对方的时间，和与众人一起的时间
     * 给对方的时间，就是陪伴对方去做他喜欢的事
  4. 两人沟通的技巧
     * 要谈就要有诚意地谈
       无论面对任何情况，只要当时不像沟通就有不沟通的权利。但是当时不想沟通，应该给对方什么时候沟通的承诺
     * 支持配偶，就算他/ 她做的并不完美
       当总不要说配偶错了、当两人独处时再谈
     * 避免批评抱怨对方
     * 避免嘲笑伴侣
       许多嘲笑的动机本来只是开玩笑，但言者无心，听者有意
     * 避免喋喋不休
     * 避免盘根问底
     * 避免讨价还价
  5. 建立两人的共同目标和未来远景
     * 明确时间、地点、人物及事件
     * 必须是凭自己的力量可以做到的。
     * 目标能给自己足够的喜悦
     * 符合三赢（你好、我好、大家好）的要求
* 当婚姻已经破裂
  1. 如何把对孩子的伤害减到最低
     * 尽量对孩子坦白
       坦诚地告诉孩子你俩有意见不一致的事情，告诉孩子这是正常的现象，没有两个人能够在所有的事情上意见一致的。坦诚地告诉孩子与另一方吵架后自己的不开心，但是 *绝对不要在孩子面前批评、责骂对方*
     * 绝对不把痛苦归咎与另一方或孩子
     * 向孩子保证、无论发生什么事情，父母对孩子的爱都不会改变
     * 保留对方与孩子见面甚至同住的权利
     * 安排一些时间、三人共同在一起
* 情绪与压力管理
  1. 压力的产生就是提醒人们需要面对威胁，消减压力最好的方法是运动，运动可以消除累积在身体里的能量，让身体恢复平静的状态
  2. 排解他人的情绪
     1) 请对方说出身体或情绪上的感受
     2) 找出事情中可以接受的地方，对之加以语言上的肯定
     3) 向对方指出事情中他需要改变的地方 但你不可以直接地说出对方的不对，而是站在他得角度指出情绪对他得不利影响
     4) 帮助找出解决方案
