#+TITLE: 认知盈余
#+AUTHOR: DarkSun
#+EMAIL: lujun9972@gmail.com
#+OPTIONS: H3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

* 新时代的规则
  1. 新工具所提供的机会越多,任何人能够从之前社会形态推断未来的可能性也越小. 由此可以推断出第2点
  2. 要从一个工具中创造出最大的价值,靠的并不是总体规划或者跨越式发展,而是连续不断的尝试和错误. 对任何一个社会来说,在这样一种转变中要面对的关键问题是,如何充分利用这个过程.
  3. 工作小组的管理难度通常会随着规模的增加而增加,因此任务的关键不是命令别人作某事,而是创造一种让人们愿意去做事的环境.
* 认知盈余的成功要素
  * 从小做起

    为了拥有一个大型而优秀的系统,最好从一个小型而优秀的系统做起,并且努力使他变大变强,这样做远远好过从一个大型却平淡无奇的系统做起并努力改进.
  * 把握用户的参与动机

    在参与动机方面,社会价值往往要比个人价值更重要.
  * 设计宽松的使用规则

    太过明确的使用规则会丢失大笔的潜在用户. 让用户自由的去使用,他们往往能够以意想不到的方式来使用你提供的工具
  * 快速学习客户的新用法,根据用户不断带来的意外快速调整.
* 群体的特征
** 群体规模
   如果群体足够大，则不可预知的可以变得可以预知。
　　
　　一个群体该被当做个体的集合还是单一的群体来认识？――都是。
　　
　　群体行动能力减弱的特征：配对、对某物过度赞美或崇拜、过分关注外界威胁（很可能是臆想的威胁）。在外界威胁较大的时候，群体内部倾向于推崇比较偏执的领导人（擅长识别外在威胁），从而在群体内部形成一种令人愉悦的团结感，无论所谓的威胁是否真实存在。
　　
** 如何打造卓越的社群或团队？
   1. 公开感谢所有提供帮助的人
   2. 社会感染――传播正向偏差
   3. 一个追求共同目标的群体必须保证自己的高效，也要保证内部成员的满足
   4. 大多数群体的威胁其实来自内部――陷入仅仅满足于个人情绪需求但效率低下的行为模式中――总是回避目标。因此，必须进行自我监管。群体内化标准以后，当某群体成员偏离了这个标准，其他成员就会把该成员拉回到这个标准中――相互监督和鼓励
   5. 最大化个人自由与最大化社会价值之间产生了矛盾。完全的个人自由和完全的社会控制都不是最优选择。我们需要管理并化解这个矛盾
   6. 公共价值和社会价值的创造需要核心参与团队的承诺和辛勤努力，还要求团体进行自我治理并致力于接受那些防止他们受到无关及娱乐元素干扰的限制措施，专注于处理复杂的任务
   7. 群体需要营造出一种奖励努力工作的员工的文化。而我们需要这样的群体创造出我们需要的价值，而不仅是我们想要的价值
   8. 粉红内衣的成功来自于他们的目的并非为了所有成员，而是为了改善所有印度女性的自由。如果一个组织仅仅为自己的成员创造价值，那么早就失败了
   9. 使用那些教训来掂量对你有利的机会，而不是将它们作为一套保证成功的宝典。这些教训是：创造新机会、应对早期的成长、根据用户不断带来的意外做出调整
