#+TITLE: 高效学习tips
#+AUTHOR: lujun9972
#+TAGS: Reading
#+DATE: [2019-01-13 日 19:04]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* 位置效应
#+begin_example
  位于开头和结尾部分的信息最容易被记住,人们把这种现象称为首因效应和近因效应
#+end_example

+ 应该重点学习并不断复习学习资料中间部分的内容
+ 在做演讲或报告时应尽量把重要信息放在开头和结尾部分，有趣轻松的信息放在中间位置
+ 每学完一个单月，简短地进行总结
+ 每个单元的学习时间应尽可能地紧凑，内容应尽可能地简短，从而保证学生在学习单元时能充分利用首因效应和近因效应。
  一般每个单元的学习时间最好控制在30-45分钟，即使学习那些主题非常轻松有趣的课程，一个单元的学习时间也应该控制在30分钟内

* 启动效应
#+begin_example
  启动效应是指通过激活之前学习过的相关知识，使大脑为学习新知识做好准备。
  人们可以通过唤醒现存的相应记忆或者有针对性地提出问题，来汲取自己特别感兴趣的知识。
#+end_example

人们每次学习的时候应该明确学习主题并结合之前所学知识。这样才能激活大脑中存储的与该学习主题相关的知识。
另外，人们还应该预想一下（最好写下来）可能会遇到的问题和苦难

在课堂教学开之前准备简要的概况介绍，有助于我们更好地接受教学或讲座内容。同理，你也可以在读一本书前仔细浏览一下内容提要或前沿，以便掌握书的整体框架

* 情绪--学习的催化剂
在学习过程中，保持积极健康的情绪会达到事半功倍的效果。

可以通过听音乐、运动、读书、放声大笑等方式将情绪调整好,

学习有意义、实用性较强并且十分具体的内容，容易产生积极的情绪。

* 学习过程中的干扰效应
#+begin_example
  学习过程中的干扰效应指的是存储信息过程中出现学习内容冲突的情况，特别是在学习内容十分相近且间隔时间很短的时候
#+end_example

为了减少干扰效应对学习的抑制作用，有以下几条学习法则:

+ 在紧张的学习之后应尽可能长时间休息
+ 不要同时学习相似的内容，而应该学习完全不同的学科
+ 我们不应该同时学习很多发音相近的单词或内容及其相近的
+ 在学习新知识之前，如果对已有知识加以巩固并形成长期记忆，那么这些知识在以后的学习中会完整地呈现在你的脑海中。这些牢记在大脑中的知识不仅不会引起干扰效应，反而有利于大脑对新知识的吸收

* 蔡格尼克记忆效应
#+begin_example
  蔡格尼克记忆效应是指与已完成事情相比，人们对尚未处理完的事情印象更深刻
#+end_example

然而,蔡格尼克记忆效应能否发挥作用还取决于其他要素,它在下列几个情况能发挥较明显的作用:
+ 当人们有完成任务的内在需求时
+ 当人们认为凭借自己力量能够完成任务时
+ 当人们在时间方面没有太大压力时
+ 当人们处于不太疲倦的状态时
+ 当人们即将完成工作却被中段时（这样才能产生精神上的紧张感，如果早期被打断，则人们对工作的了解程度还不足于让蔡格尼克记忆效应发挥作用）

蔡格尼克记忆效应在以下人群中作用最为明显
+ 好胜心强的人
+ 儿童
  
* 在睡眠中巩固记忆
#+begin_example
  在特定的睡眠阶段，大脑仍然在对白天所接受的重要信息进行加工和存储，这种现象叫做“记忆巩固”
#+end_example

保证足够的睡眠时间和睡眠深度对有效学习至关重要。
另外，在睡眠中大脑还能进行知识整合，这一行为一般发生在深度睡眠阶段。

睡前将白天所学的重要内容简明扼要地复习一遍非常有必要。

* 学习受环境和状态影响
#+begin_example
  考试时人们所处的环境与平时学习的环境越接近，考试成绩越好
#+end_example

当考试形式为“自由发挥回答主观题”时，这种现象比较明显。
当考试形式为“客观题测试”时，这种现象就没那么明显了。

对于特别重要的考试，一定要了解考试环境，并且尽可能在相同环境下学习考试内容。

* 遗忘曲线

+ 在学习结束后的1-2小时内，一定要对所学内容进行复习
+ 考试前重新记一遍学习内容，并确保不会很快将其忘记
+ 将学习内容分成小块记忆要比分成大块记忆更加容易
+ 过度学习，即复习已经完全掌握的知识对减缓遗忘率并无好处
+ 从良好到优秀，要付出的努力比平庸到良好的努力多得多


