#+TITLE: 高效学习tips
#+AUTHOR: lujun9972
#+TAGS: Reading
#+DATE: [2019-01-13 日 19:04]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* 位置效应
#+begin_example
  位于开头和结尾部分的信息最容易被记住,人们把这种现象称为首因效应和近因效应
#+end_example

+ 应该重点学习并不断复习学习资料中间部分的内容
+ 在做演讲或报告时应尽量把重要信息放在开头和结尾部分，有趣轻松的信息放在中间位置
+ 每学完一个单月，简短地进行总结
+ 每个单元的学习时间应尽可能地紧凑，内容应尽可能地简短，从而保证学生在学习单元时能充分利用首因效应和近因效应。
  一般每个单元的学习时间最好控制在30-45分钟，即使学习那些主题非常轻松有趣的课程，一个单元的学习时间也应该控制在30分钟内

* 启动效应
#+begin_example
  启动效应是指通过激活之前学习过的相关知识，使大脑为学习新知识做好准备。
  人们可以通过唤醒现存的相应记忆或者有针对性地提出问题，来汲取自己特别感兴趣的知识。
#+end_example

人们每次学习的时候应该明确学习主题并结合之前所学知识。这样才能激活大脑中存储的与该学习主题相关的知识。
另外，人们还应该预想一下（最好写下来）可能会遇到的问题和苦难

在课堂教学开之前准备简要的概况介绍，有助于我们更好地接受教学或讲座内容。同理，你也可以在读一本书前仔细浏览一下内容提要或前沿，以便掌握书的整体框架

* 情绪--学习的催化剂
在学习过程中，保持积极健康的情绪会达到事半功倍的效果。

可以通过听音乐、运动、读书、放声大笑等方式将情绪调整好,

学习有意义、实用性较强并且十分具体的内容，容易产生积极的情绪。

* 学习过程中的干扰效应
#+begin_example
  学习过程中的干扰效应指的是存储信息过程中出现学习内容冲突的情况，特别是在学习内容十分相近且间隔时间很短的时候
#+end_example

为了减少干扰效应对学习的抑制作用，有以下几条学习法则:

+ 在紧张的学习之后应尽可能长时间休息
+ 不要同时学习相似的内容，而应该学习完全不同的学科
+ 我们不应该同时学习很多发音相近的单词或内容及其相近的
+ 在学习新知识之前，如果对已有知识加以巩固并形成长期记忆，那么这些知识在以后的学习中会完整地呈现在你的脑海中。这些牢记在大脑中的知识不仅不会引起干扰效应，反而有利于大脑对新知识的吸收

* 蔡格尼克记忆效应
#+begin_example
  蔡格尼克记忆效应是指与已完成事情相比，人们对尚未处理完的事情印象更深刻
#+end_example

然而,蔡格尼克记忆效应能否发挥作用还取决于其他要素,它在下列几个情况能发挥较明显的作用:
+ 当人们有完成任务的内在需求时
+ 当人们认为凭借自己力量能够完成任务时
+ 当人们在时间方面没有太大压力时
+ 当人们处于不太疲倦的状态时
+ 当人们即将完成工作却被中段时（这样才能产生精神上的紧张感，如果早期被打断，则人们对工作的了解程度还不足于让蔡格尼克记忆效应发挥作用）

蔡格尼克记忆效应在以下人群中作用最为明显
+ 好胜心强的人
+ 儿童
  
* 在睡眠中巩固记忆
#+begin_example
  在特定的睡眠阶段，大脑仍然在对白天所接受的重要信息进行加工和存储，这种现象叫做“记忆巩固”
#+end_example

保证足够的睡眠时间和睡眠深度对有效学习至关重要。
另外，在睡眠中大脑还能进行知识整合，这一行为一般发生在深度睡眠阶段。

睡前将白天所学的重要内容简明扼要地复习一遍非常有必要。

* 学习受环境和状态影响
#+begin_example
  考试时人们所处的环境与平时学习的环境越接近，考试成绩越好
#+end_example

当考试形式为“自由发挥回答主观题”时，这种现象比较明显。
当考试形式为“客观题测试”时，这种现象就没那么明显了。

对于特别重要的考试，一定要了解考试环境，并且尽可能在相同环境下学习考试内容。

* 复习是学习之母

+ 一方面，复习时不能心不在焉，不投入
+ 另一方面，复习的时间安排至关重要(记忆曲线):
  - 在学习结束后的1-2小时内，一定要对所学内容进行复习
  - 考试前重新记一遍学习内容，并确保不会很快将其忘记
+ 将学习内容分成小块记忆要比分成大块记忆更加容易
+ 过度学习，即复习已经完全掌握的知识对减缓遗忘率并无好处
+ 从良好到优秀，要付出的努力比平庸到良好的努力多得多

* 与记忆相关的学习技巧
** 自我效应
#+begin_example
  我们更容易记住与自己直接关联的信息，这是符合进化规律的。
  充分利用这一效应，尽量将自身情绪投入到学习内容中，你的学习效果和记忆效果定会徒增。
#+end_example

正确利用“自我效应”就是将自己视为学习内容中的核心部分或主要人物。

“自我效应”不仅适用于学习，还适用于教学。比如给孩子们讲解复杂例子时，不能抽象地解释，而是假设他们就出于例子中。

** 伪逻辑记忆法
#+begin_example
  我们理解了学习内容或者明白了其中的逻辑关系后，就能更长久地记忆他们，在理解的过程中还能获得乐趣。
  学习时应尽可能理解内容之间的逻辑关系。如果没有自然逻辑可循，我们可以运用伪逻辑记忆法来帮助记忆。
#+end_example

伪逻辑记忆法的基本思路是人为地为学习内容创建一种逻辑关系来帮助记忆，这就需要一定的联想。

** 在顶点位置学习
#+begin_example

#+end_example
** 在定点位置学习
#+begin_example
  几百万年来，我们的大脑在不断优化记忆力从而更牢固地记住那些与我们生存紧密相关的物体在某一区域所处的位置，这种基于所处位置来记忆物体的能力是帮助我们学习的一个重要记忆要素。
#+end_example

定点学习的基本原则是，有意识地将学习内容与某一个或某几个特定位置相关联。其分为三个步骤：

1. 在熟悉的场所（比如自己家中）选择一个地点（定位）进行学习
2. 在脑海中将知识点和地点两者相结合
3. 回忆所学习的内容，在脑海中切换不同的地点，然后回忆起对应的知识点。
** 发挥视觉图像化能力
所谓一图胜千言，我们可以用联想把抽象的信息转化为具体、形象的信息，从而有利于记忆。

** 组块化
#+begin_example
  短时记忆的容量极其有限，大约为7个组块。
  我们可以在学习是运用存储在长时记忆里的知识来组成更大的学习模块,以加速、优化并简化整个学习过程。
#+end_example

信息组件的大小取决于我们既有知识的多少。

通过组件化，我们不仅可以扩充短时记忆有限的存储容量，还可以基于相似性原则，将新的信息与存储在长时记忆中的信息紧密相连，从而减轻短时记忆存储信息的压力。

** 背诵文章的技巧
+ 通读: 对文章的整体内容有一个大概的了解，弄清全文的逻辑架构
+ 分段背诵: 将全文分成短小的段落一段一段的背诵，不要尝试一下子背一大段
+ 经常复习
+ 将不太明白的词语转换为画图
+ 用节奏分明的语调大声朗读文章
+ 讲要背诵的文章默写下来效果也很好
+ 边走边背诵
+ 在背诵过程中不时检验是否完全掌握要背诵的内容
+ 背诵时配合一些手势有助于提高记忆力

* 学习方法中的技巧
** 间隔学习优于集中学习
#+begin_example
  把一定的时间分成间隔较短的时间段进行学习效果更好，而且可以节省总学习时间。
#+end_example

长期有规律地捡个学习与集中学习相比，有很多优点:

+ 间隔学习能反复刺激大脑在两次学习之间持续对内容进行思考合理
+ 单次学习时间的缩短会增加学习动力，因为大家能估算出学习结束的时间
+ 间隔学习也是一种复习，可以加深我们对知识的记忆
** 有条理的学习
#+begin_example
  面对范围宽广的学习内容时，人们容易迷失在大量琐碎的知识点中，看不到内容的整体框架，从而出现“只见树木，不见森林”的情况。
  这样会大大降低学习效率，容易让人产生挫败感。有条理地、系统地学习就能解决这个问题
#+end_example

有条理这里有两层意思:
1. 在思想上要有条理，比如按照某个体系来进行学习
2. 养成有条理的学习习惯，比如记笔记和归纳整理文件等

所谓有条理的学习习惯指的是:
1. 记笔记:笔记可以帮助我们回忆学习的细节内容，只需要将自己最感兴趣和最重要的内容记下来即可
2. 记下问题: 一旦有不明白的地方立即记录下。如果这个问题对接下来的学习内容影响很大，就理解决绝他，否则放在后面解决也可以
3. 记笔记和记录问题的字迹要清晰
4. 使用能帮助你回忆的关键字:
5. 整理: 笔记之式微所学内容搭建一个粗略的框架，因此你一定要尽早整理笔记
6. 分析结构: 下一步是对所学内容的整体架构进行分析
** 对重点内容进行标注
#+begin_example
  标注不仅让我们复习起来更容易，而且标注的过程有助于我们理解学习材料、加强学习
#+end_example

标记时需要注意以下几点:
1. 自己对内容进行判断后进行标注，而不是别人帮你标注
2. 精简标注，而不要满篇都是标注
3. 不标注整句话，只标其中的重点词汇
4. 可以给学习内容加上批注
** 思维导图
#+begin_example
  思维导图是一种将关键词按照一定的规则画到纸上的学习方法。它有两个优点:首先，人们在绘制思维导图时会滴UI各种信息进行详尽分析；其次，我们卓越的视觉记忆力将得到很好地利用
#+end_example
** PQ5R学习法

+ 预览(Preview) :: 快速浏览全文以了解主题、结构和重点。浏览内容包括目录、标题和索引等
+ 提问(Question) :: 就浏览过的内容提一些自己感兴趣的问题
+ 阅读(Read) :: 在阅读过程中看能否找到所提问题的答案，这一步应对重点进行标注
+ 思考(Reflect) :: 对学习内容进行思考和理解，包括对新的内容进行深刻和严谨的思考，分析内容之间的关系，领会论证思路，并尽可能用大脑中已经有的类似的知识与文中案例进行比照。
+ 背诵(Recite) :: 将所学内容背诵一遍
+ 概括(Recapitulate) :: 用自己的话将材料的整体框架和重点概括一遍
+ 复习(Repeat) :: 每隔一段时间复习一次，并随时补充重要内容
** 类比法
#+begin_example
  有些复杂的学习内容很难理解，使用类比法可能有所帮助
#+end_example

面对一组类比案例时，我们都会寻找两个类比事物的共同点和不同点，还会分析这个类比的合适程度


