#+STARTUP: hidestars
#+TODO: TOFIX(F) TOCHECK(C) REFIX(R) | DONE(D) |CANCEL(N)
* 20130523总结问题
** hvps111来帐附言解析错误,报文中有附言,但是解析出来附言为空
** REFIX hvps111来帐,且业务类型为[A113]跨境支付时,费用编码和附言信息内客项在仿真系统中无法显示
   /附言依然无法显示/
** REFIX hvps111来帐,且业务类型为[A109]委托收款(划回),凭证种类跟附言信息在仿真系统中没有显示
   /附言依然没有显示/
** TOCHECK 收到普通借记回执beps128来帐,系统验签错误
   *图像数据太长*
** TOCHECK 收到普通借记beps127来帐,且业务类型为B311,系统验签错误
   *图像数据太长*
** TOCHECK 小额提交场切后,查询仿真中小额业务状态,还是已轧差状态.
** TOCHECK 在仿真做清算场次后,发现原业务还是轧差状态,并未变成清算状态
** DONE 批量代收业务发起时,点击确定按钮,没反应.javascript出错
** TOFIX 减少签存资金,可用余额没有增加
** TOCHECK 做hvps111往帐时,没有报文发送出去,在日志sndhdltst.log中有如下错误日志
   #+begin_example
     ,**********
     7686 20130523 16:19:43.237 0 #MyODBC.cpp: 564# 信息 执行SQL: select * from TB_HeadMesg where FD_Sid = '2013052316191720007045'
     7686 20130523 16:19:43.247 0 #sndhdl.cpp: 591# 错误 无此报文格式类型
     7686 20130523 16:19:43.248 0 #Storage.cpp:  44# 信息 ====================显示存储结构
     信息==================== {
     {
             "a":    {
                     "1":    {
                             "1":    {
                                     "f000": "2013052316191720007045",       /* FD_Sid */
                                     "f001": "9"     /* FD_FLAG */
                             }
                     }
             },
             "p":    {
                     "1":    {
                             "1":    {
                                     "f000": "2013052316191720007045",       /* FD_Sid */
                                     "f001": "02",   /* FD_VersID */
                                     "f002": "0000", /* FD_OrigSend */
                                     "f003": "HVPS", /* FD_OrigSendSID */
                                     "f004": "402602000018", /* FD_OrigRecv */
                                     "f005": "HVPS", /* FD_OrigRecvSID */
                                     "f006": "20130523",     /* FD_OrigSendDate */
                                     "f007": "161922",       /* FD_OrigSendTime */
                                     "f008": "-1",   /* FD_StructType */
                                     "f009": "hvps.111.001.01",      /* FD_MesgType */
                                     "f010": "2013080120000388",     /* FD_MesgID */
                                     "f011": "2013080120000163",     /* FD_MesgRefID */
                                     "f012": "3",    /* FD_MesgPriority */
                                     "f013": "D",    /* FD_MesgDirection */
                                     "f014": ""      /* FD_Reserve */
                             }
                     }
             },
             "k":    {
                     "1":    {
                             "1":    {
                                     "f001": "9999"  /*  */
                             }
                     }
             }
     }
     7686 20130523 16:19:43.248 0 #Storage.cpp:  46# 信息 ====================显示存储结构
     信息==================== }, 耗时 0.000396 秒
     7686 20130523 16:19:43.248 0 #sndhdl.cpp: 690# 信息 处理失败
     7686 20130523 16:19:43.248 0 #sndhdl.cpp: 691# 信息 beps.128.001.01 往报处理失败, 耗>
     时 0.025072 秒
     
   #+end_example
* 20130524问题汇总
** TOCHECK 收到hvps.712后,只会990,没有回713
   712的日志为:
   #+begin_example
     ,********** 
     7681 20130523 19:11:25.652 0 #zsa_mq.c:1302# 错误 接收消息失败,完成码=[1] 原因码=[2110] MQRC_FORMAT_ERROR               
     7681 20130523 19:11:25.653 0 #zsa_mq.c:1313# 信息 接收到MQ来帐 
     7681 20130523 19:11:25.653 0 #rcvhdl.cpp: 192# 信息 数据长度=[923] 
     7681 20130523 19:11:25.653 0 #rcvhdl.cpp: 193# 信息 数据内容=[{H:02402602000018  HVPS0000          HVPS20130802085236XMLhvps.712.001.01     20130802000000000009201308020000000000093U         }^M 
     {S:}^M 
     <?xml version="1.0" encoding="UTF-8" standalone="no" ?> 
     <Document xmlns="urn:cnaps:std:hvps:2010:tech:xsd:hvps.712.001.01"> 
      
       <DtlReq> 
         <GrpHdr> 
           <MsgId>2013080200000003</MsgId> 
           <CreDtTm>2013-08-02T08:52:36</CreDtTm> 
           <InstgPty> 
             <InstgDrctPty>402602000018</InstgDrctPty> 
             <InstgPty>402602000018</InstgPty> 
           </InstgPty> 
           <InstdPty> 
             <InstdDrctPty>0000</InstdDrctPty> 
             <InstdPty>0000</InstdPty> 
           </InstdPty> 
           <SysCd>HVPS</SysCd> 
         </GrpHdr> 
         <DtlReqInf> 
           <ChckngDt>2013-08-02</ChckngDt> 
           <TtlCnt>1</TtlCnt> 
           <Dtls> 
             <MT>hvps.111.001.01</MT> 
             <TxTpCd>A100</TxTpCd> 
             <SndRcvTp>SR01</SndRcvTp> 
             <PrcSts>PR04</PrcSts> 
           </Dtls> 
         </DtlReqInf> 
       </DtlReq> 
      
     </Document> 
     ] 
     7681 20130523 19:11:25.653 0 #rcvhdl.cpp: 200# 信息 报文属于二代格式 
     7681 20130523 19:11:25.653 0 #rcvhdl.cpp: 666# 信息 数据指纹=[276E2BE583010CA5DC4815190CE69B71] 
     7681 20130523 19:11:25.654 0 #rcvhdl.cpp: 693# 信息 二代报文处理 
     7681 20130523 19:11:25.655 0 #PkgCtrl.cpp: 424# 信息 解报文[cnaps]:[中国现代化支付报>文]结构开始 { 
     7681 20130523 19:11:25.655 0 #PkgCtrl.cpp:1485# 信息 解字段[head].M.[报文头数据区]=[ 126]:[02402602000018  HVPS0000          HVPS20130802085236XMLhvps.712.001.01     20130802000000000009201308020000000000093U         ] 
     7681 20130523 19:11:25.655 0 #PkgCtrl.cpp:1583# 信息 链配置[/home/cnapstst/cnaps2/etc/cnaps2head.xml]文件 
     7681 20130523 19:11:25.656 0 #PkgCtrl.cpp: 424# 信息 解报文[head]:[报文头]结构开始 { 
     7681 20130523 19:11:25.656 0 #PkgCtrl.cpp:1485# 信息 解字段[f001].M.[版本号      ]=[   2]:[02] 
     7681 20130523 19:11:25.905 0 #PkgCtrl.cpp:1485# 信息 解字段[f002].M.[报文发起人  ]=[  14]:[402602000018  ] 新值=[402602000018] - 东莞农村商业银行总行营业部 
     7681 20130523 19:11:25.923 0 #PkgCtrl.cpp:1485# 信息 解字段[f003].O.[发送系统号  ]=[   4]:[HVPS] - 大额实时支付系统 
     7681 20130523 19:11:26.133 0 #PkgCtrl.cpp:1485# 信息 解字段[f004].M.[报文接收人  ]=[  14]:[0000          ] 新值=[0000] 
     7681 20130523 19:11:26.133 0 #PkgCtrl.cpp:1485# 信息 解字段[f005].O.[接收系统号  ]=[   4]:[HVPS] - 大额实时支付系统 
     7681 20130523 19:11:26.134 0 #PkgCtrl.cpp:1485# 信息 解字段[f006].M.[报文发起日期]=[   8]:[20130802] 
     7681 20130523 19:11:26.134 0 #PkgCtrl.cpp:1485# 信息 解字段[f007].M.[报文发起时间]=[   6]:[085236] 
     7681 20130523 19:11:26.134 0 #PkgCtrl.cpp:1485# 信息 解字段[f008].M.[格式类型    ]=[   3]:[XML] 
     7681 20130523 19:11:26.134 0 #PkgCtrl.cpp:1485# 信息 解字段[f009].M.[报文类型代码]=[  20]:[hvps.712.001.01     ] 新值=[hvps.712.001.01] - 大额业务明细核对申请报文 
     7681 20130523 19:11:26.134 0 #PkgCtrl.cpp:1485# 信息 解字段[f010].M.[通信级标识号]=[  20]:[20130802000000000009] 
     7681 20130523 19:11:26.135 0 #PkgCtrl.cpp:1485# 信息 解字段[f011].O.[通信级参考号]=[  20]:[20130802000000000009] 
     7681 20130523 19:11:26.135 0 #PkgCtrl.cpp:1485# 信息 解字段[f012].M.[报文优先级  ]=[   1]:[3] - 普通 
     7681 20130523 19:11:26.135 0 #PkgCtrl.cpp:1485# 信息 解字段[f013].M.[报文传输方向]=[   1]:[U] - 行内发出 
     7681 20130523 19:11:26.135 0 #PkgCtrl.cpp:1485# 信息 解字段[f014].O.[（保留域）  ]=[   9]:[         ] 新值=[] 
     7681 20130523 19:11:26.135 0 #PkgCtrl.cpp: 455# 信息 解报文[head]:[报文头]结构完成 }, 耗时 0.479215 秒 
     7681 20130523 19:11:26.136 0 #PkgCtrl.cpp:1485# 信息 解字段[sign].O.[数字签名    ]=[   0]:[] 
     7681 20130523 19:11:26.136 0 #PkgCtrl.cpp:1485# 信息 解字段[xml].M.[XML报文数据区]=[ 785]:[<?xml version="1.0" encoding="UTF-8" standalone="no" ?> 
     <Document xmlns="urn:cnaps:std:hvps:2010:tech:xsd:hvps.712.001.01"> 
      
       <DtlReq> 
         <GrpHdr> 
           <MsgId>2013080200000003</MsgId> 
           <CreDtTm>2013-08-02T08:52:36</CreDtTm> 
           <InstgPty> 
             <InstgDrctPty>402602000018</InstgDrctPty> 
             <InstgPty>402602000018</InstgPty> 
           </InstgPty> 
           <InstdPty> 
             <InstdDrctPty>0000</InstdDrctPty> 
             <InstdPty>0000</InstdPty> 
           </InstdPty> 
           <SysCd>HVPS</SysCd> 
         </GrpHdr> 
         <DtlReqInf> 
           <ChckngDt>2013-08-02</ChckngDt> 
           <TtlCnt>1</TtlCnt> 
           <Dtls> 
             <MT>hvps.111.001.01</MT> 
             <TxTpCd>A100</TxTpCd> 
             <SndRcvTp>SR01</SndRcvTp> 
             <PrcSts>PR04</PrcSts> 
           </Dtls> 
         </DtlReqInf> 
       </DtlReq> 
      
     </Document> 
     ] 
     7681 20130523 19:11:26.136 0 #PkgCtrl.cpp:1583# 信息 链配置[/home/cnapstst/cnaps2/etc/hvps71200101.xml]文件 
     7681 20130523 19:11:26.136 0 #PkgCtrl.cpp: 424# 信息 解报文[xml]:[大额业务明细核对申>
     请报文]结构开始 { 
     7681 20130523 19:11:26.137 0 #PkgCtrl.cpp: 554# 信息 验证schema成功, 耗时 0.000785 秒
     7681 20130523 19:11:26.137 0 #PkgCtrl.cpp: 565# 信息 解析XML报文成功, 耗时 0.000175 >秒 
     7681 20130523 19:11:26.137 0 #PkgCtrl.cpp:1485# 信息 解字段[f001].M.[报文标识号          ]=[  16]:[2013080200000003] 
     7681 20130523 19:11:26.138 0 #PkgCtrl.cpp:1485# 信息 解字段[f002].M.[报文发送时间        ]=[  19]:[2013-08-02T08:52:36] 新值=[2013-08-02 08:52:36] 
     7681 20130523 19:11:26.344 0 #PkgCtrl.cpp:1485# 信息 解字段[f003].M.[发起直接参与机构    ]=[  12]:[402602000018] - 东莞农村商业银行总行营业部 
     7681 20130523 19:11:26.565 0 #PkgCtrl.cpp:1485# 信息 解字段[f004].M.[发起参与机构        ]=[  12]:[402602000018] - 东莞农村商业银行总行营业部 
     7681 20130523 19:11:26.790 0 #PkgCtrl.cpp:1485# 信息 解字段[f005].M.[接收直接参与机构
         ]=[   4]:[0000] 
     7681 20130523 19:11:27.010 0 #PkgCtrl.cpp:1485# 信息 解字段[f006].M.[接收参与机构        ]=[   4]:[0000] 
     7681 20130523 19:11:27.010 0 #PkgCtrl.cpp:1485# 信息 解字段[f007].M.[系统编号            ]=[   4]:[HVPS] - 大额实时支付系统 
     7681 20130523 19:11:27.010 0 #PkgCtrl.cpp:1485# 信息 解字段[f008].O.[备注                ]=[   0]:[] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f009].M.[对账日期            ]=[  10]:[2013-08-02] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f010].M.[对账业务类型数目
         ]=[   1]:[1] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1701# 信息 解分片[对账清单]结构开始 { 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1792# 信息 解循环[d]-[1]:[1]结构开始 { 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f002].M.[报文编号        ]=[  15]:[hvps.111.001.01] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f003].M.[业务类型编码    ]=[   4]:[A100] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f004].M.[发送、接收标志  ]=[   4]:[SR01] 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1485# 信息 解字段[f005].M.[处理状态        ]=[   4]:[PR04] - 已清算 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1805# 信息 解循环[d]-[1]:[1]结构完成 }, 耗>
     时 0.000462 秒 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp:1722# 信息 解分片[对账清单]结构完成 }, 耗时 0.000556 秒 
     7681 20130523 19:11:27.011 0 #PkgCtrl.cpp: 455# 信息 解报文[xml]:[大额业务明细核对申>
     请报文]结构完成 }, 耗时 0.875483 秒 
     7681 20130523 19:11:27.012 0 #PkgCtrl.cpp: 455# 信息 解报文[cnaps]:[中国现代化支付报>
     文]结构完成 }, 耗时 1.357656 秒 
     7681 20130523 19:11:27.016 0 #MyODBC.cpp: 564# 信息 执行SQL: update TB_Serial set FD_No = FD_No + 1 where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.023 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.028 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.033 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_HeadMesg(FD_Sid,FD_VersID,FD_OrigSend,FD_OrigSendSID,FD_OrigRecv,FD_OrigRecvSID,FD_OrigSendDate,FD_OrigSendTime,FD_StructType,FD_MesgType,FD_MesgID,FD_MesgRefID,FD_MesgPriority,FD_MesgDirection,FD_Reserve) values ('2013052319112720007134','02','402602000018','HVPS','0000','HVPS','20130802','085236','XML','hvps.712.001.01','20130802000000000009','20130802000000000009','3','U','') 
     7681 20130523 19:11:27.034 0 #MyODBC.cpp: 564# 信息 执行SQL: select count(*) from TB_HeadMesg where FD_Sid='2013052319112720007134' and FD_OrigSend='402602000018' and FD_OrigSendDate='20130802' and FD_MesgID='20130802000000000009' 
     7681 20130523 19:11:27.043 0 #rcvhdl.cpp: 751# 信息 验签 
     7681 20130523 19:11:27.043 0 #rcvhdl.cpp: 790# 信息 组装的签名=[] 
     7681 20130523 19:11:27.046 0 #rcvhdl.cpp: 844# 信息 非签名报文 
     7681 20130523 19:11:27.050 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_HVPS712(FD_Sid,FD_MsgId,FD_CreDtTm,FD_InstgDrctPty,FD_InstgPty,FD_InstdDrctPty,FD_InstdPty,FD_SysCode,FD_Rmk,FD_CheckDate,FD_TotalCount)  
                     values('2013052319112720007134','2013080200000003','2013-08-02 08:52:36','402602000018','402602000018','0000','0000','HVPS','','2013-08-02','1') 
     7681 20130523 19:11:27.062 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_HVPS712Lis(FD_Sid, FD_MsgId,FD_MesgType, FD_TranTypeCode, FD_SndRcvTp, FD_ProcSts)  
                     values('2013052319112720007134','2013080200000003','hvps.111.001.01','A100','SR01','PR04') 
     7681 20130523 19:11:27.065 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_RecvMesg(FD_Sid,FD_SendDate,FD_MesgType,FD_MsgId,FD_SendBank,FD_RecvBank,FD_SendNum,FD_CerFlag,FD_FLAG,FD_990msg) values ('2013052319112720007134','2013-05-23T19:11:27','hvps.712.001.01','20130802000000000009','402602000018','0000',0,'0','0','HV1I0000') 
     7681 20130523 19:11:27.067 0 #rcvhdl.cpp: 911# 信息 ***********自动应答990报文开始 { 
     7681 20130523 19:11:27.068 0 #MyODBC.cpp: 564# 信息 执行SQL: update TB_Serial set FD_No = FD_No + 1 where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.070 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.072 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='##' and FD_BankCode='############' 
     7681 20130523 19:11:27.077 0 #MyODBC.cpp: 564# 信息 执行SQL: update TB_Serial set FD_No = FD_No + 1 where FD_FdID='02' and FD_BankCode='0000' 
     7681 20130523 19:11:27.079 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='02' and FD_BankCode='0000' 
     7681 20130523 19:11:27.081 0 #MyODBC.cpp: 564# 信息 执行SQL: select FD_No from TB_Serial where FD_FdID='02' and FD_BankCode='0000' 
     7681 20130523 19:11:27.086 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_HeadMesg(FD_Sid,FD_VersID,FD_OrigSend,FD_OrigSendSID,FD_OrigRecv,FD_OrigRecvSID,FD_OrigSendDate,FD_OrigSendTime,FD_StructType,FD_MesgType,FD_MesgID,FD_MesgRefID,FD_MesgPriority,FD_MesgDirection,FD_Reserve) values ('2013052319112720007135','02','0000','HVPS','402602000018','HVPS','20130523','191127','XML','ccms.990.001.02     ','2013052320001519','20130802000000000009','3','D','') 
     7681 20130523 19:11:27.088 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_CCMS990(FD_Sid,FD_OrigSender,FD_OrigSendDate,FD_MesgTyp,FD_MsgId,FD_MsgRefId,FD_MsgPrcCd) values ('2013052319112720007135','402602000018','20130802','hvps.712.001.01','20130802000000000009','20130802000000000009','HV1I0000') 
     7681 20130523 19:11:27.089 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_SendMesg(FD_Sid,FD_SendDate,FD_MesgType,FD_MsgId,FD_SendBank,FD_RecvBank,FD_SendNum,FD_FLAG,FD_990msg,FD_OrgMesgType,FD_OrgMsgId) values ('2013052319112720007135','2013-05-23T19:11:27','ccms.990.001.02','2013052320001519','0000','402602000018',0,'0','HV1I0000','hvps.712.001.01','20130802000000000009') 
     7681 20130523 19:11:27.093 0 #rcvhdl.cpp: 930# 信息 ***********自动应答990报文完成 } 
     7681 20130523 19:11:27.093 0 #rcvhdl.cpp: 959# 信息 处理完成 
     7681 20130523 19:11:27.093 0 #rcvhdl.cpp: 960# 信息 hvps.712.001.01来报处理成功, 耗时 1.439956 秒 
     7681 20130523 19:11:27.103 0 #rcvhdl.cpp:1011# 信息 保存文件=[2013080200000003_402602000018.dat] 
      
     ,********** 
     
   #+end_example
** DONE 在哪可以查看自由格式?
   无法查询自由格式 
** DONE 在做ccms.310往帐时,收到了ccms.311来帐,并且已经返回了900报文,但是页面还是一直在等待ccms.311,一直到超时
* DONE 20130527问题汇总
** DONE 数据查询-通用签名信息业务查询中,输入发起/接受直接参与机构后再点击确定,会显示"对不起,系统忙!请重新登录"的错误页面
* 20130528问题汇总
** TOFIX 发起"客户发起普通贷记业务"时(基本上所有的小额汇兑业务都有这个问题,有些以前测试是正常的,现在也有这个问题了),明明有收到990报文,但是依然会报"发送小额支付系统报文 客户发起普通贷记业务 2013072620000568,等待接收行回执超时"的信息.
** TOCHECK 仿真运行一段时间后会出现卡死的现象,需要重启才能继续做业务.
   *后台数据库锁太少了*
** 现阶段仿真是直接与我们行内系统相连的.要如何配置,才能使得仿真与PMTS连接.
* 20130529问题汇总
** TOFIX 小额往来测试数据查询-来帐查询时,标题显示的是"小额往帐信息查询",且查看"已轧差"业务状态的明细时,报"对不起，系统忙！请重新登录! "错误
* 20130530问题汇总
** TOFIX 收到HVPS111报文后,从大额来帐信息查询中,附言信息显示的是备注信息,无地方显示备注信息
* 20130531问题汇总
** TOFIX 仿真hvps.111.001.01托收承付（划回）来帐没有附言信息显视，接收的附加域信息显视不全
** TOFIX 仿真hvps.111.001.01 银行汇票来帐，没有任何附加域来帐信息显视，例如,msgid为2013081800000016的报文
** TOFIX 仿真hvps.111.001.01 银行本票来帐，没有任何附加域来帐信息显视，例如,msgid为2013081800000017的报文
** TOFIX 仿真hvps.111.001.01商业汇票来帐，没有任何附加域来帐信息显视，例如,msgid为2013081800000018的报文
** TOFIX 所有的附言部分都显示了备注的信息,所有的备注信息都没地方显示出来
** TOFIX 从仿真发起一笔  客户发起汇兑业务报文<hvps.111.001.01>   银行汇票 【A203】 附加数据域中 实际结算金额 异常；正常情况下实际结算金额应该与业务金额等同，多余金额等于出票金额减去实际结算金额,例如msgid='2013081820000783'的报文
** TOFIX 仿真[hvps.111.001.01]客户发起汇兑业务， 业务类型 [A113]跨境支付 来帐，没有附言信息。
** TOFIX 仿真[hvps.111.001.01]客户发起汇兑业务 业务类型: [A101]公益性资金汇划 来帐，没有附言信息显视。
** TOFIX hvps.112.001.01 金融机构发起汇兑业务报文，退汇来帐信息中，没有退汇原因信息要素记录
* 20130603问题汇总
** TOFIX ibps.106报文来账,验签不过,例如msgid='4026020000182014010900000059'的报文
** TOFIX ibps.104报文来账,验签不过,例如msgid='4026020000182014010900000058'的报文,缺少业务拒绝码
** TOFIX 收到beps121报文来账,报重复报文,丢弃,但是不应该是重复报文的,msgid='2013072920000011'.
** CANCEL [beps.121.001.01][A110]托收承付（划回）查询明细中,附加域少了原托金额,支付金额和多付金额
   *有些附加域就是没有显示也没关系*
** TOFIX 收到ibps105报文后,日志报"调用UnpackStructNode失败",没有发送回应报文,参见msgid='4026020000182014010900000055'的报文
** TOFIX 收到beps103报文后,日志报"错误 解字段[f026]:[认证信息                    ]#{必选项}#不能为空","调用UnpackStructNode失败",参见msgid='4026020000182014010900000042'的报文和msgid='4026020000182014010900000052'的报文
* DONE 20130604问题汇总
** DONE 如何配置一代报文的密押配置,现在一直报密押错误
* 20130605问题汇总
** TOFIX 仿真发送hvps111业务,日志报错"无此报文格式",而且奇怪的是,日志后显示的是"信息 beps.121.001.01 往报处理失败",更奇怪的是,在查询大额报文状态时该笔报文为清算状态,参见msgid='2013081820000866'的报文
   #+begin_example      
     3991 20130605 09:18:53.746 0 #MyODBC.cpp: 564# 信息 执行SQL: select * from TB_HeadMesg where FD_Sid = '2013060509182820013187'
     3991 20130605 09:18:53.763 0 #sndhdl.cpp: 591# 错误 无此报文格式类型
     3991 20130605 09:18:53.763 0 #Storage.cpp:  44# 信息 ====================显示存储结构信息==================== {
     {
             "a":    {
                     "1":    {
                             "1":    {
                                     "f000": "2013060509182820013187",       /* FD_Sid */
                                     "f001": "9"     /* FD_FLAG */
                             }
                     }
             },
             "p":    {
                     "1":    {
                             "1":    {
                                     "f000": "2013060509182820013187",       /* FD_Sid */
                                     "f001": "02",   /* FD_VersID */
                                     "f002": "0000", /* FD_OrigSend */
                                     "f003": "HVPS", /* FD_OrigSendSID */
                                     "f004": "402602000018", /* FD_OrigRecv */
                                     "f005": "HVPS", /* FD_OrigRecvSID */
                                     "f006": "20130605",     /* FD_OrigSendDate */
                                     "f007": "091833",       /* FD_OrigSendTime */
                                     "f008": "-1",   /* FD_StructType */
                                     "f009": "hvps.111.001.01",      /* FD_MesgType */
                                     "f010": "2013081820000866",     /* FD_MesgID */
                                     "f011": "2013081820000398",     /* FD_MesgRefID */
                                     "f012": "3",    /* FD_MesgPriority */
                                     "f013": "D",    /* FD_MesgDirection */
                                     "f014": ""      /* FD_Reserve */
                             }
                     }
             },
             "k":    {
                     "1":    {
                             "1":    {
                                     "f001": "9999"  /*  */
                             }
                     }
             }
     }
     3991 20130605 09:18:53.763 0 #Storage.cpp:  46# 信息 ====================显示存储结构信息==================== }, 耗时 0.000162 秒
     3991 20130605 09:18:53.763 0 #sndhdl.cpp: 690# 信息 处理失败
     3991 20130605 09:18:53.763 0 #sndhdl.cpp: 691# 信息 beps.121.001.01 往报处理失败, 耗时 0.121734 秒
     
     ,**********
   #+end_example
   
** TOFIX 仿真收到ibps305报文,msgid='4026020000182014011000000004',日志报错
   #+begin_example
     3986 20130604 17:48:10.179 0 #MyODBC.cpp: 609# 错误 执行SQL失败
     3986 20130604 17:48:10.179 0 #MyODBC.cpp: 239# 信息 The column FD_OrgngInPty in table TB_IBPS1305 does not allow null values.
     
     3986 20130604 17:48:10.179 0 #MyODBC.cpp: 239# 信息 The column FD_OrgnlMsgId in table TB_IBPS1305 does not allow null values.
     
     3986 20130604 17:48:10.179 0 #MyODBC.cpp: 239# 信息 The column FD_OrgnlMsgTp in table TB_IBPS1305 does not allow null values.
     
     3986 20130604 17:48:10.179 0 #MyODBC.cpp:1347# 错误 执行SQL语句失败
     3986 20130604 17:48:10.180 0 #MyODBC.cpp: 564# 信息 执行SQL: insert into TB_IBPS1305Lis(FD_Sid,FD_MsgId,FD_OrgngInPty,FD_OrgnlMsgId,FD_OrgnlMsgTp,FD_OrgnBusinTyCd) values ('2013060417480920013180','4026020000182014011000000004','402602000018','4026020000182014010600000153','ibps.101.001.01','C200')
     3986 20130604 17:48:10.194 0 #MyODBC.cpp:1012# 警告 发现1处错误
     3986 20130604 17:48:10.194 0 #MyODBC.cpp: 911# 错误 生成SQL语句失败
     3986 20130604 17:48:10.194 0 #rcvhdl.cpp: 861# 错误 插入数据失败  
   #+end_example
* 20130614问题汇总
** TOFIX 汇总对账,在业务类型为即时转账时,业务总笔数不对,但是金额总数相符
* 20130617问题汇总
** TOFIX 退汇来账信息付款人与收款人的信息互换了
   从仿真发出一笔CMT101往帐到平台，平台接收后因账号不符退回。仿真接收到平台的退汇来账信息，跟仿真最初发起的往帐信息一致，来帐的付款人还是原仿真往账付款人，收款人还是原仿真往帐的收款人。报文标识号：2013083100000004
** TOFIX 一代报文往账,加押的原始串没有空格,造成平台验押错误.例如msgid='2013083150004007'的报文
* 20130618问题汇总
** TOFIX 在哪里可以作一代报文的查询查复信息查询?
** TOFIX 收到及时转账排队报文后,就算补足余额,但原业务依然是排队状态
* 20130625问题汇总
** TOFIX 小额普通借记业务回执包,点击整包付款或部分付款都没有反应,查看后台日志,并未有008的日志出现,而且,此后再作其他业务,都无反应了
* 20130626问题汇总
** TOFIX 定期借记手工应答,点击之后没有反应,随后所有业务都做不了了,被卡死了,类似于20130625的那个问题
** TOFIX 小额实时借记业务提交后无法发送（测试pkg004）今天才不可做，昨天还可的
* 20130701问题汇总
** TOFIX 小额报文不能超过28K，超过28K的需要放入文件传输，但是小额发送票据影像信息时会超过28K
** TOFIX 过一段时间依然会卡死
* 20130708问题汇总
** TOFIX 仿真发起PKG001,包发起清算行行号给的是发起行行号,而不是清算行行号
* 20130709问题汇总
** TOFIX 仿真发起PKG002,业务类型不知道为何为08888?组报如下
   #+BEGIN_EXAMPLE
     :0BG:08888:52A:102100000030:58A:402602000018:30A:20141011:0BC:50005375:33G:000000000005506:CC4:402602012011:50C:120010190010007634              :50A:测试2000120109                                              :CC5:102100000030:59C:123456789                       :59A:随便吧                                                      :59B:无所谓                                                      :72A:仿真发出小额002明细                                         :B40:00000000
   #+END_EXAMPLE
** TOFIX 仿真发起pkg012通用信息业务包时,对附件作BASE64之后的结果跟我们的BASE64结果不匹配
* 20130711问题汇总
** TOFIX 仿真发起CMT233和CMT234的时候 收款人账号前补了很多"0"
* 20130712问题汇总
** TOFIX 发送beps121组包发送,金额填58.1x时,报"错误信息：写表TB_BEPS121失败！",日志无beps121的相应日志文件出现
** TOFIX 作净借记余额调整后,余额改变了,但是净借记额度没有改变
* 20130716问题汇总
** TOFIX 仿真往平台发PKG001，业务类型是财政直接支付退回、财政授权支付退回，“汇总金额、明细根据案例数据默认填写！！” 在仿真系统管理里不能查找到该汇总明细案例数据，建议仿真系统增加。
** TOFIX 系统管理==>>他行客户账户信息维护 --他行客户账户信息列表 该页面的“新增”功能不起作用，新增了也没法用上他行账号。
** TOFIX 仿真往平台发PKG002，业务类型是00113国库资金借记划拨，附加信息里的明细信息不能查询显示出来。
** TOFIX 仿真的小额借记业务包，不能手动打包。
* 20130821问题汇总
** TOFIX 仿真发起的ccms.921报文头没有系统标示号,而人行回应的有标示号
